### ISSUE TITLE
权限的问题

### ISSUE THREAD

**Issue by iYoullloveGitHub** [jpush/aurora-imui#1]
1.权限没有提示
2.自拍时,拍出来的图像是左右反的

**Comment by KenChoi1992** [comment]
@iYoullloveGitHub 看下 sample 中的 MessageListActivity，https://github.com/jpush/imui/blob/master/Android/sample/exampleui/src/main/java/imui/jiguang/cn/imuisample/messages/MessageListActivity.java#L139，我们在点击的回调中申请了权限。至于第二个问题确实是自拍后照片没有处理。

**Comment by KenChoi1992** [comment]
@iYoullloveGitHub 新版本解决了这个问题。
