### ISSUE TITLE
首次录制语音,弹出请求权限对话框,同意之后,录音继续计时,点击录音按钮后计时停止但是没有发送语音

### ISSUE THREAD

**Issue by lchad** [jpush/aurora-imui#10]
如题

这种情况下我认为合理的处理是请求到权限之后,不要再计时了,丢弃这次操作.
或者在打开录音面板之后立即请求权限.

机型:魅族 魅蓝3
Android5.1
Flyme 5.1.0.1

**Comment by KenChoi1992** [comment]
@lchad 在我们的 sample 中就是这么做的，打开录音面板就申请权限。
