### ISSUE TITLE
使用导航器跳转首次界面渲染会有严重的延迟

### ISSUE THREAD

**Issue by hzlgit** [jpush/aurora-imui#104]
`react-native` version:0.47.1
  `aurora-imui-react-native` version:最新
   导航器 : react-native-navigation
  平台 : ios

从会话列表首次进入会话界面，原生UI显示会有至少1s以上的延时
而且如果在`componentWillMount`里面插入数据，`messageList`界面展示不正常

**Comment by huangminlinux** [comment]
componentWillMount 里面插入数据，界面展示不正常，具体是什么意思？

**Comment by hzlgit** [comment]
@huangminlinux messageList的高度和宽度不正常，以至于数据显示的位置不正确

**Comment by hzlgit** [comment]
![292461d4-c5d2-4e12-8813-956080a24eae](https://user-images.githubusercontent.com/20529057/29800850-d1a5372e-8c9e-11e7-9155-4a3a6659b6c0.png)

**Comment by PeterLocas** [comment]
@hzlgit 你们输入框自己定制了吗

**Comment by huangminlinux** [comment]
@hzlgit 最下面那条消息高度不正常？ 还是说最后一条消息无法完全消失出来？

**Comment by hzlgit** [comment]
这个问题我们已经处理过了，只要在onLayout之后再初始化messageList即可
```
      let onViewLayout = (e) => {
            const layout = e.nativeEvent.layout;
            if (layout.height === 0) {
                return;
            }
            this.setState({
                isInitialized: true
            });
        };
        if (this.state.isInitialized) {
            return (
		<View style={styles.container}>
			<MessageListView/>
		</View>
            )
        }
        return (
		<View style={styles.container} onLayout={onViewLayout}>
		</View>
        )
```

**Comment by PeterLocas** [comment]
@hzlgit 网络头像你们是下载到本地然后加载的吗？

**Comment by hzlgit** [comment]
@PeterLocas 我们做了许多定制的，很多地方都改过了

**Comment by ww930912** [comment]
@hzlgit  我正准备将react-native-navigation导航换成和demo一样的react-navigation，不报任何希望的搜了下Issues，结果还真有和我一样遇到问题的人，哈哈，真心感谢你的回答，太谢谢了！
