### ISSUE TITLE
React Native run ios/android bug  Error:(34, 42) 错误: 找不到符号 符号:   类 CameraControllerListener 位置: 程序包 cn.jiguang.imui.chatinput.listener

### ISSUE THREAD

**Issue by PeterLocas** [jpush/aurora-imui#105]
### My environment？
 react-native 
 - `react-native` version:0.46.1
 - `aurora-imui-react-native` version:0.4.13

react native ios 
![image](https://user-images.githubusercontent.com/5467858/29799375-c9467f1a-8c95-11e7-9e05-3dc032a4a6ba.png)

react native android

![image](https://user-images.githubusercontent.com/5467858/29799387-dab0b63a-8c95-11e7-98cf-6e9bf56127f4.png)

**Comment by KenChoi1992** [comment]
@PeterLocas try `npm install` again

**Comment by PeterLocas** [comment]
Error:Project :app declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :aurora-imui-react-native. 没起作用啊

**Comment by KenChoi1992** [comment]
@PeterLocas  rebuild 一下项目

**Comment by PeterLocas** [comment]
android好了，但iOS一直报这个错 clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by huangminlinux** [comment]
有完整日志吗？

**Comment by PeterLocas** [comment]
![image](https://user-images.githubusercontent.com/5467858/29803968-dc87598e-8cb1-11e7-9ca2-5a6559d57e33.png)  @KenChoi1992 就这个错，打不开

**Comment by huangminlinux** [comment]
@PeterLocas  右键 reveal in log

**Comment by PeterLocas** [comment]
好了
