### ISSUE TITLE
React Native android messagelist没有下拉刷新？

### ISSUE THREAD

**Issue by PeterLocas** [jpush/aurora-imui#109]
- `react-native` version:0.47.2
 - `aurora-imui-react-native` 0.4.14:

**Comment by KenChoi1992** [comment]
@PeterLocas 有啊，在 `MessageList` 中加入 `onPullToRefresh` 属性，然后声明 `onPullToRefresh` 函数，参考一下 demo。

**Comment by PeterLocas** [comment]
多谢

**Comment by PeterLocas** [comment]
@KenChoi1992 这里好像必须发送一条消息才可以触发刷新，直接下来刷新没有效果

**Comment by PeterLocas** [comment]
@KenChoi1992 可以加你QQ吗

**Comment by KenChoi1992** [comment]
发布了新版本修复了这个问题。
