### ISSUE TITLE
点击播放录音图标不动

### ISSUE THREAD

**Issue by wentilin** [jpush/aurora-imui#110]
### My environment？

iOS master
点击播放录音图标不动
是否考虑在IMUIVoiceMessageContentView的layoutToVoice加入如下代码，然后在onTapContentView合适位置开始/停止动画（outgoing/incoming）
`self.voiceImg.animationImages = [UIImage.imuiImage(with: "outgoing_voice_1")!,UIImage.imuiImage(with: "outgoing_voice_2")!,UIImage.imuiImage(with: "outgoing_voice_3")!]`
`self.voiceImg.animationDuration = 1`

**Comment by huangminlinux** [comment]
下个版本加入播放动画。

**Comment by huangminlinux** [comment]
最新版本已添加播放动画。
