### ISSUE TITLE
React Native android 默认头像可以修改吗

### ISSUE THREAD

**Issue by PeterLocas** [jpush/aurora-imui#113]
- `react-native` 4.7.1:
 - `aurora-imui-react-native` 0.4.14:

![image](https://user-images.githubusercontent.com/5467858/29960027-90333e90-8f2c-11e7-83b8-f66bc437a0c2.png)
{"msgId":"1","status":"send_succeed","msgType":"text","isOutgoing":false,"text":"Fd","fromUser":{"userId":"450","displayName":"test","avatarPath":"file://data/user/0/com.testimui/files/RNFetchBlobTmp_ph7xi28h6egthu2gbubs5.jpg"}}

**Comment by KenChoi1992** [comment]
@PeterLocas 默认的头像可以改。把头像文件放在 res/drawable 目录下，然后改一下 `ReactMsgListManager` 中 `loadAvatarImage` 方法中 placeholder 的第二个参数，改为头像的文件名。
