### ISSUE TITLE
 React Native  android  isShowDisplayName={true} 发出的消息显示不了名字

### ISSUE THREAD

**Issue by PeterLocas** [jpush/aurora-imui#114]
### My environment？

 - `react-native` version:0.47.1
 - `aurora-imui-react-native` version:最新
 
![image](https://user-images.githubusercontent.com/5467858/30008202-7d8e007a-914f-11e7-9d99-f07e74c6a453.png)

**Comment by KenChoi1992** [comment]
@PeterLocas 原生的发送方默认是没有名字的

**Comment by PeterLocas** [comment]
@KenChoi1992 android没有名字？

**Comment by PeterLocas** [comment]
@KenChoi1992 还有一个问题 android中 messagelist是否没有下拉刷新

**Comment by KenChoi1992** [comment]
@PeterLocas 最新发布的版本这个问题修复了。
