### ISSUE TITLE
React Native android下拉刷新无法触发，必须发一条消息才能触发事件

### ISSUE THREAD

**Issue by PeterLocas** [jpush/aurora-imui#116]
### My environment？

 - `react-native` version:最新
 - `aurora-imui-react-native` version:最新

![image](https://user-images.githubusercontent.com/5467858/30159254-8b486f4a-93fa-11e7-94ea-16be3825daf2.png)

android下拉刷新无法触发，必须发一条消息才能触发事件,而且手动下拉刷新没有圆形进度条

**Comment by KenChoi1992** [comment]
参考最新 release
