### ISSUE TITLE
React Native Android 报错 iOS正常

### ISSUE THREAD

**Issue by PeterLocas** [jpush/aurora-imui#117]
### My environment？
 react-native 
 - `react-native` version:最新
 - `aurora-imui-react-native` version:

![image](https://user-images.githubusercontent.com/5467858/30268966-fe93626c-9719-11e7-9219-dbd0591828c7.png)

**Comment by KenChoi1992** [comment]
@PeterLocas 你没有定义 displayName

**Comment by PeterLocas** [comment]
不知道什么原因定义了，重新启动电脑又好了

**Comment by PeterLocas** [comment]
还是这个问题 @KenChoi1992  isShowDisplayName={true}   var user = {
            userId: payload.from + '',
            displayName: ext.name,
            avatarPath: ext.avatar
        }

**Comment by KenChoi1992** [comment]
@PeterLocas 我测试了没有问题呀

**Comment by PeterLocas** [comment]
有时会出现
