### ISSUE TITLE
React Native ios and android onPullToRefresh bug

### ISSUE THREAD

**Issue by PeterLocas** [jpush/aurora-imui#119]
- `react-native` version:最新
 - `aurora-imui-react-native` version:最新

ios 不手动刷新第一次进界面不会调用onPullToRefresh ，可之后每次再进界面会触发onPullToRefresh，很奇怪的问题，这样会导致分页加载聊天记录出现问题。

android 下拉刷新没有进度条，无法手动刷新触发，偶尔才能触发一次出来，

**Comment by huangminlinux** [comment]
下个版本中修复这个问题
