### ISSUE TITLE
可以增加其他输入视图吗？

### ISSUE THREAD

**Issue by xiaosongfu** [jpush/aurora-imui#12]
可以增加其他的输入视图吗？因为不同项目有不同的需求
比如（只需要语音和文本）：
![你看不到我 ^_^](http://image.ifuxs.cn/2017/05/keyboard-voice.png)  

如果等不了你们，到时候我们写好了可以给你提 PR 吗？ ^_^

**Comment by xiaosongfu** [comment]
![^_^](http://image.ifuxs.cn/2017/05/keyboard-voice2.png)

**Comment by huangminlinux** [comment]
非常欢迎你的 PR。
 不过我们这边建议可以上传到你的 github上，到时候我们提供外部链接的方式跳过去， 不然全部库放到一起太重了。

**Comment by xiaosongfu** [comment]
对，我也觉得放在一起不好，因为各种输入视图应该可以被单独引入，而不应该揉在一起

**Comment by musicode** [comment]
@xiaosongfu 你的这个输入视图有啥进展了么

**Comment by xiaosongfu** [comment]
@musicode 做好了，但是我们项目没有上滑取消等需求，所以很粗躁，意义不大

**Comment by lfh22** [comment]
@musicode可以提供一下思路方向吗？谢谢

**Comment by musicode** [comment]
为啥要 at 我。。。

**Comment by JoshLipan** [comment]
参考 #372
