### ISSUE TITLE
react native 集成 出问题

### ISSUE THREAD

**Issue by githubbaichi520** [jpush/aurora-imui#121]
缺少文件 RCTAuroraIMUI-Swift.h

![1234](https://user-images.githubusercontent.com/26995854/30685248-e22f19f2-9ee6-11e7-8ca7-5c4513281642.jpeg)

**Comment by huangminlinux** [comment]
需要先编译 RCTAuroraIMUI.framework， 才会生成 RCTAuroraIMUI-Swift.h 文件

**Comment by huangminlinux** [comment]
先关闭这个 issue，如果问题还没解决可以重新打开
