### ISSUE TITLE
ReactNative IOS android

### ISSUE THREAD

**Issue by PeterLocas** [jpush/aurora-imui#123]
### My environment:
 react-native 
- `react-native` version:最新
- `aurora-imui-react-native` version:最新

![image](https://user-images.githubusercontent.com/5467858/30738978-73e18b36-9f51-11e7-9b43-21e8a2ba3a8c.png)
一进界面就会调用onPullToRefresh 而且如果只写onPullToRefresh消息会错错乱丢失的情况，必须在constructor先加一些消息才正常。android 还是没有下刷新的进度条。

**Comment by PeterLocas** [comment]
再加一个问题，andorid是否可以把默认发出去的消息气泡颜色变明显一些

**Comment by KenChoi1992** [comment]
@PeterLocas iOS 跟 Android 用的气泡是相同的，可能只是背景颜色不一样导致的。

**Comment by PeterLocas** [comment]
@KenChoi1992 背景色能改吗

**Comment by KenChoi1992** [comment]
0.5.8-rn fixed

**Comment by musicode** [comment]
同吐槽背景色，唉
