### ISSUE TITLE
升级Xcode9.0错误，iOS11.0情况下的处理

### ISSUE THREAD

**Issue by NameOfSelf** [jpush/aurora-imui#125]

**Comment by NameOfSelf** [comment]
希望大佬处理下

**Comment by huangminlinux** [comment]
报什么错误？

**Comment by flyinghawker** [comment]
我也有问题，按照安装说明，
PROJECT -> TARGETS -> Build Settings -> Enable Bitcode Set to No
Find PROJECT -> TARGETS -> General -> Embedded Binaries and add RCTAuroraIMUI.framework
Before build you project ,you should build RCTAuroraIMUI.framework
在构建项目之前，我先点选构建了RCTAuroraIMUI.framework，但是有报错，
现在npm install出现问题无法安装，所以没办反完全复制错误。
错误是关于RCTViewManager not found（大概这个名字） 无法找到。
折腾几个小时也没有结果，等后面npm安装好了，再粘贴原版错误。谢谢。
我按照网上的建议，删除了所有~/Library/Developer/DerivedData里面的结果文件，clean之后重新编译，始终如此，
  "react": "16.0.0-alpha.6",
  "react-native": "0.44.0",
  "aurora-imui-react-native": "^0.4.21",
   xcode 9.0

**Comment by flyinghawker** [comment]
@huangminlinux 
刚reproduce了一下，错误如下
'React/RCTViewManager.h' file not found

**Comment by NameOfSelf** [comment]
我是下载下来的ZIP，打开sample的工程编译错误。错误如下：
Undefined symbols for architecture x86_64:
  "__T0So22AVCapturePhotoSettingsC12AVFoundation01_abC16SwiftNativeTypesACWP", referenced from:
      __T06sample14IMUICameraViewC23capturePhotoAfter_iOS10yyFyycfU_ in IMUICameraView.o
  "__T012AVFoundation39_AVCapturePhotoSettingsSwiftNativeTypesPAAE016availablePreviewc11PixelFormatG0SaySo8NSNumberCGfg", referenced from:
      __T06sample14IMUICameraViewC23capturePhotoAfter_iOS10yyFyycfU_ in IMUICameraView.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
---------------------------------------------分割线--------------------------------------
另外还有工程中有这样的代码：if #available(iOS 10.0,*){}else{}并没有iOS11.0的情况，这样iOS11.0系统会不会出现问题。这个我还没测试。

**Comment by huangminlinux** [comment]
@flyinghawker 
 'React/RCTViewManager.h' file not found 这个错误是应该 react 相关库没有完成编译，可以先编译主工程（这个地方可能会报 RCTAuroraIMUI.framework  编译不通过），然后再编译 RCTAuroraIMUI.framework 。

**Comment by huangminlinux** [comment]
@NameOfSelf  使用 Version 9.0 beta 2 (9M137d) 编译没出现你说所的错误。

if #available(iOS 10.0,*){}else{} 意思是 iOS 10+ 的系统

**Comment by flyinghawker** [comment]
@NameOfSelf 你有解决你的问题吗，我和你遇到同样的问题，搜索很多案例，都没有对应的办法解决

**Comment by NameOfSelf** [comment]
假期外出。明天我再好好看下

**Comment by NameOfSelf** [comment]
@flyinghawker  应该是架包问题。我下载下来的ZIP，打开sample工程就是这个错误。
@huangminlinux 我用的9.0（不包含beta）

**Comment by NameOfSelf** [comment]
补充下是9.0（9A235），好像这个版本有个bug。

**Comment by huangminlinux** [comment]
刚刚试着安装 Xcode 9 正式版，确实会报这个错误，这貌似是 Xcode 的 bug，AVfoundation 的几个接口被标记为私有了，这个问题在 Xcode 9.0 Beta 6 (9M214v) 已经修复了，估计在下个正式版才会修复这个问题， 可以先使用最新的 Xcode beta 版。
https://forums.developer.apple.com/thread/86810#259270

**Comment by NameOfSelf** [comment]
已解决，谢谢👍

**Comment by flyinghawker** [comment]
@NameOfSelf 请问你是怎么解决的，我下载了最新的 xcode 9.1 beta 2 (9B46), 还是有类似错误。

**Comment by NameOfSelf** [comment]
我现在用9.0beta版，9.1beta版有错误的话我只能等了
