### ISSUE TITLE
Native iOS video record callback to wrong delegate in InputView

### ISSUE THREAD

**Issue by joelo0107** [jpush/aurora-imui#128]
### My environment:

- native version

#### iOS/IMUIInputView/Controllers/IMUIInputView.swift
    public func didRecordVideo(with videoPath: String, durationTime: Double) {
        self.inputViewDelegate?.finishRecordVoice?(videoPath, durationTime: durationTime)
    }

**Comment by huangminlinux** [comment]
可以升级到 0.5.4 版本，修复了这个问题。
