### ISSUE TITLE
关于图片选择的优化建议

### ISSUE THREAD

**Issue by china-coder** [jpush/aurora-imui#131]
android  
 native version:7.0
图片选择的模式，在图片数量比较多的情况下，翻阅比较麻烦，能否像微信那样，支持在图片浏览器里面选择呢？

**Comment by KenChoi1992** [comment]
@china-coder 有图片浏览的按钮，不过隐藏掉了

**Comment by china-coder** [comment]
要怎样才能显示出来呢？哈哈

**Comment by KenChoi1992** [comment]
@china-coder 需要改一下源代码，找到 layout_chatinput_selectphoto.xml ，然后把最后一个按钮显示出来。

**Comment by china-coder** [comment]
好的 我试一下

**Comment by tianweicc** [comment]
@KenChoi1992  只有android么？  ios没有么？

**Comment by tianweicc** [comment]
@china-coder @KenChoi1992  这个文件 在哪啊  没看着啊

**Comment by china-coder** [comment]
兄弟，源码里面应该有。

**Comment by tianweicc** [comment]
@china-coder 兄die  可以具体说说哪个源码文件么 我看了node_modules里面的源码 没找到啊

**Comment by china-coder** [comment]
aurora-imui/Android/chatinput/src/main/res/layout/layout_chatinput_selectphoto.xml

**Comment by china-coder** [comment]
兄弟 android的问题，你非要奥node里面找，这个我没有办法啊 哈哈

**Comment by tianweicc** [comment]
感觉我们两个说的好像不是一个方向。。 哥们你的问题是 进入图库选择图片么 @china-coder

**Comment by tianweicc** [comment]
@KenChoi1992 你好  有没有图片选择？  图片几千的话  这样滑动选择 实在不方便

**Comment by KenChoi1992** [comment]
@tianweicc 可以自己做的，下个版本我们把这个事件暴露出来。

**Comment by KenChoi1992** [comment]
0.6.2 版本 暴露了这个按钮，可以自己添加点击事件或隐藏。

**Comment by tianweicc** [comment]
@KenChoi1992  暴露的方法叫什么？

**Comment by KenChoi1992** [comment]
@tianweicc 
```
ImageButton button = mChatInput.getSelectAlbumBtn();
```
也可以使用属性来隐藏或显示：
```
<cn.jiguang.imui.chatinput.ChatInputView
        app:showSelectAlbum="true"/>
```

**Comment by tianweicc** [comment]
![11](https://user-images.githubusercontent.com/17263719/34511525-38850e86-f097-11e7-8ddb-ec05ed284b5c.jpg)
相机打开后 点击全屏  无法拍照 只有缩小 拍照跟切换摄像头才会出来  android 魅族pro6

**Comment by tianweicc** [comment]
@KenChoi1992 android输入框 输入字数过多 光标丢失
