### ISSUE TITLE
#Android 可以显示或者自定义下拉加载的loading view吗？

### ISSUE THREAD

**Issue by Sky-Walkrr** [jpush/aurora-imui#132]
### My environment: Android MessageList 0.48
可以显示或者自定义下拉加载的loading view吗，比如说下拉加载历史消息的时候显示SwipeRefreshLayout，数据加载成功refresh layout消失.目前发现下拉加载是没有loading view显示的。

**Comment by KenChoi1992** [comment]
@Sky-Walkrr 更新了。
