### ISSUE TITLE
低版本打开摄像机崩溃。

### ISSUE THREAD

**Issue by china-coder** [jpush/aurora-imui#134]
### My environment:

native android  
native version 4.1.2
系统版本emotion ui 1.0
手机存储4G
内存卡：2G
部分错误信息

mm_camera_read_preview_frame Read Preview 
af_run_algorithm:Fail Invalid

**Comment by KenChoi1992** [comment]
@china-coder 发布了 chatinput 0.5.0 版本，修复了这个问题。

**Comment by china-coder** [comment]
好的 我测试一下
