### ISSUE TITLE
Failed to resolve: com.github.w446108264:AndroidEmoji:1.0.0

### ISSUE THREAD

**Issue by A-DoubleCheng** [jpush/aurora-imui#138]
### My environment:

Error:Failed to resolve: com.github.w446108264:XhsEmoticonsKeyboard:2.0.4
<a href="openFile:D:/workspace/ZYD/workspace/ZYD/node_modules/aurora-imui-react-native/ReactNative/android/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
Error:Failed to resolve: com.github.w446108264:AndroidEmoji:1.0.0
<a href="openFile:D:/workspace/ZYD/workspace/ZYD/node_modules/aurora-imui-react-native/ReactNative/android/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by KenChoi1992** [comment]
在你项目的 build.gradle 中加入：
```
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}

```

**Comment by PeterLocas** [comment]
![image](https://user-images.githubusercontent.com/5467858/33107796-77edaca0-cefe-11e7-8702-4d67864f2b1d.png)

@KenChoi1992 代码放到哪里并未解决
