### ISSUE TITLE
发送的第一条消息是否应该置顶

### ISSUE THREAD

**Issue by xiaosongfu** [jpush/aurora-imui#14]
当前聊天记录为空的时候，发送的第一条消息是否应该放置到顶不呢？就 qq 那些一样
图：
![^_^](http://image.ifuxs.cn/201705/messagelist.png)

**Comment by KenChoi1992** [comment]
@xiaosongfu 了解，这个问题应该是 RecyclerView 的默认样式。

**Comment by xiaosongfu** [comment]
这个问题不解决，应用不能上线。我也看了源码，修复不了，你们有计划着手解决这个问题吗？

**Comment by KenChoi1992** [comment]
@xiaosongfu 感谢提交 PR，请在 dev 分支上提交一次。
