### ISSUE TITLE
demo点击第二次输入框时也会导致页面上移

### ISSUE THREAD

**Issue by StonyMoon** [jpush/aurora-imui#140]
### My environment:
联想P1 C72
Android 6.0

在点击一次输入框后，屏幕上移。再次点击，屏幕仍然会上移
第一次点击输入框
![screenshot_20171114-232359-670](https://user-images.githubusercontent.com/25023887/32788311-db38bfcc-c993-11e7-828e-5867de067e5c.jpg)

第二次点击输入框
![screenshot_20171114-232402-364](https://user-images.githubusercontent.com/25023887/32788318-e23d6868-c993-11e7-92b9-ae1ff4bf85bb.jpg)

**Comment by KenChoi1992** [comment]
@StonyMoon 上移后没有恢复？我这里测试是正常的。

**Comment by weisuodaodi1** [comment]
我也遇到了这个问题，尤其是点击了图片或者表情之后，再次点击图片或者表情他们不会下去了，然后再次点击输入法，输入框就会顶到最顶处

**Comment by IndignantAngel** [comment]
我也遇到了这个问题。还有就是点击语音，键盘也没有弹回去。
![tim 20171213103724](https://user-images.githubusercontent.com/8613363/33919117-e50ae47a-dff1-11e7-9077-f5610a54542b.png)

**Comment by KenChoi1992** [comment]
试试新版本，应该修复了这个问题。
