### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by swustzl** [jpush/aurora-imui#145]
### My environment:

- `react-native` version:0.50.3
- `aurora-imui-react-native` version:0.5.6
   

![psgjpc 1s cc2sekruwh_s](https://user-images.githubusercontent.com/9999528/32879246-2720a822-cae4-11e7-9c2c-668b8b461632.png)

**Comment by KenChoi1992** [comment]
@swustzl 刚用 0.50.3 测试了一下，可以编译成功。

**Comment by swustzl** [comment]
对这个gradle 的版本有最低限制吗

**Comment by KenChoi1992** [comment]
没有限制，改成你自己的版本就行了，包括 buildToolsVersion

**Comment by swustzl** [comment]
buildToolsVersion 及 compiledSdkVersion ，这两个也不再限制 25 以上了吗？我的原本是23的

**Comment by KenChoi1992** [comment]
只要你安装了这两个版本的 build tools 以及 sdk 就行，另外如果改了 compiledSdkVersion ，
```
compile 'com.android.support:appcompat-v7:25.3.1'
```
这里也要改成对应的版本。

**Comment by swustzl** [comment]
我刚试的，buildToolsVersion 及 compiledSdkVersion 版本还是需要25，另外`dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0-beta2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }` 这个需要3以上的，我的原本是gradle:2.2.3,   以及 `distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-rc-1-all.zip` 这个也要是4，我的是gradle-2.14.1-all.zip，  这样才成功运行。。。。

**Comment by swustzl** [comment]
不明白都是啥作用。。

**Comment by KenChoi1992** [comment]
这是因为你指定的 gradle 版本是 3.0.0-beta2，相应的 gradle.properties 也要改，AS 都会提示的。gradle 正式发布了 3.0.0，你可以试试，提升了编译速度。
