### ISSUE TITLE
个人建议把RN android iOS demo写在一起

### ISSUE THREAD

**Issue by PeterLocas** [jpush/aurora-imui#148]
个人建议把RN android iOS demo写在一起

**Comment by KenChoi1992** [comment]
@PeterLocas 我们的 [JMessage-react-plugin](https://github.com/jpush/jmessage-react-plugin) 是写在一起的，你可以先参考这个。

**Comment by KenChoi1992** [comment]
@PeterLocas  dev 下更新了，可以参考一下新版本

**Comment by KenChoi1992** [comment]
@PeterLocas master 和 dev 都更新了
