### ISSUE TITLE
同时添加send和recive自定义消息样式时，其中一个无效

### ISSUE THREAD

**Issue by china-coder** [jpush/aurora-imui#157]
### My environment:

同时添加自定义消息样式时，其中一个无效，必须要注释掉第一个，第二个才起作用，否则第二个显示为文本的样式。

**Comment by KenChoi1992** [comment]
@china-coder 你怎么做的

**Comment by china-coder** [comment]
自定义的holder
    private static class DefaultLogSendViewHolder extends LogViewHolder<IMessage> {
        public DefaultLogSendViewHolder(View itemView, boolean isSender) {
            super(itemView, isSender);
        }
    }

recive的config 
 CustomMsgConfig config1 = new CustomMsgConfig(14, R.layout.item_log_receive_txt, false, DefaultLogSendViewHolder.class);
                    //CustomMsgConfig config2 = new CustomMsgConfig(15, R.layout.item_log_send_text, true, DefaultLogSendViewHolder.class);
                    mAdapter.addCustomMsgType(14, config1);
                    message.setType(14);

send的config
CustomMsgConfig config2 = new CustomMsgConfig(15, R.layout.item_log_send_text, true,      DefaultLogSendViewHolder.class);
                    mAdapter.addCustomMsgType(15, config2);
                    message.setType(15);

**Comment by KenChoi1992** [comment]
@china-coder 还有你的 Message 也要 setType

**Comment by china-coder** [comment]
我看了一下源码，好像并没有对自定义的数组进行遍历，源码如下，使用的版本为0.5.4
      for (int i=0; i < mCustomMsgList.size(); i++) {
            CustomMsgConfig config = mCustomMsgList.valueAt(0);//这里并没有使用for循环的i值
            if (message.getType().getCustomType() == config.getViewType()) {
                return config.getViewType();
            }
        }

**Comment by china-coder** [comment]
message的settype我按照文档上面的已经做了，如下
   public void setType(int type) {
        this.messageType.setCustomType(type);
    }

**Comment by KenChoi1992** [comment]
@china-coder 这个确实是个 bug，发布了新版本跟你说一声

**Comment by china-coder** [comment]
okay think

**Comment by KenChoi1992** [comment]
@china-coder 可以了，发布了 0.5.5 ，你再试试

**Comment by china-coder** [comment]
好的，我试一试

**Comment by china-coder** [comment]
可以了，谢谢。
