### ISSUE TITLE
react native ios集成

### ISSUE THREAD

**Issue by giantss** [jpush/aurora-imui#159]
### My environment:

- `react-native` 0.49.5
- `aurora-imui-react-native` 0.5.10

npm install aurora-imui-react-native --save
react-native link
都ok
找到 PROJECT -> TARGETS -> General -> Embedded Binaries 然后添加 RCTAuroraIMUI.framework。
找到 PROJECT -> TARGETS -> Build Phases -> Target Dependencies 添加 RCTWebSocket。
ok
然后xcode build 报错
![1476cf93a2d6f9e93324a9303c40134e](https://user-images.githubusercontent.com/13778798/33354015-b4868d2e-d4eb-11e7-8e80-b6eee0498622.jpg)

**Comment by huangminlinux** [comment]
可以参考这个 #125  issue。
