### ISSUE TITLE
播放第二条语音时，正在播放的第一条语音动画未停止

### ISSUE THREAD

**Issue by baiyuliang** [jpush/aurora-imui#16]
播放第二条语音时，正在播放的第一条语音动画未停止

**Comment by KenChoi1992** [comment]
@baiyuliang 这确实是个 bug，正在修复

**Comment by KenChoi1992** [comment]
@baiyuliang 这个 bug 在这个 commit https://github.com/jpush/aurora-imui/commit/e712f3f6d4cf383c54de578632e26a5ef552889b 上修复了。

**Comment by KenChoi1992** [comment]
@baiyuliang 发布了新版本，修复了这个问题，重新拉一下代码试试。
