### ISSUE TITLE
关于react native文档的一些小瑕疵

### ISSUE THREAD

**Issue by giantss** [jpush/aurora-imui#160]
![image](https://user-images.githubusercontent.com/13778798/33356657-a550da6e-d4f8-11e7-9497-2a634612a8b0.png)

**Comment by giantss** [comment]
![image](https://user-images.githubusercontent.com/13778798/33356677-c1c525f6-d4f8-11e7-8773-b2884062e6e1.png)

**Comment by KenChoi1992** [comment]
@giantss 感谢指出问题，改了。

**Comment by huangminlinux** [comment]
感谢指正。
