### ISSUE TITLE
ionic3跨平台UI插件需求

### ISSUE THREAD

**Issue by xumingyi** [jpush/aurora-imui#164]
### My environment:
基于cordova+ionic+angularjs的跨平台开发
- `ionic` version: 3.19.0 
- `cordova` version: 7.1.0 
- `angularjs` version:2.0以上

**Comment by huangminlinux** [comment]
ionic3 和 RN 机制不太一样，不会再这个库中支持。以后可能会单独开发基于 ionic 的 UI 插件。

**Comment by xumingyi** [comment]
谢谢
