### ISSUE TITLE
react native demo  sample/app/app.js代码有错误

### ISSUE THREAD

**Issue by giantss** [jpush/aurora-imui#165]
449行  `generateIOSView`方法
![image](https://user-images.githubusercontent.com/13778798/33409553-087b8210-d5b7-11e7-9d6e-a1d01203fa90.png)
导致了了我们在集成的时候复制了app.js代码到我的项目中运行报错了
![image](https://user-images.githubusercontent.com/13778798/33409705-bd110a1a-d5b7-11e7-81f0-de40260ed9a9.png)

**Comment by huangminlinux** [comment]
已更新，感谢指正。
