### ISSUE TITLE
点击播放中的语音，停止播放时动画图标未复原

### ISSUE THREAD

**Issue by baiyuliang** [jpush/aurora-imui#17]
点击播放中的语音，停止播放时动画图标未复原

**Comment by KenChoi1992** [comment]
@baiyuliang https://github.com/jpush/aurora-imui/commit/1e7bc2cf32aa2bf3adf1c4ed6b4e7df7cd6f7f03 这个提交应该修复了这个问题。

**Comment by KenChoi1992** [comment]
@baiyuliang 发布了新版本，修复了这个问题，重新拉一下代码。
