### ISSUE TITLE
提一个小小的需求？

### ISSUE THREAD

**Issue by PeterLocas** [jpush/aurora-imui#170]
聊天窗口输入框，能否加一个开关，可以控制发送消息类型的显示，比如可以设置成只显示发送按钮，其他功能都没有就把下面那一排隐藏，在输入框最右边加上发送按钮。

**Comment by PeterLocas** [comment]
像这样![image](https://user-images.githubusercontent.com/5467858/33535601-17f6a354-d874-11e7-92a1-422c5ba5694e.png)

**Comment by lulululbj** [comment]
个性化的需求 自己改一下代码就好了

**Comment by JoshLipan** [comment]
参考 #372
