### ISSUE TITLE
在华为平板PLE-703L的设备商，录音设备无法正常操作，所有录制的音频都只有1秒，并且这一秒的录音文件是打开不开的

### ISSUE THREAD

**Issue by ronaldoWang** [jpush/aurora-imui#175]

**Comment by KenChoi1992** [comment]
@ronaldoWang 录音权限获取了吗

**Comment by ronaldoWang** [comment]
是这样的，我在华为手机meta7 和meta9都测试过，都是正常的。只有华为的这个平板有问题。经过反复测试，确认是代码的问题。修改如下：
类名：RecordVoiceButton
方法：finishRecord
                MediaPlayer mp = new MediaPlayer();
                mp.setAudioStreamType(AudioManager.STREAM_MUSIC);
                try {
                    mp.setDataSource(myRecAudioFile.getPath());
                    mp.prepare();
方法：startRecording 
            recorder = new MediaRecorder();
            recorder.setAudioSource(MediaRecorder.AudioSource.MIC);
            // 设置录音的保存格式
            recorder.setOutputFormat(MediaRecorder.OutputFormat.AMR_NB);
            // 设置录音的编码
            recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB);
            recorder.setOutputFile(myRecAudioFile.getAbsolutePath());
            myRecAudioFile.createNewFile();
修改之后，测试无问题

**Comment by KenChoi1992** [comment]
@raoxudong 估计华为平板不支持 m4a 格式。因为有开发者要求 iOS 和 Android 可以播放同一个文件，所以编码格式是 m4a。
