### ISSUE TITLE
android iOS 聊天背景颜色不一致，聊天气泡颜色不一致

### ISSUE THREAD

**Issue by PeterLocas** [jpush/aurora-imui#176]
if react-native 
- `react-native` version:最新
- `aurora-imui-react-native` version:最新
  

![image](https://user-images.githubusercontent.com/5467858/33812358-797434fc-dde2-11e7-8e8b-06644d38eac3.png)

仔细查看 bubble颜色不一致，还有聊天背景色不一致

**Comment by huangminlinux** [comment]
下个版本处理这个问题。

**Comment by PeterLocas** [comment]
@huangminlinux 
 1.能否给evert类型消息加上点击事件，给所有消息都加上 extras属性。
2.还有custom消息不应该换成content，还应该用text，只需价格判断即可（个人感觉）

**Comment by KenChoi1992** [comment]
@PeterLocas 所有消息都加上 extras 属性了。event 消息要点击事件的话，你可以用 custom 消息来做。

**Comment by KenChoi1992** [comment]
@PeterLocas 新版本可以修改背景颜色了。
