### ISSUE TITLE
拍照，录像黑屏（小米note，android6.0）

### ISSUE THREAD

**Issue by baiyuliang** [jpush/aurora-imui#18]
拍照，录像黑屏（小米note，android6.0）

**Comment by KenChoi1992** [comment]
@baiyuliang 打开系统设置，看看应用的拍照权限有没有打开。

**Comment by KenChoi1992** [comment]
@baiyuliang 和 https://github.com/jpush/aurora-imui/issues/4 这个 issue 一样，关闭了。
