### ISSUE TITLE
选择照片快速点击导致显示bug

### ISSUE THREAD

**Issue by lulululbj** [jpush/aurora-imui#181]
**Android**

选择发送照片，对单张照片快速点击两次，发送按钮为灰色，但仍然显示数字 1，且不可发送。
![tim 20171213162019](https://user-images.githubusercontent.com/13194137/33928629-8c0a8bde-e021-11e7-8f3f-3b2d4db153ac.png)

**Comment by KenChoi1992** [comment]
@lulululbj 确实是个 bug，下个版本修复。
