### ISSUE TITLE
安卓版的聊天输入框输入文字后会崩溃

### ISSUE THREAD

**Issue by weisuodaodi1** [jpush/aurora-imui#183]
我查看源代码，问题是出在ChatInputVIew的1014行，mSelectPhotoView.getSelectFiles().size() > 0 这里，我看getSelectFiles()方法获取的对象为Null,这里没有做非空判定，然后直接崩溃了。是还需要做什么其他操作吗？我新创建一个项目，就只是添加输入框，按照文档进行操作，然后输入文字也是一样的错误。

**Comment by KenChoi1992** [comment]
@weisuodaodi1 下个版本修复
