### ISSUE TITLE
最新版 RN android报错

### ISSUE THREAD

**Issue by PeterLocas** [jpush/aurora-imui#188]
### My environment:

- `react-native` version:最新
- `aurora-imui-react-native` version:最新
   -
![image](https://user-images.githubusercontent.com/5467858/34037924-214cd8e4-e150-11e7-88e9-f2b3b9048b5d.png)

![image](https://user-images.githubusercontent.com/5467858/34037917-191afc0a-e150-11e7-97de-2a76a870310b.png)

**Comment by KenChoi1992** [comment]
@PeterLocas 你的 extra 传了 number

**Comment by PeterLocas** [comment]
@KenChoi1992 不能包含number还是？

**Comment by PeterLocas** [comment]
@KenChoi1992 没明白你的意思，我上一版本是可以运行的

**Comment by PeterLocas** [comment]
@KenChoi1992 两张图是两个问题

**Comment by KenChoi1992** [comment]
@PeterLocas  extras 只能传 string

**Comment by PeterLocas** [comment]
message.text = payload.Contents;
        message.content = '<body style="background-color: rgba(142,142,142,0.6)"> <p style="color:#3b62ff">' + payload.Contents + '</p></body>'
        message.contentSize = {'height': 80, 'width': 200}
        message.extras = payload.extras;  @KenChoi1992 这样写不行？content 和text不能一起写？

**Comment by PeterLocas** [comment]
@KenChoi1992 我这代码在0.5.10没有问题 啊

**Comment by KenChoi1992** [comment]
自定义消息的话，还是只传 content，text 你设置了也没用，根据文档来。

**Comment by PeterLocas** [comment]
@KenChoi1992 普通消息啊上一版没问题啊

**Comment by KenChoi1992** [comment]
上一版都没改这个地方

**Comment by PeterLocas** [comment]
我退回上一版了

**Comment by KenChoi1992** [comment]
你 list_item 是什么东西
