### ISSUE TITLE
加载本地聊天记录页面加载过慢

### ISSUE THREAD

**Issue by NameOfSelf** [jpush/aurora-imui#193]

**Comment by NameOfSelf** [comment]
聊天记录暂时存到FMDB数据库中，但是我进入页面取出所有的聊天记录加载，要等待数十秒。消息的展示采用创建消息体[self.messageList appendMessageWith:message];然后添加显示。尤其是有图片的时候比较慢，这我处理有问题还是记录太多就是会出现这样的情况，忘回复

**Comment by huangminlinux** [comment]
你的消息记录一次获取所有的记录？正常应该分页获取历史消息

**Comment by NameOfSelf** [comment]
是应该分页的。现在是获取所有，卡顿是正常的是吧。

**Comment by NameOfSelf** [comment]
我在原有的基本内容类扩展了一个自定义样式的contentView，public class IMUIContractMessageContentView: UIView, IMUIMessageContentViewProtocol 加载这个就比较慢

**Comment by huangminlinux** [comment]
需要分析 数据库获取历史消息回调花费多少时间， 自定义 contentView 初始化花费多少时间， 等待数十秒确实太夸张了。

**Comment by NameOfSelf** [comment]
谢谢，还有一个是聊天的最后一条消息应该显示在键盘上面。现在键盘挡着了

**Comment by huangminlinux** [comment]
@NameOfSelf  https://github.com/jpush/aurora-imui/issues/104#issuecomment-326168311 看看是不是同一个问题。

**Comment by NameOfSelf** [comment]
做了分页，已经好了。还要继续优化，输入框后续重新定制下，谢谢
