### ISSUE TITLE
_this.refs.ChatInput.showMenu is not a function

### ISSUE THREAD

**Issue by sofwu** [jpush/aurora-imui#194]
1、_this.refs.ChatInput.showMenu is not a function
2、点ChatInput的其他按钮都没反应

**Comment by KenChoi1992** [comment]
@sofwu 你集成成功了吗？可以参考一下 ReactNative/sample/app

**Comment by sofwu** [comment]
@KenChoi1992 
Failed to resolve: com.github.w446108264:AndroidEmoji:1.0.0
Failed to resolve: com.github.w446108264:XhsEmoticonsKeyboard:2.0.4
gradle的时候出现这两个错误

**Comment by KenChoi1992** [comment]
在项目的 build.gradle 加上
```
allprojects {
  repositories {
    ...
    maven { url 'https://jitpack.io' }
  }
}
```

**Comment by sofwu** [comment]
@KenChoi1992 
aurora-imui-react-native: 0.5.14
react-native: 0.44.0
点录音、相册、拍照都不会把输入文本框切换走，只有发送按钮能点，我是按照你的demo来写

**Comment by KenChoi1992** [comment]
@sofwu 那你看看有哪些地方漏掉了。

**Comment by sofwu** [comment]
@KenChoi1992 现在好了，有新的问题就是点拍照会连拍三张

**Comment by KenChoi1992** [comment]
@sofwu 点击拍照，demo 是正常的啊，只拍一张。历史记录的第一条不显示，估计是你取记录时，没计算好数组下标。
