### ISSUE TITLE
【IOS 真机调试出错】

### ISSUE THREAD

**Issue by contineu0818** [jpush/aurora-imui#198]
### My environment:

使用官方提供的样例。ios虚拟机调试没有问题，真机运行的时候会卡在启动屏，xcode报错：
dyld: Library not loaded: @rpath/RCTAuroraIMUI.framework/RCTAuroraIMUI
  Referenced from: /var/containers/Bundle/Application/DDDE214C-5255-4D69-8AD1-F5F80D59A4FF/TestRNIMUI.app/TestRNIMUI
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/DDDE214C-5255-4D69-8AD1-F5F80D59A4FF/TestRNIMUI.app/Frameworks/RCTAuroraIMUI.framework/RCTAuroraIMUI: code signing blocked mmap() of '/private/var/containers/Bundle/Application/DDDE214C-5255-4D69-8AD1-F5F80D59A4FF/TestRNIMUI.app/Frameworks/RCTAuroraIMUI.framework/RCTAuroraIMUI'

**Comment by huangminlinux** [comment]
确保 手机\电脑没有翻墙，确保手机电脑连同一个 wifi

**Comment by contineu0818** [comment]
@huangminlinux 我确认是连在一个wifi下面的，电脑手机都没有翻墙，请问图上这一部分需要设置一下吗？我在百度上搜索到报错“Reason: no suitable image found”有可能是引入第三方库签名错误导致的，我设置成我们的开发账号之后不报错了，但是依然卡在启动屏。
![image](https://user-images.githubusercontent.com/24377663/34375693-ba140eea-eb22-11e7-94dd-be10d2771251.png)

**Comment by huangminlinux** [comment]
卡在启动页面基本就是 jsCodeLocation 加载的问题。

可以试着修改 Appdelegate.m 中的加载代码，通过 url 来加载。

**Comment by contineu0818** [comment]
@huangminlinux 请问在官方提供的这个样例中应该怎么改，能不能烦请你提供一下修改之后的Appdelegate.m，万分感激！

**Comment by huangminlinux** [comment]
```
jsCodeLocation = [NSURL URLWithString:@"http://192.168.8.185:8081/index.ios.bundle?platform=ios&dev=true"]; 
```
换成自己电脑的 IP

**Comment by huangminlinux** [comment]
另外 这项配置也不要忘了 ，https://github.com/jpush/aurora-imui/blob/master/ReactNative/README_zh.md#ios

**Comment by contineu0818** [comment]
@huangminlinux 还是不行，现在又卡在启动屏，然后报
dyld: Library not loaded: .framework/RCTAuroraIMUI
Referenced from: /var/containers/Bundle/Application/DDDE214C-5255-4D69-8AD1-F5F80D59A4FF/TestRNIMUI.app/TestRNIMUI
Reason: no suitable image found. Did find:
/private/var/containers/Bundle/Application/DDDE214C-5255-4D69-8AD1-F5F80D59A4FF/TestRNIMUI.app/Frameworks/RCTAuroraIMUI.framework/RCTAuroraIMUI: code signing blocked mmap() of '/private/var/containers/Bundle/Application/DDDE214C-5255-4D69-8AD1-F5F80D59A4FF/TestRNIMUI.app/Frameworks/RCTAuroraIMUI.framework/RCTAuroraIMUI'

**Comment by huangminlinux** [comment]
https://github.com/jpush/aurora-imui/issues/198#issuecomment-354084705 这个你加了？

**Comment by contineu0818** [comment]
@huangminlinux  配置我加了的，虚拟机都是可以正常运行的

**Comment by huangminlinux** [comment]
这边没有遇到这个问题，应该是本地环境的问题， 试试这个https://stackoverflow.com/questions/32730312/reason-no-suitable-image-found
