### ISSUE TITLE
IOS不能下拉刷新！！！！

### ISSUE THREAD

**Issue by sofwu** [jpush/aurora-imui#200]
IOS不能下拉刷新！！！！

**Comment by huangminlinux** [comment]
MessageList 的 isAllowPullToRefresh 属性有没设为 true？

**Comment by sofwu** [comment]
我的是RN文档上没看到这个属性

**Comment by huangminlinux** [comment]
👌 已更新文档。

**Comment by sofwu** [comment]
@huangminlinux 视频点全屏，只是大了一点，而且下面那3个按钮都不见了这个问题解决了吗，安卓的

**Comment by KenChoi1992** [comment]
@sofwu 下个版本返回的路径加上后缀，JMessage SDK 分开了文件名和格式。你也可以自己加上

**Comment by huangminlinux** [comment]
JMessage 的问题 可以到对应 jmessage 插件上提提 issue. 先关闭这个 issue.
