### ISSUE TITLE
其他的功能暂时不用可以屏蔽么

### ISSUE THREAD

**Issue by tianweicc** [jpush/aurora-imui#202]
录音  表情包的 布局  可以屏蔽么  最下面的一栏

**Comment by huangminlinux** [comment]
暂时没有这个配置项，messageList 和 输入组件可以分开使用，如果输入组件无法满足要求可以自己实现。

**Comment by KenChoi1992** [comment]
@tianweicc Android 这边可以屏蔽的，在 switchToXXX 方法中返回为 false 就可以隐藏。

**Comment by HHuiHao** [comment]
@KenChoi1992 这样?  不行.
`switchCameraMode={false}`
