### ISSUE TITLE
react-native run-android错误报错

### ISSUE THREAD

**Issue by FCMore** [jpush/aurora-imui#207]
### My environment:

 Could not resolve all dependencies for configuration ':aurora-imui-react-native:_debugPublishCopy'.
   > Could not find com.github.w446108264:XhsEmoticonsKeyboard:2.0.4.
     Required by:
         Awe:aurora-imui-react-native:unspecified
         Awe:aurora-imui-react-native:unspecified > cn.jiguang.imui:chatinput:0.5.6
   > Could not find com.github.w446108264:AndroidEmoji:1.0.0.
     Required by:
         Awe:aurora-imui-react-native:unspecified
         Awe:aurora-imui-react-native:unspecified > cn.jiguang.imui:chatinput:0.5.6
请问这是什么原因，为什么AndroidEmoji，XhsEmoticonsKeyboard这两个依赖包会找到不到

@jpush

**Comment by KenChoi1992** [comment]
@FCMore chatinput 新版本 0.6.2 已修复

**Comment by hellowupeng** [comment]
@KenChoi1992 npm 上最新的是0.6.0? 不是0.6.6?
