### ISSUE TITLE
添加了 aurora-imui 可以编译并运行，但是 command + D 和 command + R 无效

### ISSUE THREAD

**Issue by zuijiaoluo** [jpush/aurora-imui#209]
My environment: macOs 
运行环境  iPhone 6 虚拟机
- `react-native` version: 0.50.3
- `aurora-imui-react-native` version: 0.5.14

**Comment by zuijiaoluo** [comment]
移除了 aurora-imui command + D 和 command + R 可以使用

**Comment by huangminlinux** [comment]
报什么吗？

**Comment by huangminlinux** [comment]
和 #172  是相同的问题，想关闭这个 issue
