### ISSUE TITLE
返回的图片地址 视频地址

### ISSUE THREAD

**Issue by tianweicc** [jpush/aurora-imui#211]
地址不能换成文件的返回么

**Comment by tianweicc** [comment]
图片地址是不完整的

**Comment by KenChoi1992** [comment]
@tianweicc 你说的是 JMessage？

**Comment by tianweicc** [comment]
/Users/wtian/Library/Developer/CoreSimulator/Devices/733D099F-994E-4245-BBAC-9F9C799A41AC/data/Containers/Data/Application/E1D19BAF-4D7A-44A9-A8B4-71B2E817999A/Documents/17612181312_117551751/17612181312_single_ba6b2c354b6478d031952330/receivePath/image/49974-07-01/thumb/FE44845A86F5FAC102CE324B027D9989.jpg

/Users/wtian/Library/Developer/CoreSimulator/Devices/733D099F-994E-4245-BBAC-9F9C799A41AC/data/Containers/Data/Application/9CDE70C7-378D-49B1-9048-0EE9FE660374/Documents/17612181312_117551751/andy_single_ba6b2c354b6478d031952330/sendPath/image/49974-03-07/thumb/1AF9A8D1B1E8C16D91B9925F29158BBF

@KenChoi1992  上面的是jmessage返回的 是正确的  使用这个组件 自己发送的图片 获取的详情 是不完整的

**Comment by KenChoi1992** [comment]
@tianweicc 下个版本修复

**Comment by tianweicc** [comment]
@KenChoi1992 
![1](https://user-images.githubusercontent.com/17263719/34507874-41f04a02-f075-11e7-9c10-85bffd4bfab4.png)
0.6.6版本 还没有检测到 你没有发布么

**Comment by KenChoi1992** [comment]
@tianweicc 你直接安装 0.6.0 是可以的。
```
npm install aurora-imui-react-native@0.6.0 --save
```

**Comment by KenChoi1992** [comment]
@tianweicc 我测试是有返回文件扩展名的。
```
fileItem: {mediaType: video, mediaPath: /data/user/0/imui.jiguang.cn.imuirnexample/files/video/1514958265186.mp4}
```

**Comment by tianweicc** [comment]
@KenChoi1992  图片你测试也是正常的么

**Comment by KenChoi1992** [comment]
@tianweicc 也是正常的

**Comment by tianweicc** [comment]
@KenChoi1992  ok了 裁剪的时候 同事改错了  可以关闭这个问题了 谢谢

**Comment by KenChoi1992** [comment]
@tianweicc 更新了什么卡顿？
