### ISSUE TITLE
ios编译报错问题

### ISSUE THREAD

**Issue by 594904020** [jpush/aurora-imui#216]
### My environment:

根据文档安装后，也zhi执行了react-native link，成功后，按如下图配置了，结果在编译运行是报错
![image](https://user-images.githubusercontent.com/32348909/34493427-cf7b607c-f026-11e7-8875-84a38506f02f.png)

报错:
![image](https://user-images.githubusercontent.com/32348909/34493366-87e40fe8-f026-11e7-8117-375d19b52832.png)

**Comment by huangminlinux** [comment]
升级 xcode 到最新版本。
