### ISSUE TITLE
sample问题

### ISSUE THREAD

**Issue by misakichan** [jpush/aurora-imui#218]
### My environment:

sample运行，点击发送后文本后，输入框消失
点击发送录音后，再次点击语音按钮，弹出的不是录音按钮，是键盘。

**Comment by KenChoi1992** [comment]
@misakichan 你是不是用模拟器测试的？

**Comment by misakichan** [comment]
不是模拟器
荣耀V10
安卓8.0
emui8.0

**Comment by KenChoi1992** [comment]
@misakichan 昨天也有人说华为有问题，我用华为手机测一下。

**Comment by KenChoi1992** [comment]
@misakichan 我用的是华为 GRA-TL00 Android 6.0 emui 4.0.2 没有问题

**Comment by misakichan** [comment]
@KenChoi1992 好吧。感谢您的尝试。不得不说这几家IMpass,就你们家rn的sdk和文档最好

**Comment by KenChoi1992** [comment]
@misakichan 你试试别的机型看看有没有问题。
