### ISSUE TITLE
设置MessageType的问题。

### ISSUE THREAD

**Issue by MaChunsion** [jpush/aurora-imui#220]
### My environment:

> 在用 "IMessage.MessageType.SEND_TEXT.ordinal()" 设置 "MessageType" 的时候出现如下错误“java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Enum.ordinal()' on a null object reference“。但是用 "IMessage.MessageType.RECEIVE_TEXT.ordinal()" 设置 "MessageType" 的时候就不会错。

**Comment by KenChoi1992** [comment]
@MaChunsion 你重新编译一下试试。
