### ISSUE TITLE
AndroidStudio 加载项目(Simple)报错了！

### ISSUE THREAD

**Issue by DevXue** [jpush/aurora-imui#222]
### My environment:
刚才把demo下载下来，导入AndroidStudio发现总是报这个错
![qwe](https://user-images.githubusercontent.com/9455329/34708807-7375f106-f54f-11e7-8924-0a16f0f2eba9.png)
Error:One of setGitDir or setWorkTree must be called.

百度了白天找不到，用Google搜出来说是和Git有关系  说是要通过URL克隆下来才可以，我也不清楚咋回事···求解

这是Google搜出来的结果
![ssasasas](https://user-images.githubusercontent.com/9455329/34708877-c6e5ee04-f54f-11e7-9d06-9f6f50653c44.png)

**Comment by KenChoi1992** [comment]
@DevXue 你把整个项目 clone 下来

**Comment by DevXue** [comment]
@KenChoi1992   找到原因了，我就是把这个工程克隆下载下来的，  我在issues里头发现的 #30

**Comment by KenChoi1992** [comment]
@DevXue 👌，关闭这个 issue 了。
