### ISSUE TITLE
聊天页面卡顿很严重啊

### ISSUE THREAD

**Issue by ZCforiOS** [jpush/aurora-imui#225]

**Comment by huangminlinux** [comment]
不要在 消息列表插入原图， 要自行做裁剪动作。

**Comment by KenChoi1992** [comment]
@ZCforiOS Android 还是 iOS？

**Comment by ZCforiOS** [comment]
@KenChoi1992 RN版本的iOS端的图片只支持本地图片我改了库加载网络图片，导致滑动变慢

**Comment by huangminlinux** [comment]
@ZCforiOS  自行该的话需要注意 contentview 里面的内容不要有太多的计算，如果是图片的话很可能是图片过大导致的，应该要在聊天列表中显示图片的缩略图 而不是原图。
