### ISSUE TITLE
发现个问题，切换到前置相机不能拍摄了！多点几次OOM了

### ISSUE THREAD

**Issue by DevXue** [jpush/aurora-imui#229]
### Android
最新的代码，下载下来跑起来 发现切换到前置相机不能拍摄，怎么点都没有反应(用小米Note测试的，Android6.0 ，MUI8， 另外一台Android4.4的YouTaPhone没有问题)，后台log打印报错的截图如下
![7895464321](https://user-images.githubusercontent.com/9455329/34819141-ebdfd608-f6f7-11e7-8c1c-6e3c4781575d.png)
还有OOM的问题，就是当我点击切换前置相机  点击拍没反应  多点几次 就出现了OOM了
![oom](https://user-images.githubusercontent.com/9455329/34819317-5b3b40c8-f6f8-11e7-993a-b22442dba14f.png)

**Comment by KenChoi1992** [comment]
@DevXue 有的手机前置摄像头不支持自动对焦，下个版本改一下对焦策略。

**Comment by DevXue** [comment]
@KenChoi1992   谢谢， OOM的问题也是对焦引起的吗？

**Comment by KenChoi1992** [comment]
@DevXue 是因为没有对焦，然后你一直点，那个 precapture 队列就一直增长，直到 OOM。

**Comment by DevXue** [comment]
@KenChoi1992   哥们，前置摄像头还是不能拍摄啊···    我看到更新的代码只更新了布局文件，我也把布局文件的代码下载下来覆盖到我的代码中了  可是还是不能拍摄  选择前置。。。
