### ISSUE TITLE
从服务端获取的音频地址，播放不了，不支持在线播放音频吗？

### ISSUE THREAD

**Issue by DevXue** [jpush/aurora-imui#234]
### Android

聊天记录都保存在了服务端， 现在获取到聊天记录后，当我播放服务端的音频就没有反应了···  报了个错
![fff](https://user-images.githubusercontent.com/9455329/34865572-3b3476d4-f7b4-11e7-98b8-633e8be6e0be.png)

**Comment by KenChoi1992** [comment]
@DevXue 没有在线播放的功能，你要下载下来。
