### ISSUE TITLE
message.status update problem

### ISSUE THREAD

**Issue by yuandapeng** [jpush/aurora-imui#241]
Sending message initialization message.status='send_going'is added to MessageListView through appendMessage. Socket.io returns to update message.status='send_successed'. It is necessary to pull the scroll bar to the bottom to refresh the state successfully.

**Comment by huangminlinux** [comment]
android or iOS ？

**Comment by yuandapeng** [comment]
android

**Comment by yuandapeng** [comment]
i make it to the bottom by AuroraIController.scrollToBottom(true) ,the propblem has been solved
