### ISSUE TITLE
appendMessages错误

### ISSUE THREAD

**Issue by yuandapeng** [jpush/aurora-imui#242]
![image](https://user-images.githubusercontent.com/11659997/35078689-5f2dd9b6-fc3e-11e7-8a53-fddde05df292.png)
![image](https://user-images.githubusercontent.com/11659997/35078728-887d4054-fc3e-11e7-9727-a213e3728392.png)
代码如上，出现一下错误

TypeError: expected dynamic type `string', but had type `int64'
getString
    ReadableNativeMap.java
configMessage
    AuroraIMUIModule.java:154
appendMessages
    AuroraIMUIModule.java:86
invoke
    Method.java
invoke
    JavaMethodWrapper.java:374
invoke
    JavaModuleWrapper.java:162
run
    NativeRunnable.java
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:148
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:818

**Comment by KenChoi1992** [comment]
@yuandapeng  userId 为 string

**Comment by yuandapeng** [comment]
thanks
