### ISSUE TITLE
InputView  will  be hidden

### ISSUE THREAD

**Issue by yuandapeng** [jpush/aurora-imui#245]
When the expression is chosen, InputView will be hidden

**Comment by huangminlinux** [comment]
What do you mean by expression? messageList?

**Comment by yuandapeng** [comment]
when select emotion

**Comment by huangminlinux** [comment]
android or iOS?

**Comment by KenChoi1992** [comment]
@yuandapeng 这个问题是因为，你进入聊天页面后，没有第一时间设置软键盘高度导致的。这样，我检查一下有没有设置，如果没有就用一个默认的值好了。
