### ISSUE TITLE
sendBubble和receiveBubble的类型不明确，会导致ios8.0的APP闪退

### ISSUE THREAD

**Issue by andylidong** [jpush/aurora-imui#250]
![image](https://user-images.githubusercontent.com/18454971/35369169-bac3f994-01c1-11e8-945e-b72f2bbf9559.png)
APP的iOS9.0以上运行是没有问题的，在以下则会产生问题，导致APP都闪退，主要是由于在
https://github.com/jpush/aurora-imui/blob/0.6.1/ReactNative/messagelist.ios.js
中的定义propTypes时候产生的，会导致js读取问题？sendBubble和receiveBubble的类型不明确

**Comment by huangminlinux** [comment]
感谢提醒，可以升级到 + aurora-imui-react-native@0.7.1。
