### ISSUE TITLE
输入组件能够自定义图标吗？

### ISSUE THREAD

**Issue by YeomanYe** [jpush/aurora-imui#255]

**Comment by huangminlinux** [comment]
react-native 版没有提供这个配置项。

**Comment by YeomanYe** [comment]
@huangminlinux 那应该可以通过改变android和ios原生模块中的代码来改变吧，应该在哪里改变呢？

**Comment by KenChoi1992** [comment]
@YeomanYe Android 的话可以通过 ChatInput.getXXBtn.setImageDrawable() 设置，参考 https://github.com/jpush/aurora-imui-examples/blob/master/Themes-example/Android/app/src/main/java/cn/jiguang/imuisample/themes/ThemeFragment.kt

**Comment by YeomanYe** [comment]
@KenChoi1992 好的，谢谢
