### ISSUE TITLE
plugin with id 'com.android.library' not found 

### ISSUE THREAD

**Issue by YeomanYe** [jpush/aurora-imui#256]
我用React Native打开源码ReactNative目录中的android报plugin with id 'com.android.library' not found 怎么解决？

**Comment by KenChoi1992** [comment]
@YeomanYe 你要运行 demo 的话用 Android Studio 打开 React Native/sample/android 目录。

**Comment by YeomanYe** [comment]
@KenChoi1992 我是想改变组件原来的图标，所以才查看组件android和ios模块
