### ISSUE TITLE
react-native ios下拉刷新问题

### ISSUE THREAD

**Issue by YeomanYe** [jpush/aurora-imui#257]
### My environment:
react-native:0.50.3
aurora-imui-react-native:0.7.1

ios下拉刷新不能触发，如果使用了输入组件会触发组件的sizechange回调函数

**Comment by YeomanYe** [comment]
@huangminlinux 设置了的

**Comment by huangminlinux** [comment]
最新版本应该没这个问，可以试试最新版本。先关闭这个issue 有问题可以重新打开
