### ISSUE TITLE
版本升级到0.7.0后，Android和ios语音都不能播，ios头像不显示

### ISSUE THREAD

**Issue by lfh22** [jpush/aurora-imui#260]
### My environment:
查了代码，是因为播放的时候先把资源释放了，播的时候就报错了，难道没有人遇到吗？

**Comment by KenChoi1992** [comment]
可以播放啊

**Comment by huangminlinux** [comment]
头像问题确保头像路径文件存在。新版本对默认头像处理有所改动，可以参考 demo 的用法。

**Comment by lfh22** [comment]
ios头像不显示是因为地址是网络地址
