### ISSUE TITLE
下拉刷新android

### ISSUE THREAD

**Issue by z5614036** [jpush/aurora-imui#266]
下拉刷新安卓我自己融入了原生的Ptr，想取消 messageList的小菊花，但是我去除messageList的onPullToRefresh属性后 还能触发 那个小菊花。是bug吗？

**Comment by z5614036** [comment]
还有一个很严重的问题，你们的下拉加载会导致头部数据不能立刻加载出来，必须手动先滑动那个messageList，然后才能加载出来。 估计是你们的messageList封装了某种lock状态，当滑动到头部会lock住，无法再主动加载更多了

**Comment by KenChoi1992** [comment]
@z5614036 RN 这边 MessageList 使用了 [Ultra-Pull-to-Refresh](https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh) 你可以替换头部。

**Comment by z5614036** [comment]
<MessageListView
                style={{flex: 1}}
                onMsgClick={this.onMessagePress.bind(this)}
                onLinkClick={this.onOpenURL.bind(this)}
                onAvatarClick={this.onAvatarPress.bind(this)}
                onStatusViewClick={this.onStatusViewClick.bind(this)}
                onTouchMsgList={this.onTouchMsgList}
                onClickChangeAutoScroll={this.onClickChangeAutoScroll}
                onPullToRefresh={this._loadMoreContentAsync}
                sendBubble={{imageName: "send_msg", padding: 10}}
                receiveBubbleTextColor={'#ffffff'}
                sendBubbleTextSize={14}
                receiveBubbleTextSize={14}
                sendBubblePressedColor={'#dddddd'}
                eventMsgTxtColor={'#ffffff'}
                eventMsgTxtSize={12}
                initList={this.state.initList}
            />

这是demo里面的！  能给我看看如何用 自带Ultra-Pull-to-Refresh吗？

**Comment by KenChoi1992** [comment]
@z5614036 你要看 ReactMsgListManager 这个类，把 PtrDefaultHeader 换成 [Ultra-Pull-to-Refresh](https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh) 里的其他 Header 就行了。
