### ISSUE TITLE
RN 列表宽度有问题

### ISSUE THREAD

**Issue by musicode** [jpush/aurora-imui#268]
页面导航有动画，我怀疑可能是动画过程中，计算宽度出了问题，比如 375px 宽度的手机，渲染第一条消息时，是按 750px 来算的，就导致 `timeString` 不在中间，而是在偏右的位置。

此问题经常出现，希望能尽快修复

如计算宽度实在麻烦，是否可提供宽度配置项，直接外面写死宽度就好

此外，图片压缩问题希望能在下一版加入，再次感谢

**Comment by musicode** [comment]
上个版本已经隔了20多天，希望 @huangminlinux  @KenChoi1992 两位大神有空一定记得发版本啊，我们等得可着急了...

**Comment by KenChoi1992** [comment]
@musicode Android 还是 iOS？
