### ISSUE TITLE
适配 iphoneX

### ISSUE THREAD

**Issue by musicode** [jpush/aurora-imui#271]
![image](https://user-images.githubusercontent.com/2732303/36641708-54457690-1a6f-11e8-9da5-3bf2ae1feca9.png)

**Comment by musicode** [comment]
拍照点击全屏后，取消全屏按钮在屏幕右上方，iphonex 屏幕会偏上，有点和状态栏重叠，很难点击，是否可以往下调一些

**Comment by iwangx** [comment]
貌似可以你自己在外层套一层设置一个paddingBottom就可以了
