### ISSUE TITLE
文字大小和行高

### ISSUE THREAD

**Issue by musicode** [jpush/aurora-imui#272]
对于消息气泡中的文字和输入框中的文字，是否可添加以下三项配置呢？

* textSize
* textColor
* textLineHeight

此外，输入框是否可配置 padding 呢

**Comment by KenChoi1992** [comment]
@musicode textLineHeight 没有这个属性

**Comment by musicode** [comment]
@KenChoi1992  android 有没有调整行间距的属性呢？

**Comment by KenChoi1992** [comment]
可以调整行间距

**Comment by musicode** [comment]
@KenChoi1992 因为前端的命名通常叫 lineHeight，所以暴露给 RN 的是否可以叫做 `textLineHeight` 呢？

**Comment by KenChoi1992** [comment]
@musicode 可以查看稍后发布的版本对应的 [API doc](https://github.com/jpush/aurora-imui/blob/master/ReactNative/docs/APIs.md)。

**Comment by musicode** [comment]
文本还涉及 `timeString`，现在已有三项配置：

* dateTextSize
* dateTextColor
* datePadding

是否可添加圆角和背景色配置项呢，这样就能实现微信的效果了。

**Comment by musicode** [comment]
刚又看到一个
```
eventMsgTxtColor: PropTypes.string,
eventMsgTxtPadding: PropTypes.number,
eventMsgTxtSize: PropTypes.number,
```

是否可以同样加 lineHeight 呢，因为会有换行的场景

**Comment by KenChoi1992** [comment]
已更新
