### ISSUE TITLE
android 气泡背景颜色有api可以修改吗

### ISSUE THREAD

**Issue by 617450941** [jpush/aurora-imui#277]
android 气泡背景颜色有api可以修改吗

**Comment by KenChoi1992** [comment]
@617450941 需要替换气泡背景图片。
![image](https://user-images.githubusercontent.com/8196928/36953594-f9dd5478-2056-11e8-9923-8ee51c6e6e94.png)

**Comment by 617450941** [comment]
怎么我放了一张改过颜色的九点图到drawable目录下 怎么气泡颜色没任何改变 是还需要哪里去设置吗

**Comment by KenChoi1992** [comment]
原生的话有 sendBubbleDrawable/ receiveBubbleDrawable 属性。RN 的话，只要设置 sendBubble/receiveBubble 为该点九图名字就行了。
