### ISSUE TITLE
andorid 的messagelist 0.6.1版本不设置时间 会出现空阴影

### ISSUE THREAD

**Issue by 617450941** [jpush/aurora-imui#282]
andorid 的messagelist 0.6.1版本 没有设置setTimeString这个方法的值时候 会出现空阴影 
![image](https://user-images.githubusercontent.com/7607957/37015420-f700dbb2-2141-11e8-8cb1-b655f969ea02.png)

**Comment by 617450941** [comment]
而且还有个问题 在循环里调用setTimeString这个方法加上if的条件判断后 添加的时间 在listview里显示会有几条时间顺序是乱的  
![image](https://user-images.githubusercontent.com/7607957/37016749-c59d3e74-2148-11e8-8029-72db54faade9.png)

**Comment by KenChoi1992** [comment]
@617450941 最终按照你的插入顺序来显示。

**Comment by 617450941** [comment]
@KenChoi1992  那messagelist 0.6.1 没有设置setTimeString这个方法的时候 出现空阴影是怎么回事

**Comment by KenChoi1992** [comment]
@617450941 下个版本修复

**Comment by KenChoi1992** [comment]
更新了 0.6.3
