### ISSUE TITLE
aurora-imui-react-native更新至0.9.1报错

### ISSUE THREAD

**Issue by lfh22** [jpush/aurora-imui#285]
`react-native` version:0.48.1
![image](https://user-images.githubusercontent.com/33644616/37023535-35e774e8-2161-11e8-9051-8e001a35f80e.png)
![image](https://user-images.githubusercontent.com/33644616/37023730-c68fe21e-2161-11e8-9855-1bbf2e5389ff.png)

**Comment by lfh22** [comment]
使用updateMessage更新时，跳到了会话列表底部，此时并没有调用scrollToBottom方法

**Comment by KenChoi1992** [comment]
@lfh22 新版本已修复。
