### ISSUE TITLE
android glide升级到4.6.1 选择图片闪退

### ISSUE THREAD

**Issue by 617450941** [jpush/aurora-imui#286]
错误信息
java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.example.a61745-1/base.apk)

**Comment by 617450941** [comment]
PhotoAdapter.java 第82行的glide调用方式 在新版本glide已经失效

**Comment by KenChoi1992** [comment]
已修复。

**Comment by renshaodong** [comment]
没修复
