### ISSUE TITLE
Android版，消息列表不能显示图片

### ISSUE THREAD

**Issue by HelloWym** [jpush/aurora-imui#292]
你好，我想问一下，以下是发送图片的代码，为什么在本地消息列表显示不出图片？
 message = new MyMessage(null, IMessage.MessageType.SEND_IMAGE.ordinal());
 message.setMediaFilePath(item.getFilePath());
 message.setTimeString(new SimpleDateFormat("HH:mm", Locale.getDefault()).format(new Date()));
 message.setUserInfo(new DefaultUser("1", Params.userName,sendurl));
 final MyMessage fMsg = message;
 ChartActivity.this.runOnUiThread(new Runnable() {
                                                 @Override
                                                  public void run() {
                                                     mAdapter.addToStart(fMsg, true);
                                                 }
                                               });

**Comment by KenChoi1992** [comment]
@HelloWym 你有没有实现 ImageLoader ？

**Comment by KenChoi1992** [comment]
@HelloWym 没有回复就先关闭了。
