### ISSUE TITLE
推送数据模型中的pushMap作用是什么，必须设置吗？

### ISSUE THREAD

**Issue by Danawill** [jpush/aurora-imui#294]
public class JPushData {
	
	private String type; //推送类型
	private String title;  //推送标题
	private String content;  //推荐内容
	private Map<String, Object> pushMap; //业务数据
	private List<String> alias; //推送别名，一个设备对应一个token，极光服务器通过这个别名寻找需要推送的真正设备

**Comment by KenChoi1992** [comment]
@Danawill 你是不是搞错项目了，我们这没有 pushMap

**Comment by Danawill** [comment]
失误，我是在找极光推送
