### ISSUE TITLE
问题同61楼，需要手动滑动一下键盘才能刷新信息，更新库至0.6.1依然无效

### ISSUE THREAD

**Issue by Youngjim77** [jpush/aurora-imui#297]

**Comment by KenChoi1992** [comment]
更新至最新版本。 npm view aurora-imui-react-native 查看最新版本。

**Comment by Youngjim77** [comment]
messagelist: 0.6.1 
chatinput:0.6.3
如果将版本再往上升就出现
![image](https://user-images.githubusercontent.com/26914864/37509517-9dabaf58-2932-11e8-8cf5-bc8729f0b909.png)
请问这是什么原因呢？

**Comment by KenChoi1992** [comment]
升级后，clean，rebuild 即可。
