### ISSUE TITLE
发送消息时闪退

### ISSUE THREAD

**Issue by nextdooroldwang** [jpush/aurora-imui#298]
![1 427dd2qos1 a8qwi0rz54](https://user-images.githubusercontent.com/18671240/37318168-f4cba9d2-26a3-11e8-87c3-77da9ca72318.png)

![k0o z83z50eq l upyec](https://user-images.githubusercontent.com/18671240/37318172-fc38323a-26a3-11e8-9da9-6b6442a7bae9.jpg)

**componentDidMount触发还不会闪退，放在监听事件里触发就会闪退**

**版本改成25.3.1还是一样的闪退**
"aurora-imui-react-native": "^0.8.4",
"react-native": "0.53.0",

**Comment by KenChoi1992** [comment]
在你的 build.gradle 做如下修改：
```
compile (project(':aurora-imui-react-native')) {
        exclude group: 'com.android.support'
    }
implementation 'com.android.support:appcompat-v7:25.4.0'
    implementation 'com.android.support:design:25.4.0'
    implementation 'com.android.support:support-v4:25.4.0'
    implementation 'com.android.support:recyclerview-v7:25.4.0'
```
上面演示的是 25.4.0，实际跟你的 compileSdkVersion 版本相匹配。

**Comment by nextdooroldwang** [comment]
谢谢，好使了
