### ISSUE TITLE
android小屏幕手机 输入框有点问题

### ISSUE THREAD

**Issue by 617450941** [jpush/aurora-imui#299]
点击表情弹出的面板快把屏幕都占满了

**Comment by 617450941** [comment]
![image](https://user-images.githubusercontent.com/7607957/37335305-1cf41986-26e9-11e8-9058-87ab4bfca370.png)

**Comment by KenChoi1992** [comment]
@617450941 进入聊天界面之前首先通过 setMenuContainerHeight 设置一下默认的菜单栏高度。

**Comment by KenChoi1992** [comment]
@617450941 新版这块可以适配键盘高度了，你可以试试在小屏幕手机上设置一个较小的初始高度。

**Comment by zhuAria** [comment]
@KenChoi1992 新版指的是 cn.jiguang.imui:chatinput:0.11.0 这个吗？
