### ISSUE TITLE
安卓的DEMO 直接就跑不起来

### ISSUE THREAD

**Issue by happynewplay** [jpush/aurora-imui#30]

**Comment by lhw5123** [comment]
有详细的错误日志吗？

**Comment by yuekong** [comment]
Error:One of setGitDir or setWorkTree must be called.

**Comment by tao0111225** [comment]
Error:One of setGitDir or setWorkTree must be called.     也遇到了

**Comment by lhw5123** [comment]
试下在菜单中： VCS -> Enable Version control -> Git

**Comment by gazerhuang** [comment]
不用Git的把build.gradle里面第2行apply from、第18行productFlavors {}删了就好了 @happynewplay @yuekong @tao0111225
