### ISSUE TITLE
hotkey(Command+r)  invalid when Embedded Binaries add RCTAuroraIMUI.framework

### ISSUE THREAD

**Issue by xc19** [jpush/aurora-imui#303]
### My environment:
- `react-native` version: 0.54
- `aurora-imui-react-native` version: 0.9.9

React-native has hotkey Command+r can refresh the iOS simulator.
But when i use "react-native link" and add RCTAuroraIMUI.framework to Embedded Binaries,
Command+r will invalid.
I try minus RCTAuroraIMUI.framework in Embedded Binaries,Command+r can back to normal.
I try aurora-imui-react-native version 0.71 still have the same problem.

Same problem: 
[https://github.com/jpush/aurora-imui/issues/209](https://github.com/jpush/aurora-imui/issues/209) 
[https://github.com/jpush/aurora-imui/issues/172](https://github.com/jpush/aurora-imui/issues/172)
But it look like is not solved.

**Comment by huangminlinux** [comment]
这边 Command + r 可以正常 reload 应用， 你那边编译选项是否选择了 release ？

**Comment by xc19** [comment]
no, it is debug.

I try minus RCTAuroraIMUI.framework in Embedded Binaries,Command+r can back to normal.

you can try to use react-native 0.54 init new project. you may have same problem.

**Comment by huangminlinux** [comment]
新建  0.54.2 项目没有问题

**Comment by xc19** [comment]
I just retested.  
Aurora-imui-react-native is already fixed this issue with 0.9.20.
The problem I encountered before was to use Aurora-imui-react-native with 0.9.9.  
Thx.
