### ISSUE TITLE
android chatinput更新到0.6.9点击选择图片报错

### ISSUE THREAD

**Issue by 617450941** [jpush/aurora-imui#308]
android chatinput更新到0.6.9点击选择图片报错

java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.example.a61745-E-X-fwa1gaQcF94dzJT1tQ==/base.apk)

**Comment by 617450941** [comment]
![image](https://user-images.githubusercontent.com/7607957/37692293-9e6caece-2cf2-11e8-949d-e75bf2b76ded.png)

**Comment by KenChoi1992** [comment]
@617450941 因为 ChatInput 使用了 Glide 3.8.0，你用的 Glide 是 v4 以上的，这里出现了冲突。解决方法就是 exclude ChatInput 的 Glide。

**Comment by 617450941** [comment]
怎么exclude 小白...

**Comment by 617450941** [comment]
compile ('cn.jiguang.imui:chatinput:0.7.3') {
        exclude group: 'com.github.bumptech.glide', module: 'glide'
    }

exclude 后还是报java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.example.a61745-CcNZ_G_pvDgk-hflj-R8Kw==/base.apk)

**Comment by KenChoi1992** [comment]
@617450941 你更新一下，现在应该修复了。
