### ISSUE TITLE
如何发送项目中安卓目录里的图片和视频文件？

### ISSUE THREAD

**Issue by nextdooroldwang** [jpush/aurora-imui#316]

**Comment by KenChoi1992** [comment]
@nextdooroldwang 你要发送手机 sd 卡里的文件还是打包到 apk 里的文件？可以看一下网上的资料啊。

**Comment by nextdooroldwang** [comment]
@KenChoi1992 发送打包到APK里的图片。应该怎么发送？我用Image标签能显示出来，但是同样的路径放在message里就不行

**Comment by KenChoi1992** [comment]
如果放在 drawable 下，直接传 R.drawable.图片名 就行了，如果是加载视频，放在 assets 下，传 file:///android_asset/图片名 ，视频也是一样的。

**Comment by nextdooroldwang** [comment]
@KenChoi1992 react-native项目
