### ISSUE TITLE
command + D 打不开调试菜单，unlink后可以。

### ISSUE THREAD

**Issue by jiasongs** [jpush/aurora-imui#317]
### My environment:
- `react-native` version:  0.53.3
- `aurora-imui-react-native` version:   0.9.30
- `native version` ： iOS11.2 xcode9.2 模拟器

command + D 打不开调试菜单，摇一摇可以。提供的Demo也是如此。删除aurora-imui-react-native，unlink之后就可以了。

**Comment by huangminlinux** [comment]
#303 看看是不是同一个问题。

**Comment by jiasongs** [comment]
看过[#303](https://github.com/jpush/aurora-imui/issues/303)，应该不是这个问题。使用iPhone8模拟器不行，但是使用其他的模拟器（iPhone7）没问题。我删除iPhone8模拟器后，重新添加模拟器就好了。怪事。。。

**Comment by huangminlinux** [comment]
应该是 RN 的 bug。
