### ISSUE TITLE
CocoaPods仓库需要更新。

### ISSUE THREAD

**Issue by ishell** [jpush/aurora-imui#32]
目前`pod install`版本还是0.1.0，我看到0.1.1的release log里面iOS也有更新，能不能在CocoaPods上面更新下？貌似需要提交个podspec.json到https://github.com/CocoaPods/Specs 就可以了。

**Comment by huangminlinux** [comment]
这周会出个版本，状态更新，到时候会一起更新到 cocoapods 上，

现在不需要提交 spec 上了，那边已经不维护 PR 了， 要用 pod trunk

**Comment by ishell** [comment]
Thx.
