### ISSUE TITLE
react-native可以提供消息列表点击视频接口吗？点击视频消息的时候onMsgClick没有用呀

### ISSUE THREAD

**Issue by lfh22** [jpush/aurora-imui#321]

**Comment by huangminlinux** [comment]
android 还是 iOS ？

**Comment by lfh22** [comment]
@huangminlinux 可以两边都提供吗？我们项目ios和Android两边都在使用消息列表，如果你这边没办法实现，把视频点击，视频自定义样式等视频相关接口开放给我们，还有现在最新的版本使用Android SDK27.1.0，我的这边下载不到无法使用有些悲伤

**Comment by KenChoi1992** [comment]
@lfh22  你可以在 app 的 build.gradle 中这样写：
```
compile (project(':aurora-imui-react-native')) {
        exclude group: 'com.android.support'
    }
```

**Comment by KenChoi1992** [comment]
点击视频消息也会回调 onMsgClick 方法。你需要自己判断一下消息类型，然后做相应处理。

**Comment by lfh22** [comment]
@KenChoi1992 我这边点击视频消息没有触发onMsgClick方法 版本RN0.9.1

**Comment by lfh22** [comment]
依然是Error:Could not find method implementation() for arguments [com.android.support:appcompat-v7:27.1.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Please install the Android Support Repository from the Android SDK Manager.
<a href="openAndroidSdkManager">Open Android SDK Manager</a>

**Comment by KenChoi1992** [comment]
你没有安装 Android Support 包吗？另外升级下 Gradle 插件到 3.0 以上以支持 implementation。
