### ISSUE TITLE
关于AuroraIMUIController.addMessageListDidLoadListener()无法remove问题

### ISSUE THREAD

**Issue by jasonyuantmc** [jpush/aurora-imui#327]
1.跟着sample去写发现监听方法AuroraIMUIController.addMessageListDidLoadListener()在componentDidMount() 调用之后，需要在 componentWillUnmount()去执行AuroraIMUIController.addMessageListDidLoadListener()注销监听

2.写好了之后发现以下注销监听方法并没有好好的在componentWillUnmount()执行,最后查到在/aurora-imui-react-native/index.js里面这两个方法是根据传值来判断注销哪个监听,但是两个方法传入的对象均为{Function}cb，这样的话在sample里面的 AuroraIMUIController.addMessageListDidLoadListener(() => {
            this.getHistoryMessage();
        });
会已一个function作为keyword来注册监听，所以AuroraIMUIController.removeMessageListDidLoadListener();
是不可能注销掉监听的。

3.所以建议在/aurora-imui-react-native/index.js的监听方法里加上String:keyword，例如
	/**
	 * add listener: messageList did Loaded will call cb
	 * @param {Function} cb 
	 * @param {String} name
	 */
	static addMessageListDidLoadListener(name,cb) {
		listeners[name] = DeviceEventEmitter.addListener(IMUIMessageListDidLoad,
			() => {
				cb();
			});
	}

	/**
	 * remove listener:
	 * @param {Function} cb 
	 * @param {String} name
	 */
	static removeMessageListDidLoadListener(name,cb) {
		if (!listeners[name]) {
			return;
		}
		
		listeners[name].remove();
		listeners[name] = null;
	}

4.之后在执行的时候
   componentDidMount() {

        AuroraIMUIController.addMessageListDidLoadListener(MessageListDidLoadEvent,() => {
            this.getHistoryMessage();
        });

    }

    componentWillUnmount() {
            
        AuroraIMUIController.removeMessageListDidLoadListener(MessageListDidLoadEvent,()=>{

        });
 
    }
这样就可以有正确删除监听。

**Comment by huangminlinux** [comment]
需要将 callback 存在一个变量中， addMessageListDidLoadListener 和 removeMessageListDidLoadListener 都传该变量。

**Comment by huangminlinux** [comment]
已更新
