### ISSUE TITLE
运行出错，如何解决？

### ISSUE THREAD

**Issue by BruceWan** [jpush/aurora-imui#330]
Error: `MessageList` has no propType for native prop `RCTMessageList.displayNamePadding` of native type `Map`
If you haven't changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.

This error is located at:
    in RCTMessageList (at messagelist.android.js:80)

**Comment by KenChoi1992** [comment]
@BruceWan 更新 aurora-imui-react-native 后，clean，rebuild（或者手动删除 node_modules/aurora-imui-react-native/android/build 文件夹）。

**Comment by HHuiHao** [comment]
```
先删除:
react-native unlinka-imui-react-native
npm uninstall aurora-imui-react-native
然后再安装:
npm install aurora-imui-react-native --save
react-native link aurora-imui-react-native
```
