### ISSUE TITLE
时间显示bug！！！

### ISSUE THREAD

**Issue by nextdooroldwang** [jpush/aurora-imui#331]
### My environment:

"aurora-imui-react-native": "^0.9.32",
"react-native": "0.53.0",

 android  

当多条数据（测试出大概多余15条）时，如果有的数据timeString有值有的数据timeString为空的话，就会出现时间显示跟数据设置的不符。如图：
![image](https://user-images.githubusercontent.com/18671240/38478026-b6d3e55e-3be8-11e8-9a11-83f4f5c329f3.png)

而实际我的数据是：

let msg = {
            fromUser: fromUser,
            msgId: 'aa',
            status: 'send_succeed',
            msgType: "text",
            isOutgoing: false,
            text: 'aaaaa',
            timeString:'2018-4-4 10:10:10'
        }
        let msg1 = {
            fromUser: fromUser,
            msgId: 'aa',
            status: 'send_succeed',
            msgType: "text",
            isOutgoing: false,
            text: 'aaaaa',
            timeString: null
        }
        let dataArr = [];
        dataArr[0] = msg;
        dataArr[1] = msg1;
        dataArr[2] = msg;
        dataArr[3] = msg1;
        dataArr[4] = msg;
        dataArr[5] = msg1;
        dataArr[6] = msg;
        dataArr[7] = msg1;
        dataArr[8] = msg;
        dataArr[9] = msg1;
        dataArr[10] = msg;
        dataArr[11] = msg1;
        dataArr[12] = msg;
        dataArr[13] = msg1;
        dataArr[14] = msg;
        dataArr[15] = msg1;
        dataArr[16] = msg;
        dataArr[17] = msg1;
        dataArr[18] = msg;
        dataArr[19] = msg1;
        dataArr[20] = msg;
        dataArr[21] = msg1;
        dataArr[22] = msg;
        dataArr[23] = msg1;
        dataArr.map((item)=> {
            AuroraIMUIController.insertMessagesToTop([item]);
        })

**Comment by KenChoi1992** [comment]
@nextdooroldwang 发布了 0.9.36 解决了这个问题。

**Comment by 617450941** [comment]
android同样有这问题
