### ISSUE TITLE
RN编译报错，Could not find method implementation()

### ISSUE THREAD

**Issue by LukeChenyk** [jpush/aurora-imui#333]
react-native 
`react-native` version: 0.51.0
`aurora-imui-react-native` version:^0.9.35

///////////////////////////      build.gradle    ////////////////////////////////////////////////
 compileSdkVersion 26
 buildToolsVersion "26.0.2"

minSdkVersion 16
targetSdkVersion 26

dependencies {
     ...
    compile (project(':aurora-imui-react-native')) {
        exclude group: 'com.android.support'
    }
    compile 'com.android.support:appcompat-v7:26.0.2'
    compile 'com.android.support:design:26.0.2'
}
////////////////////////////////////////////////////////////////////

dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
}

////////////////////////////////////////////////////////////////////

报错如下：
* Where:    
Build file 'D:\workplace\RN\RnPro\node_modules\aurora-imui-react-native\ReactNative\android\build.gradle' line: 34                                                                                                                              
* What went wrong:                                                                                                      
A problem occurred evaluating project ':aurora-imui-react-native'.                                                      
Could not find method implementation() for arguments [com.android.support:appcompat-v7:27.1.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by KenChoi1992** [comment]
@LukeChenyk 要么升级 Gradle 插件到 3.0 以上，要么将所有的 implementation 改成 compile 。建议升级。

**Comment by LukeChenyk** [comment]
我把你们build.gradle 都改成了compile,如图
![image](https://user-images.githubusercontent.com/10167615/38545866-a705dcd6-3cdd-11e8-871e-56200a5be593.png)

报错如下：
![image](https://user-images.githubusercontent.com/10167615/38545920-c98df0a4-3cdd-11e8-8cc3-4b7dae800387.png)

是一定需要com.android.support:appcompat-v7:27.1.0 这包的吗

**Comment by LukeChenyk** [comment]
加了这仓库就编译通过了，问题解决了
allprojects {
    repositories {
        maven { url "https://maven.google.com" }
    }
}

**Comment by youngjuning** [comment]
加在哪里

**Comment by laienliang** [comment]
遇到同样的问题

**Comment by laienliang** [comment]
有人解决了么，按上面的方法都不行
