### ISSUE TITLE
iOS版本提示 Use of undeclared type 错误

### ISSUE THREAD

**Issue by ishell** [jpush/aurora-imui#34]
我是按照这个[教程](https://github.com/jpush/aurora-imui/blob/master/docs/iOS/usage_iOS_zh.md)来做的。
在StoryBoard里面添加了两个View，并分别把这两个View的class改为`IMUIMessageCollectionView`以及`IMUIInputView`，然后在 Controller里面连接好@IBOutlet后，出现`Use of undeclared type 'IMUIMessageCollectionView'`以及`Use of undeclared type 'IMUIInputView'`错误。
我搜索了一下貌似是命名错误，但是我用官方iOS目录下的IMUIChat却可以运行起来。请问这种情况是不是CocoaPods哪里没设置好吗？

**Comment by ishell** [comment]
Podfile:
`# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'HelloChat' do


  # Pods for HelloChat
  pod 'AuroraIMUI'
  
  target 'HelloChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HelloChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
`
Xcode版本 8.3.2（8E2002）
Pod 版本 1.2.1
Swift 版本 3.1

**Comment by huangminlinux** [comment]
有执行 import AuroraIMUI 吗？

**Comment by ishell** [comment]
添加 import AuroraIMUI 后好了。Thx。
