### ISSUE TITLE
ChatInput props: customLayoutItems 设置无效

### ISSUE THREAD

**Issue by shopshow** [jpush/aurora-imui#344]
### My environment:
- `react-native` version: 0.52.1
- `aurora-imui-react-native` version: 0.10.1

项目中不需要 发送语音，尝试配置 customLayoutItems 如下：
```
customLayoutItems={{
  left: [],
  right: ['send'],
  bottom: ['gallery','emoji','camera']
}} 
```
没有任何效果, 语音的图标，仍然还在

**Comment by huangminlinux** [comment]
这个配置只有 iOS 才提供
