### ISSUE TITLE
RN IOS端重新点击gallery按钮后，下方图片所占区域不会缩回去

### ISSUE THREAD

**Issue by magiclove** [jpush/aurora-imui#346]

**Comment by huangminlinux** [comment]
需要实现这个功能可以在 [onSwitchtoGalleryMode](https://github.com/jpush/aurora-imui/blob/master/ReactNative/docs/APIs_zh.md#onswitchtogallerymode) 回调中调用 [hidenFeatureView](https://github.com/jpush/aurora-imui/blob/master/ReactNative/docs/APIs_zh.md#hidenfeatureview) 方法

**Comment by magiclove** [comment]
react:16.0.0
react-native:0.51.0
