### ISSUE TITLE
消息数据的处理等

### ISSUE THREAD

**Issue by xushao1990** [jpush/aurora-imui#35]
项目介绍中描述中 Aurora IMUI 是个通用的即时通讯（IM）UI 库。
请问在消息数据处理方面你们是怎么考虑的，比如图片格式和尺寸、音视频的编码格式等。
这些方面会涉及到吗？就目前的项目来说对这方面的支持不太灵活。

另外，在接收消息后插入到聊天列表的时也是比较麻烦的。因为接收到消息数据时，像一些图片资源肯定没有下载到本地。比如：列表中图片的加载、视频首帧的加载、用户头像的加载，目前还仅能从沙盒中读取文件数据而不能通过图片异步加载库进行加载。
再比如，在IM聊天中视频文件的下载一般会在用户点击视频消息后才开始执行的，所以视频的第一帧图片肯定不能从本地视频文件中获取。

我看了目前的项目，感觉大部分功能的出发点为本地发送消息，而接收消息方面的数据处理是比较弱的。

我是iOS开发者。本项目已经给我带来了相当多的便利。感谢。

**Comment by huangminlinux** [comment]
目前来看项目还不能满足你的需求。

这几天会发一个版本， 新增接口：消息更新，可以用于替换消息，可以在点击消息的操作之后更新消息。

之后我们会出一套自定义消息的机制，你所说的这些数据和视图之间的关系逻辑可以放到这里去处理。
