### ISSUE TITLE
rn集成xcode运行不起来

### ISSUE THREAD

**Issue by iamgod588** [jpush/aurora-imui#355]
### My environment:

![029016e7-7b10-424b-a596-d33bb5d57c16](https://user-images.githubusercontent.com/18711312/39796162-73978f64-5387-11e8-9b46-95a657b10bde.png)

模拟器上不会报错，但是真机上运行就报这个，我这个是空白项目，也没有用其他东西
react-native` version: 0.55.4

**Comment by huangminlinux** [comment]
插件用的什么版本？

**Comment by iamgod588** [comment]
我下载了这个demo也是这样的，模拟器可以运行，真机就报错

**Comment by iamgod588** [comment]
@huangminlinux

**Comment by huangminlinux** [comment]
这边测试正常，  可以尝试如下操作。
将 RCTAuroraIMUI-> TARGETS -> RCTAuroraIMUITests -> General -> Team  改成自己的 team。
如果还是不行，可以将 RCTAuroraIMUI-> TARGETS -> RCTAuroraIMUITests 删除。

**Comment by iamgod588** [comment]
我用了自己的team，删除了RCTAuroraIMUITests，依然不行

**Comment by huangminlinux** [comment]
能提供详细错误提示吗？ 截图信息太少。
