### ISSUE TITLE
andorid和ios列表顺序相反

### ISSUE THREAD

**Issue by ferrysu** [jpush/aurora-imui#357]
### My environment:

`react-native` version: 0.55.3
`aurora-imui-react-native` version:0.10.1

在android和ios  上消息列表正好相反

而且安卓在刚打开几面用 insertMessagesToTop 插入多条数据后 不会到最底部, 而ios没有这个问题

**Comment by youngjuning** [comment]
+1

**Comment by xiaomansjw** [comment]
+1
