### ISSUE TITLE
打包的时候出现com.android.ide.common.process.ProcessException: Failed to execute aapt

### ISSUE THREAD

**Issue by 25juan** [jpush/aurora-imui#367]
按照教程，我配置了对应的项目，在Android 安装debug apk的时候没有问题，但是打包的时候就会出现下面的问题。
![image](https://user-images.githubusercontent.com/14308183/39984009-46149204-578c-11e8-9fe6-92780c503d8c.png)
我也在build.gradle 里面配置了 exclude gruop support
![image](https://user-images.githubusercontent.com/14308183/39984048-72b69cf8-578c-11e8-8119-e9f47f24a49b.png)
请问这个该怎么解决呢？

**Comment by lijunzz** [comment]
建议将 `compile ` 全部替换成 `implementation` 。

**Comment by 25juan** [comment]
替换之后还是打包失败
![image](https://user-images.githubusercontent.com/14308183/39984730-b0078a0c-578e-11e8-88f8-c49fc2bb823d.png)

**Comment by 25juan** [comment]
已经解决了，方案为：在android 目录下的gradle.properties 下添加下面的代码

android.enableAapt2=false
org.gradle.jvmargs=-Xmx2048M

![image](https://user-images.githubusercontent.com/14308183/39987588-c6ce6338-5797-11e8-9d96-6fcd0096aebc.png)
