### ISSUE TITLE
RCTMessageListView error

### ISSUE THREAD

**Issue by king804** [jpush/aurora-imui#370]
`react-native` version: 55.0.3
`aurora-imui-react-native` version: lastest

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/2D5A8D3E-5084-462B-99BA-DB8E2579463B/howsyourdate.app> (loaded)' with name 'RCTMessageListView''
*** First throw call stack:

模擬機沒有問題，真機測試時就出現這個錯，整個app都卡掉

**Comment by king804** [comment]
IOS 才有的問題

**Comment by huangminlinux** [comment]
这个配置项有添加吗？  
- 找到 PROJECT -> TARGETS -> General -> Embedded Binaries 然后添加 RCTAuroraIMUI.framework。

**Comment by king804** [comment]
<img src="https://i.imgur.com/ttqEnpz.png"></img>
有加啊

**Comment by king804** [comment]
<img src="https://i.imgur.com/IMZMsZH.png"></img>

**Comment by king804** [comment]
我重裝插件後，出現了別的問題
xcode我clear了，再走一次，都是出這個錯誤
<img src="https://i.imgur.com/zzIHAqEg.png"></img>

dyld: Library not loaded: @rpath/RCTAuroraIMUI.framework/RCTAuroraIMUI
  Referenced from: /var/containers/Bundle/Application/44CB7E6A-2595-42C7-9171-9666086F806A/howsyourdate.app/howsyourdate
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/44CB7E6A-2595-42C7-9171-9666086F806A/howsyourdate.app/Frameworks/RCTAuroraIMUI.framework/RCTAuroraIMUI: code signing blocked mmap() of '/private/var/containers/Bundle/Application/44CB7E6A-2595-42C7-9171-9666086F806A/howsyourdate.app/Frameworks/RCTAuroraIMUI.framework/RCTAuroraIMUI'

**Comment by king804** [comment]
以上問題在simulator都沒出現的問題，只有真機才出現，是xcode有什麼位置要設定嗎？

**Comment by huangminlinux** [comment]
在 TARGET->project->Build Phases -> Target dependences 添加 RCTAuroraIMUI 试试

**Comment by cnpmge** [comment]
请问大佬如何解决的？感激不尽！
