### ISSUE TITLE
请问IOS显示头像问题

### ISSUE THREAD

**Issue by chujian** [jpush/aurora-imui#371]
### My environment:

请问IOS头像我应该在什么地方开始下载？因为文件下载是异步的，历史消息是显示本地的，当图片还没下载完的时候，头像文件是不存在的，导致聊天对话窗口读取头像失败而报错。

**Comment by huangminlinux** [comment]
头像下载完后可以调用 updateMessage 接口就可以了

**Comment by chujian** [comment]
谢谢
