### ISSUE TITLE
消息发送框下面的工具栏支持自定义扩展吗？

### ISSUE THREAD

**Issue by 25juan** [jpush/aurora-imui#372]
我现在有个定位的需求，想放到消息发送框下面的工具栏上，请问该组件支持扩展吗？

**Comment by huangminlinux** [comment]
iOS 原生提供了自定义 inputView 的功能 [IMUICustomInutView](https://github.com/jpush/aurora-imui/blob/master/docs/iOS/IMUIInputView_usage_zh.md#imuicustominputview)，android 还没支持。

**Comment by JoshLipan** [comment]
android原生可通过[MenuManager](https://github.com/jpush/aurora-imui/blob/master/Android/chatinput/README_EN.md#menumanagersupport-since-090)自定义菜单项，v0.9.0开始支持
