### ISSUE TITLE
RN chatInput组件内部样式能修改吗

### ISSUE THREAD

**Issue by chaochaocao** [jpush/aurora-imui#375]
>chatInput 图片、录音、及发送按钮的样式在选中的时候能改变背景色来标识已正在操作此项吗

>chatInput 点击图片按钮的时候，不想用chatInput组件的选图片方式，有接口来实现选择手机里的本地图片吗

> MessageList 能发送通告信息吗，即不展示发送方和接受方，只有一条通告信息

**Comment by lzctbyong** [comment]
目前只能自己改原生,我也头疼

**Comment by huangminlinux** [comment]
需要改原生。
