### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by itlws** [jpush/aurora-imui#376]
聊天界面，点击播放语音，然后关闭当前界面，会出现内存泄漏
![image](https://user-images.githubusercontent.com/7419461/40904674-0d877446-680e-11e8-87b7-c4381d015eca.png)

**Comment by JoshLipan** [comment]
需要在MessageListActivity的onDestroy中调用ViewHolderController.getInstance().setReplayVoiceListener(null);来解决内存泄漏，这是sample的不完善，不影响组件使用。
