### ISSUE TITLE
Attempt to read from field 'android.view.View android.support.v7.widget.RecyclerView$ViewHolder.itemView' on a null object reference

### ISSUE THREAD

**Issue by DaiFalin** [jpush/aurora-imui#377]
Android 8.1
调用：mAdapter.addToStart(jmMessage, true)
异常：Attempt to read from field 'android.view.View android.support.v7.widget.RecyclerView$ViewHolder.itemView' on a null object reference

**Comment by JoshLipan** [comment]
这边用官方sample在小米8（Android8.1）测试没有问题
