### ISSUE TITLE
自定义气泡上下边距太大？

### ISSUE THREAD

**Issue by 25juan** [jpush/aurora-imui#378]
version:  "aurora-imui-react-native": "^0.10.1",
在这个版本中我想自定义发送消息的Bubble，
代码如下所示：
![image](https://user-images.githubusercontent.com/14308183/41081954-3ac22598-6a5f-11e8-9b12-bde3ffdfc6d6.png)

所展示的UI 效果如下：
![image](https://user-images.githubusercontent.com/14308183/41081838-dd58e84c-6a5e-11e8-8e81-ec5315b62eea.png)

问题点：上下边距太大，请问这个该怎么调整呢（ps:气泡的图片用的是 github上面example提供的气泡图片,只是改了下背景色而已）？

**Comment by JoshLipan** [comment]
和原始气泡放在同一个drawable文件下，qq上回答你了，关闭

**Comment by 25juan** [comment]
OK 感谢 ！ @JoshLipan

**Comment by niuniubuniu** [comment]
@JoshLipan 麻烦问下 原始气泡在哪个路径 安卓的我没找到

**Comment by JoshLipan** [comment]
https://github.com/jpush/aurora-imui/tree/master/Android/messagelist/src/main/res/drawable-xhdpi

**Comment by niuniubuniu** [comment]
@JoshLipan 对不起没说清楚 我用的RN 的

**Comment by JoshLipan** [comment]
参考[自定义介绍](https://github.com/jpush/aurora-imui/blob/master/ReactNative/docs/APIs_zh.md#messagelist-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)

**Comment by niuniubuniu** [comment]
@JoshLipan 
![0072c168-7c56-4cb4-a236-b93ab13da276](https://user-images.githubusercontent.com/15334495/42368257-225cf35c-8139-11e8-9a8f-6165c02ab967.png)

**Comment by huangminlinux** [comment]
检查padding 是否正确。

**Comment by niuniubuniu** [comment]
@huangminlinux 没看出来问题 ![d319f220-8794-41ff-bd79-efebd5f1fad6](https://user-images.githubusercontent.com/15334495/42378098-a0ff9ce0-8158-11e8-8142-edfa42554ab1.png)

而且我只在sendBubble传入padding参数无效 字体回贴着边框， sendBubblePadding传入padding才显示正常

**Comment by niuniubuniu** [comment]
@JoshLipan 麻烦看下上面发的图  方便的话加你下qq，我的qq 1261103246

**Comment by liuliu66666** [comment]
@niuniubuniu 这个问题解决了吗，我页遇到了这样的问题在RN上

**Comment by JoanBoat** [comment]
@huangminlinux 
<img width="115" alt="2018-09-26 11 17 12" src="https://user-images.githubusercontent.com/25084399/46090004-56ede100-c1e2-11e8-9eb0-4bb1bf7f9dc7.png">
这个sendBubble 自定义气泡有问题 为什么会显示那么多的锯齿

**Comment by CrazyMan2** [comment]
我使用的是sample里的气泡素材，怎么有两条黑边而且变形的？
![image](https://user-images.githubusercontent.com/11832173/79468815-fd523f00-8031-11ea-8694-2b73f6e333a4.png)
