### ISSUE TITLE
MessageList消息列表展示左右颠倒，是否有设置当前用户的位置

### ISSUE THREAD

**Issue by xiaomansjw** [jpush/aurora-imui#380]

**Comment by xiaomansjw** [comment]
react-native version: 0.54.3
aurora-imui-react-native version: 0.9.36
MessageList消息列表展示左右颠倒，是否有设置当前用户的位置

**Comment by huangminlinux** [comment]
检查 isOutGoing 这个字段是否设置反了。

**Comment by xiaomansjw** [comment]
非常感谢，解决了
