### ISSUE TITLE
如何修改MessageList和ChatInput组件的背景颜色？

### ISSUE THREAD

**Issue by django-wong** [jpush/aurora-imui#383]
### My environment:
- `react-native` version: ^0.54.2
- `aurora-imui-react-native` version: ^0.10.1

如何修改MessageList和ChatInput组件的背景颜色？默认是_白色_且不能修改？

**Comment by huangminlinux** [comment]
[chatinputbackgroupcolor](https://github.com/jpush/aurora-imui/blob/master/ReactNative/docs/APIs.md#chatinputbackgroupcolor)

[messagelistbackgroundcolor](https://github.com/jpush/aurora-imui/blob/master/ReactNative/docs/APIs.md#messagelistbackgroundcolor)

**Comment by django-wong** [comment]
chatInputBackgroupColor修改的是外层wrapper的颜色


![image](https://user-images.githubusercontent.com/4019240/41608211-8b77e472-741a-11e8-903d-80af10ff6ba1.png)


```
<MessageListView style={this.state.messageListLayout}
    ...                
    messageListBackgroundColor="#000000"
    ...
/>

<InputView style={this.state.inputViewLayout}
    ....
    chatInputBackgroupColor="#ff0000"
    inputTextColor="red"
    ...
/>
```

**Comment by huangminlinux** [comment]
其他颜色没有提供配置项
