### ISSUE TITLE
React Native 希望能写详细点的文档，

### ISSUE THREAD

**Issue by youngjuning** [jpush/aurora-imui#384]
试了一下午，愣是没有成功圆形

**Comment by huangminlinux** [comment]
报什么错误？

**Comment by youngjuning** [comment]
希望你们能把文档重新写一下，其实只要把 android gradle 版本升级到 3.0.0 以上，不需要那么麻烦。而且现在都已经是 3.1.0 了。用户更新这个是必须的。很多插件都已经要求 gradle 3.0.0 以上了。

我也是在升级到 3.0.0 之后，用你们的组件才没有问题的了

**Comment by youngjuning** [comment]
https://github.com/youngjuning/issue-blog/issues/91
