### ISSUE TITLE
No visible @interface for 'IMUIInputView' declares the selector 'isNeedShowBottomView'

### ISSUE THREAD

**Issue by tangshuang** [jpush/aurora-imui#385]
### My environment:
- `react-native` version: 0.55.4
- `aurora-imui-react-native` version:0.10.2

用Xcode编译的时候提示：
No visible @interface for 'IMUIInputView' declares the selector 'isNeedShowBottomView'

请问怎么处理？

**Comment by huangminlinux** [comment]
可以升级到 aurora-imui-react-native@0.10.3
