### ISSUE TITLE
RTCMessageList does not exist

### ISSUE THREAD

**Issue by xiaoniuge** [jpush/aurora-imui#387]

**Comment by xiaoniuge** [comment]
"react-native": "^0.51.0",
"aurora-imui-react-native": "^0.10.4",

**Comment by huangminlinux** [comment]
插件版本多少？
link 成功没？

**Comment by xiaoniuge** [comment]
@huangminlinux 
我是用Android调试的
link输出的信息：
rnpm-install info Linking aurora-imui-react-native ios dependency
rnpm-install info Platform 'ios' module aurora-imui-react-native has been successfully linked
版本：
"react-native": "^0.51.0",
"aurora-imui-react-native": "^0.10.4",

**Comment by xiaoniuge** [comment]
@huangminlinux 
这是link时候的信息 Android的 好像link不上啊
D:\react\demo>react-native link aurora-imui-react-native
Scanning folders for symlinks in D:\react\demo\node_modules (37ms)
rnpm-install info Platform 'ios' module aurora-imui-react-native is already linked

**Comment by JoshLipan** [comment]
link失败可以手动配置下，参照[install教程](https://github.com/jpush/aurora-imui/tree/master/ReactNative#install)
