### ISSUE TITLE
长按事件获取到的message.content为undefined？

### ISSUE THREAD

**Issue by hjylxh** [jpush/aurora-imui#389]
![image](https://user-images.githubusercontent.com/32626148/42067877-43433cd4-7b7b-11e8-96b8-b56a48d92318.png)

android的问题

**Comment by huangminlinux** [comment]
android 还是 iOS 端出现的问题?

**Comment by JoshLipan** [comment]
你是要获取什么类型Message的content，不是所有message都有content的，参照[Message定义](https://github.com/jpush/aurora-imui/blob/master/ReactNative/docs/Models.md#message)

**Comment by hjylxh** [comment]
![image](https://user-images.githubusercontent.com/32626148/42069134-9c2bb554-7b82-11e8-985e-062e227886e9.png)
message.msgType === "text"  要获取这个的

**Comment by JoshLipan** [comment]
message.msgType === "text" 对应的文本内容参数是message.text,文档里写了

**Comment by hjylxh** [comment]
@JoshLipan 
哦哦哦，咦，那看错了，多谢了
