### ISSUE TITLE
Linking RN library causes Google Play to display 0 supported devices

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [jpush/aurora-imui#390]
### My environment:
- `react-native` version: 0.55.3
- `aurora-imui-react-native` version: 0.10.4

Hello, thank you for the awesome library. As title said, I got that issue when I tried to link to my current codebase. I linked it successfully, but when I try to upload the `apk` to Google Play, it shows:

![Linked with IMUI](https://puu.sh/ANPHL.png)

And when I remove it:

![Without IMUI](https://puu.sh/ANPIT.png)

There might be some troubles with the library. Any idea what they might be?

**Comment by JoshLipan** [comment]
Did you add [proguard rule](https://github.com/jpush/aurora-imui/tree/master/ReactNative#android-release-generate-release-apk) for your project?

**Comment by Doko-Demo-Doa** [comment]
No I didn't, is that the actual reason?

**Comment by JoshLipan** [comment]
You need to add this rule when you want to release a apk.And for your problem ,maybe this [issue](https://stackoverflow.com/questions/14020237/android-app-is-supported-by-0-devices) can help you from stackoverflow.
![default](https://user-images.githubusercontent.com/16323137/42084135-71d0d2d4-7bbf-11e8-9427-1a8a0f81f016.png)
![default](https://user-images.githubusercontent.com/16323137/42084151-7c3027f2-7bbf-11e8-9b60-5f3a64b9cc22.png)

**Comment by dogbutcat** [comment]
@JoshLipan No, it's not work, as chatinput library pack the manifest with required option
https://github.com/jpush/aurora-imui/blob/a18f0667f29f84d67a0bfdaf19784c3888f6c4f6/Android/chatinput/src/main/AndroidManifest.xml#L9-L10

**Comment by Doko-Demo-Doa** [comment]
In my case, it works. I don't use camera feature so I didn't bumped in to above problem.

**Comment by dogbutcat** [comment]
@Doko-Demo-Doa You'r quite the luck! It already drives me crazy, I finally extract the lib & change the feature to false, then it works. I think it's better to set to false where react-native-camera did.
