### ISSUE TITLE
android下拉刷新问题

### ISSUE THREAD

**Issue by flyinggor** [jpush/aurora-imui#391]
messagelist不能用自定义的下拉刷新控件吗,用的 SmartRefreshLayout下拉会没有

**Comment by flyinggor** [comment]
4天过去了..

**Comment by JoshLipan** [comment]
在对应刷新回调里处理数据加载就可以，你说的下拉会没有是什么意思

**Comment by flyinggor** [comment]
用SmartRefreshLayout来做下拉刷新,下拉没效果,拉不下来,另外还想问下,对发送语音限制最长60s可以做限制吗

**Comment by JoshLipan** [comment]
看下这个issue #266

**Comment by SanChunAndrroid** [comment]
这下拉有bug 要拖动一下列表才能刷新 各位大佬咋搞
