### ISSUE TITLE
Hide buttons

### ISSUE THREAD

**Issue by eduardorocha82** [jpush/aurora-imui#394]
Hello

In react native the customLayoutItems property works only for iOs.

How can I hide voicemails, emojis, photos on Android?

I just want to keep the send button.

Where and what class could I change in the native java code?

Thank you

**Comment by JoshLipan** [comment]
[layout_chatinput_menu.xml](https://github.com/jpush/aurora-imui/blob/master/Android/chatinput/src/main/res/layout/layout_chatinput_menu.xml)

**Comment by eduardorocha82** [comment]
Hi,

Thanks, but I'm using React Native, no there are this file!

Can I use this?

Thanks

**Comment by JoshLipan** [comment]
Sorry，you can only modify the native android code for this.

**Comment by eduardorocha82** [comment]
Got it,

If I modify the native code, can I have the buttons hidden in React Native?

Could you tell me which class I should modify?

Thanks

**Comment by JoshLipan** [comment]
You can modify [ChatInputView.java](https://github.com/jpush/aurora-imui/blob/master/Android/chatinput/src/main/java/cn/jiguang/imui/chatinput/ChatInputView.java#L96) or [layout_chatinput_menu.xml](https://github.com/jpush/aurora-imui/blob/master/Android/chatinput/src/main/res/layout/layout_chatinput_menu.xml).
