### ISSUE TITLE
不清楚sendBubble和receiveBubble的imageName 是哪里来的 自己的气泡背景图需要放到哪个路径

### ISSUE THREAD

**Issue by niuniubuniu** [jpush/aurora-imui#395]

**Comment by huangminlinux** [comment]
imageName 是你图片资源的文件名，需要将图片资源拖到工程中。

**Comment by niuniubuniu** [comment]
@huangminlinux 谢了 我看了源码才看出来是原生读取的图片

**Comment by CrazyMan2** [comment]
设置无效
![image](https://user-images.githubusercontent.com/11832173/79466301-fa098400-802e-11ea-90f1-f5a137b5fbcd.png)

![image](https://user-images.githubusercontent.com/11832173/79466252-e9f1a480-802e-11ea-909a-546a88646484.png)
