### ISSUE TITLE
reactnative android 点击相册按钮, 没反应????

### ISSUE THREAD

**Issue by HHuiHao** [jpush/aurora-imui#397]
- `react-native` version:  0.55.2
- `aurora-imui-react-native` version: 最新
- `android`

点击**进入相册**按钮, 没反应????

**Comment by JoshLipan** [comment]
你是不是拒绝权限申请了

**Comment by youngjuning** [comment]
我点击所有的菜单栏按钮都不会切换啊，是怎么回事

**Comment by youngjuning** [comment]
@HHuiHao 兄弟，你解决了吗？

**Comment by JoshLipan** [comment]
menu的相册点击没反应检查权限问题，子菜单中的相册按钮不处理业务逻辑，抛出事件[onClickSelectAlbum](https://github.com/jpush/aurora-imui/blob/dev/ReactNative/docs/APIs_zh.md#onclickselectalbum)

**Comment by youngjuning** [comment]
那我想实现点击子菜单按钮打开相册，有没有实现的方法呢

**Comment by JoshLipan** [comment]
可以看下这个插件react-native-image-picker

**Comment by HHuiHao** [comment]
菜单的相册按钮打开能获取相片. 我说的是进入系统相册按钮, , 点击无反应!!!

**Comment by JoshLipan** [comment]
不是回复你了，子菜单中的相册按钮不处理业务逻辑，抛出事件onClickSelectAlbum

**Comment by HHuiHao** [comment]
我的问题, 你们那边有出现吗? (华为手机, EMUI系统 4.03, Android 6.0)

**Comment by JoshLipan** [comment]
打开系统相册需要你自己处理，点击相册按钮imui只负责抛出[onClickSelectAlbum](https://github.com/jpush/aurora-imui/blob/dev/ReactNative/docs/APIs_zh.md#onclickselectalbum)事件，剩下的逻辑自己完成

**Comment by HHuiHao** [comment]
好的, 感谢!
