### ISSUE TITLE
react native android 菜单栏点击没有反应

### ISSUE THREAD

**Issue by youngjuning** [jpush/aurora-imui#398]
我没有拒绝权限，点击所有的菜单栏都没有反应

**Comment by JoshLipan** [comment]
你跑的官方sample还是自己去集成出现的问题？对应的版本信息是什么
以后提issue最好提供全面点的信息帮助定位问题

**Comment by JoshLipan** [comment]
RN-Android 暂时不支持inputview 自定义控制排版显示，关注issue #372

**Comment by youngjuning** [comment]
不是自定义的问题，我这边自己写的不会切换模式

**Comment by JoshLipan** [comment]
参考sample和api吧，对比下你的项目

**Comment by youngjuning** [comment]
必须写 onSizeChange 回调，感觉这样很麻烦

**Comment by huangminlinux** [comment]
如果不使用 onSizeChange 这个方法，也能正常使用，不过需要用户自行处理下面的情况：
- 处理键盘的弹入弹出
- 处理 inputview 各种按钮的点击事件来计算 inputView

**Comment by youngjuning** [comment]
你们那个 sample 真坑的，好多API，在 RN 的文档中并没有写。比如 `switchCameraMode={this.switchCameraMode}`

**Comment by JoshLipan** [comment]
谢谢建议，后续我们会注意文档完善
