### ISSUE TITLE
android  小米5  无法进行拍照  出现拍照是黑色背景

### ISSUE THREAD

**Issue by tao0111225** [jpush/aurora-imui#4]

**Comment by KenChoi1992** [comment]
@tao0111225 请检查一下设置中有没有获得拍照权限

**Comment by tao0111225** [comment]
@KenChoi1992 恩，没有开启 。因为我第一次打开拍照的时候，有权限提示 。
  第二次点击视频拍照并没有提示  ，所以第一次我就以为全部开启了。

视频预览 和手机 预览效果不一样。   
[
![_20170505142231](https://cloud.githubusercontent.com/assets/13714111/25735483/4e1b74fa-319e-11e7-9443-ee623a2f8832.jpg)
![_20170505142235](https://cloud.githubusercontent.com/assets/13714111/25735484/4e289b4e-319e-11e7-82f3-ed86711fbbed.jpg)

](url)

如果可以的话，我也慢慢帮你们弄照相机这一模块。      适配手机 坑无数

**Comment by KenChoi1992** [comment]
@tao0111225 那就非常感谢了，这块问题确实比较多……国内的机型你懂的。

**Comment by KenChoi1992** [comment]
@tao0111225 目前权限这块是要自己在回调里申请的：
```
chatInput.setMenuClickListener(new OnMenuClickListener() {
   ...
    @Override
    public void switchToCameraMode() {
        // 申请权限
        ...
    }

```
预览效果的话，确实目前还不完善。
