### ISSUE TITLE
用一个数组保存消息 id 的作用是什么

### ISSUE THREAD

**Issue by youngjuning** [jpush/aurora-imui#401]
### My environment:

- `react-native` version: 0.55.4
- `aurora-imui-react-native` version: 0.10.4

![image](https://user-images.githubusercontent.com/13204332/42499808-50be758c-8462-11e8-8b24-0c08ccc23bf8.png)

用一个数组保存消息 id 的作用是什么

**Comment by huangminlinux** [comment]
之前图片预览的时候用到，现在已经去除这部分功能，没删除干净，我重新提交一下。

**Comment by youngjuning** [comment]
顺便问一下，demo里边，音频是可以直接播放的，但是视频和图片无法预览。我想请教一下你们视频播放和图片预览的思路和具体操作。感谢

**Comment by huangminlinux** [comment]
提供了消息点击事件  [onMsgClick](https://github.com/jpush/aurora-imui/blob/master/ReactNative/docs/APIs_zh.md#onmsgclick), 可以在这个回调中构建新的 视频播放和图片预览的界面。

**Comment by huangminlinux** [comment]
可以试试这个 https://github.com/react-native-community/react-native-video

**Comment by youngjuning** [comment]
谢谢
