### ISSUE TITLE
【BUG】点击拍照按钮，会触发三次 onTakePicture

### ISSUE THREAD

**Issue by youngjuning** [jpush/aurora-imui#403]
### My environment:

- `react-native` version: 0.55.4
- `aurora-imui-react-native` version: 0.10.4

sample 的代码执行也是这样的。

![image](https://user-images.githubusercontent.com/13204332/42500957-32e03728-8465-11e8-8e5d-613680a405f4.png)

![20180710_171836](https://user-images.githubusercontent.com/13204332/42500993-4bf2e76a-8465-11e8-9a40-df99b5618585.png)

**Comment by youngjuning** [comment]
您在测试这个BUG吗？如果暂时不修复的话，我可以禁用这个视频拍摄的功能吗？

**Comment by youngjuning** [comment]
![20180710_174033](https://user-images.githubusercontent.com/13204332/42502351-5d2722be-8468-11e8-850f-bb0bbc5ed900.png)
这是实际的，可以看到三张是一模一样的

**Comment by huangminlinux** [comment]
手机机型是什么？

**Comment by youngjuning** [comment]
华为 SLA-AL00

**Comment by youngjuning** [comment]
oppo r9 plus 正常

**Comment by JoshLipan** [comment]
我这边测试只执行一次

**Comment by alleniver** [comment]
demo 好几个月没更新过了，可以更新一下，RN 已经0.56.1了，React 也到了16.4.1了，把版本升上去后测试问题比较多，比如底部的按钮设置无效，摄像头拍照出现3个图片，相册的筛选最好还是用直接打开相册的方式，底部这么一排找图比较难找，特别是图片比较多的情况下，可以考虑整合一下react-native-syan-image-picker或者react-native-image-crop-picker这类组件。其他还没仔细测试过。

**Comment by youngjuning** [comment]
@alleniver 这个库的UI层渲染用的 原生的你敢信？这对于前端转过来的很不友好。我想集成 react-native-lightbox 都办不到，强烈建议把 UI 层 用 react-native 写，这样我们就可以自己很方便地集成第三方插件

**Comment by jwan3453** [comment]
三星s8 上面也有这个问题

**Comment by JoshLipan** [comment]
更新到 0.10.9
