### ISSUE TITLE
【BUG】全屏模式下拍照会 crash

### ISSUE THREAD

**Issue by youngjuning** [jpush/aurora-imui#404]
### My environment:

- `react-native` version: 0.55.4
- `aurora-imui-react-native` version: 0.10.4
- 系统： oppo r9 plus

调试模式下，点击全屏直接卡死，release的话，点击发送回闪回桌面

**Comment by youngjuning** [comment]
我可以在安卓下面禁用这个 camare吗

**Comment by youngjuning** [comment]
@JoshLipan 是要修改源码吗？

**Comment by youngjuning** [comment]
我尝试了一下，弄不好，我就是想在 安卓下把那个camareMode 给去掉。有没有最佳实践呢。或者把 ios 可以自定义的加到 android 上

**Comment by JoshLipan** [comment]
去掉camera我们有提供参数设置的，hideCameraButton={true}

**Comment by youngjuning** [comment]
期待你们把文档完善一下，降低使用难度
