### ISSUE TITLE
RN , 怎么隐藏录视频按钮?

### ISSUE THREAD

**Issue by HHuiHao** [jpush/aurora-imui#406]
RN , 怎么隐藏录视频按钮?
<img width="414" alt="111111" src="https://user-images.githubusercontent.com/8486113/42669552-a73e8942-8688-11e8-993f-becf150fc465.png">

**Comment by JoshLipan** [comment]
没有提供这个API，可以自己修改原生满足个性化需求

**Comment by HHuiHao** [comment]
@JoshLipan 这边没找到对应的修改类哦(ReactNative android)

**Comment by HHuiHao** [comment]
求解答.. 怎么对应的修改类是哪个? (ReactNative)

**Comment by JoshLipan** [comment]
rn没有提供这个相关方法和类，需要修改了原生再把原生项目导入rn，原生对应的类[ChatInputView.java](https://github.com/jpush/aurora-imui/blob/master/Android/chatinput/src/main/java/cn/jiguang/imui/chatinput/ChatInputView.java#L96)

**Comment by HHuiHao** [comment]
好的, 有点麻烦, 希望后期能增加这个. 还有iOS进相册功能(Android有)
