### ISSUE TITLE
关于图片预览的问题

### ISSUE THREAD

**Issue by youngjuning** [jpush/aurora-imui#407]
![image](https://user-images.githubusercontent.com/13204332/42684165-decd7bc8-86c1-11e8-873f-b7d965696b26.png)

这个地址，我怎么显示呢？你们是怎么在页面中显示的？

**Comment by youngjuning** [comment]
我要把图片存到服务器，这个地址可以用吗

**Comment by huangminlinux** [comment]
需要使用本地图片，可以先将图片下载到本地。

**Comment by jwan3453** [comment]
@huangminlinux 那是不是像历史消息的图片也要重新下载 然后保存到本地显示吗。 为何不提供直接加载网络图片的功能？

**Comment by youngjuning** [comment]
@jwan3453 只有语音需要下载

**Comment by jwan3453** [comment]
@youngjuning 那是如何展示网络图片的， api 找了下没看到

**Comment by youngjuning** [comment]
我发送的时候，后端上传到服务器上。所以显示就是直接拿到网络地址显示

**Comment by jwan3453** [comment]
@youngjuning ios上显示网络图片我用的是custom message， 然后放在html  img 里面显示， 但是android用这个方法就不行， 有解决方案吗

**Comment by JoshLipan** [comment]
#413
