### ISSUE TITLE
我想自定义视图，怎么搞？

### ISSUE THREAD

**Issue by youngjuning** [jpush/aurora-imui#408]
我想给图片信息加上灯箱 react-native-lightbox，请问怎么做，需要改原生代码对吧？

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/42793669-c475e910-89ad-11e8-855e-ddd08bec222f.png)
我看了源码，你们连视图渲染用的都是原生，这让我从rn层面改都不可行啊。。。

**Comment by JoshLipan** [comment]
是的，RN版本是从原生扩展过来的，如果你对完全RN渲染有兴趣，欢迎提交PR
