### ISSUE TITLE
语音无法播放网络地址

### ISSUE THREAD

**Issue by youngjuning** [jpush/aurora-imui#409]
我这边语音上传到服务器的，然后语音无法播放

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/42803805-b260b47c-89d9-11e8-9963-4618cb1c0cee.png)

**Comment by youngjuning** [comment]
请问，这个问题怎么解决呢？

**Comment by huangminlinux** [comment]
需要下载到本地进行播放。

**Comment by youngjuning** [comment]
@huangminlinux 具体怎么操作呢？完全没有思路啊

**Comment by youngjuning** [comment]
点击的时候下载的话，怎么替换那个地址呢？

**Comment by youngjuning** [comment]
我知道怎么下载到本地，但是我不知道怎么去替换mediaPath那个路径

**Comment by huangminlinux** [comment]
可以使用 https://github.com/itinance/react-native-fs 下载到本地。然后调用 sendvoide 或者 updatemessage

**Comment by youngjuning** [comment]
sendvoide 是什么？

**Comment by youngjuning** [comment]
转成 mp3 存起来可以吗？

**Comment by huangminlinux** [comment]
sendMessage(voiceMessage)
----
可以

**Comment by youngjuning** [comment]
可与转成mp3，就不用下载到本地了？

**Comment by huangminlinux** [comment]
带 path 的参数都要求是本地路径。

**Comment by youngjuning** [comment]
我在 onMsgClick 的时候 去 sendMessage(voiceMessage)？

**Comment by youngjuning** [comment]
我的思路是发送消息的时候保存语音到本地，替换远程地址为本地地址。

**Comment by huangminlinux** [comment]
使用 messageList 的时候只需要保证 [appendMessages](https://github.com/jpush/aurora-imui/blob/master/ReactNative/docs/APIs_zh.md#appendmessages) 这个方法里面的 message.mediaPath 是本地路径就行。这样就能够保证可以正常播放，如果消息已经在 messageList 中 可以通过 [updateMessage](https://github.com/jpush/aurora-imui/blob/master/ReactNative/docs/APIs_zh.md#updatemessage) 这个接口来更新 mediaPath。

**Comment by youngjuning** [comment]
我遇到了在异步的中，不能给对象的属性复制的错误

**Comment by youngjuning** [comment]
谢谢，昨天搞定了这个，确实是用的解构

**Comment by qxj006** [comment]
下载好语音，调用updateMessage更新消息，还要手动再点一次语音才能播放，怎么解决请问
