### ISSUE TITLE
如何隐藏软件盘

### ISSUE THREAD

**Issue by youngjuning** [jpush/aurora-imui#410]
我想实现的是从会话列表退出时，隐藏软键盘，也就是输入框失去焦点

**Comment by huangminlinux** [comment]
可以试试 hidenFeatureView

**Comment by youngjuning** [comment]
会报错，我是在卸载的钩子函数中添加的

**Comment by youngjuning** [comment]
https://github.com/DanielMSchmidt/react-native-dismiss-keyboard 和react-native 的 KeyBord.dismiss 都试了

**Comment by huangminlinux** [comment]
调用下面这段代码报什么错误？
```
AuroraIMUIController.hidenFeatureView(false)
```

**Comment by youngjuning** [comment]
@huangminlinux 谢谢，就可以了，我没有加false
