### ISSUE TITLE
安卓昵称过长显示...

### ISSUE THREAD

**Issue by youngjuning** [jpush/aurora-imui#411]
### My environment:

- `react-native` version: 0.54.0
- `aurora-imui-react-native` version: 0.10.8

![image](https://user-images.githubusercontent.com/13204332/43395034-443f21da-942f-11e8-9475-b7d979fec24a.png)

如图，我想让这里的昵称显示完整的，能提供一下思路或者解决方案吗？感谢！！！

**Comment by youngjuning** [comment]
@huangminlinux 有解决办法吗？或者是我怎么修改这块

**Comment by JoshLipan** [comment]
RN没有提供设置方法，需要改原生属性[android:ems](https://github.com/jpush/aurora-imui/blob/master/Android/messagelist/src/main/res/values/styles.xml#L38)，去掉这个属性显示全称

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/43505095-5f694732-9598-11e8-9c95-4f1ea5340d57.png)
我没有找到你说的这个文件

**Comment by youngjuning** [comment]
npm 下载的包里没有你说的这个文件

**Comment by JoshLipan** [comment]
在原生库messagelist里面，下载[原生库](https://github.com/jpush/aurora-imui/tree/master/Android/messagelist)修改完，[RN插件的依赖](https://github.com/jpush/aurora-imui/blob/master/ReactNative/android/build.gradle#L30)替换成你的本地库；

**Comment by youngjuning** [comment]
本地的路径如何引用啊，我只是个写js的

**Comment by youngjuning** [comment]
还有一个问题啊，我 装其他依赖的话，修改过的就会恢复，我还要再修改。请问可以把这个暴露一个配置项吗？毕竟超过5个字就省略有定说不过去啊

**Comment by gitfdy** [comment]
我这边已经进行了替换 我是直接把messagelist的代码整个贴到项目里面,然后修改样式的 . 但是始终不生效,请问下楼主这个问题解决了吗?

**Comment by JoshLipan** [comment]
@gitfdy 最新的版本可以通过 [displayNameEmsNumber](https://github.com/jpush/aurora-imui/blob/master/ReactNative/android/src/main/java/cn/jiguang/imui/messagelist/viewmanager/ReactMsgListManager.java#L536) 参数来设置昵称显示长度，Android only

**Comment by gitfdy** [comment]
@JoshLipan  非常感谢 感看到 使用这个属性已经解决了

**Comment by youngjuning** [comment]
@gitfdy 请教下你用的即时通讯是那家的

**Comment by youngjuning** [comment]
@gitfdy 请教下你用的即时通讯是那家的

**Comment by gitfdy** [comment]
> @gitfdy 请教下你用的即时通讯是那家的

我使用的网易云信
