### ISSUE TITLE
react native 气泡的背景色

### ISSUE THREAD

**Issue by jwan3453** [jpush/aurora-imui#412]
想问下在react native 是否能修改 send 和 receive 的气泡的背景色？

**Comment by huangminlinux** [comment]
想要替换背景图片可以替换泡泡的的图像资源[参考](https://github.com/jpush/aurora-imui/blob/master/ReactNative/docs/APIs_zh.md#messagelist-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)
