### ISSUE TITLE
native android 的 custom 消息类型

### ISSUE THREAD

**Issue by jwan3453** [jpush/aurora-imui#413]
custom 的消息类型在ios 上可以显示网络图片， 而且style 也可以正常运用，
但是android 上面的custom 消息类型就不行， 图片只能显示本地图片， style 也无效，求解

**Comment by JoshLipan** [comment]
参考下[demo](https://github.com/jpush/aurora-imui/blob/master/ReactNative/sample/App.js#L463)

**Comment by Tiger-man** [comment]
真么发送自定义消息了

**Comment by jwan3453** [comment]
@Tiger-man 可以看下react native 的example [https://github.com/jpush/aurora-imui/blob/master/ReactNative/sample/App.js#L463](url)

**Comment by Tiger-man** [comment]
我看到代码里边只有往UI组件里边插数据 但是实际上没有发送消息

**Comment by Tiger-man** [comment]
@jwan3453 我看到代码里边只有往UI组件里边插数据 但是实际上没有发送消息

**Comment by Tiger-man** [comment]
@jwan3453 求指教

**Comment by jwan3453** [comment]
@Tiger-man 具体是如何发送的要自己实现的， 比如说你用的是socket.io , 那应该是把消息向发送给自己的socket 服务器，成功之后在向ui 插入那条消息.

**Comment by jwan3453** [comment]
放弃用custom 的类型显示图片了,  保存在本地然后显示了，还有android 的custom message 显示用的是android 的textView. 很多标签是没有style 属性的，

**Comment by JohnTree** [comment]
@jwan3453  你好 可以问下您 custom 的类型显示图片 我的怎么是一条线吗 图片很小 另外style真的没用。。

**Comment by JohnTree** [comment]
我把其他的标签都去了就显示了。。。原来是文字挤压的
