### ISSUE TITLE
ld: library not found for -lRCTWebSocket 

### ISSUE THREAD

**Issue by huangminlinux** [jpush/aurora-imui#416]
### My environment:
`aurora-imui-react-native` version: 0。40.0+

link 成功，运行报错

**Comment by huangminlinux** [comment]
解决方案： TARGETS -》Build Phases -》 Target Dependencies 添加 RCTWebSocket

**Comment by pref-mail** [comment]
why my Xcode  TARGETS -》Build Phases -》 Target Dependencies  has not find RCTWebSocket

Xcode 10.3 
RN:0.60.4
