### ISSUE TITLE
iOS消息列表显示顺序反了

### ISSUE THREAD

**Issue by Helry** [jpush/aurora-imui#418]

**Comment by youngjuning** [comment]
+1

**Comment by huangminlinux** [comment]
iOS  的消息列表和数据传入顺序一一对应，检查传入数据。

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/43825884-7c1c155e-9b28-11e8-8b39-b53e4b86da03.png)
确定这个方法之前的数据顺序是对的，执行了这个之后页面就是反的。所以怀疑这个方法ios下有BUG

**Comment by huangminlinux** [comment]
insertMessagesToTop 这个方法确实是有问题，已修复，可以升级到  0.12.1 版本。
