### ISSUE TITLE
ios上的图片和头像使用网络地址不显示

### ISSUE THREAD

**Issue by zoumin-hxb** [jpush/aurora-imui#421]
![image](https://user-images.githubusercontent.com/36915845/44073956-4501f5ca-9fc9-11e8-8c6c-e44eeacb0bdc.png)

**Comment by NightRaid1** [comment]
一样的问题...

**Comment by huangminlinux** [comment]
iOS 暂时只支持 本地路径图片。

**Comment by huangminlinux** [comment]
可以升级到 0.10.11 版本
