### ISSUE TITLE
react-native run-ios 报编译错误

### ISSUE THREAD

**Issue by zhonggithub** [jpush/aurora-imui#427]
在的项目加入该模块后ios 环境下报错误
错误信息如下：
The following build commands failed:
        CompileC /Users/zz/workspace/zz/UServiceApp/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTShadowView+Internal.o Views/RCTShadowView+Internal.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/zz/workspace/zz/UServiceApp/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTUIManagerUtils.o Modules/RCTUIManagerUtils.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/zz/workspace/zz/UServiceApp/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTMultipartStreamReader.o Base/RCTMultipartStreamReader.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/zz/workspace/zz/UServiceApp/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTSourceCode.o Modules/RCTSourceCode.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/zz/workspace/zz/UServiceApp/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTFrameUpdate.o Base/RCTFrameUpdate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(5 failures)

react-native : 0.55.4
aurora-imui-react-native： 0.10.10

**Comment by huangminlinux** [comment]
link 成功没？

**Comment by zhonggithub** [comment]
ios link 成功，安卓link 不成功

**Comment by zhonggithub** [comment]
能把ios 手动link 的过程也放出来吗
