### ISSUE TITLE
出现编译错误

### ISSUE THREAD

**Issue by CreateByCool** [jpush/aurora-imui#428]
### My environment:

<!-- if native android  
- native version

> 
![default](https://user-images.githubusercontent.com/13312824/44379807-4474ed80-a53a-11e8-88ca-d8d6ed007295.png)

**Comment by Lpbzzz** [comment]
![view](https://user-images.githubusercontent.com/28721487/44379775-1f807a80-a53a-11e8-9493-95dcbb94fa58.jpg)

**Comment by CreateByCool** [comment]
![default](https://user-images.githubusercontent.com/13312824/44379835-65d5d980-a53a-11e8-8942-9c4ce35c7dd9.png)

**Comment by JoshLipan** [comment]
1.网络环境问题
2.gradle版本问题，试下下面的版本
/android/build.gradle修改如下：

dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
/android/gradle/wrapper/gradle-wrapper.properties中修改：

distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
