### ISSUE TITLE
自定义ViewHolder编译不通过！

### ISSUE THREAD

**Issue by DaiFalin** [jpush/aurora-imui#429]
Android：
compile 'cn.jiguang.imui:messagelist:0.7.2'
自定义：ViewHolder
MsgListAdapter.HoldersConfig holdersConfig = new MsgListAdapter.HoldersConfig();
 holdersConfig.setSenderVoiceMsg(JMVoiceViewHolder.class, R.layout.item_send_voice);
holdersConfig.setReceiverVoiceMsg(JMVoiceViewHolder.class, R.layout.item_receive_voice);
编译报错：
错误: 不兼容的类型: Class<JMVoiceViewHolder>无法转换为Class<? extends BaseMessageViewHolder<? extends IMessage>>
JMVoiceViewHolder代码
public class JMVoiceViewHolder<MESSAGE extends IMessage> extends BaseMessageViewHolder<MESSAGE>
        implements MsgListAdapter.DefaultMessageViewHolder, ViewHolderController.ReplayVoiceListener {...}

**Comment by JoshLipan** [comment]
参考下 #363
