### ISSUE TITLE
有支持群聊的计划吗

### ISSUE THREAD

**Issue by musicode** [jpush/aurora-imui#43]
如题

**Comment by huangminlinux** [comment]
等自定义消息出来，就可以满足群聊的业务逻辑了。

**Comment by musicode** [comment]
自定义消息是否支持 谁把谁拉进了谁，谁把谁踢了，谁改了群名称，或者是类似微信可以分享一个网页到会话中呢？

**Comment by huangminlinux** [comment]
自定义消息，样式可以完全自己来定义，具体的样式需要自己来实现。

**Comment by musicode** [comment]
可否默认给几种呢，我是 RN 开发者，不会原生，我不知道你说的自己实现，是否要自己写原生代码

**Comment by huangminlinux** [comment]
可以提供默认样式。

**Comment by musicode** [comment]
我遇到的需求，其实只需要两种，一种是通知型的灰底白色，一种是 title + content + img 型的分享类消息，希望你们能支持，万分感谢

**Comment by KenChoi1992** [comment]
@musicode 通知型现在已经支持了

**Comment by musicode** [comment]
@KenChoi1992 RN 支持么，文档也有了么？

**Comment by huangminlinux** [comment]
可以升级到 [0.5.10](https://github.com/jpush/aurora-imui/releases/tag/0.5.10-rn) 用自定义消息实现   ，具体用法可以参考 demo。
