### ISSUE TITLE
时间和状态设置无效【iOS_Object-c】

### ISSUE THREAD

**Issue by HHuiHao** [jpush/aurora-imui#433]
![image](https://user-images.githubusercontent.com/8486113/44561620-2dc3d600-a788-11e8-8c39-6f1741850918.png)

**Comment by huangminlinux** [comment]
更新了 demo， 可以更新一下

**Comment by HHuiHao** [comment]
@huangminlinux 时间上面为啥会有重复的文本消息？怎么去掉？
![image](https://user-images.githubusercontent.com/8486113/44563790-72ed0580-a792-11e8-9088-eab97e22ed55.png)

**Comment by HHuiHao** [comment]
好 ，谢谢.
