### ISSUE TITLE
更新cocoapod版本

### ISSUE THREAD

**Issue by chy89310** [jpush/aurora-imui#436]
你好，可以麻煩更新一下pod的版本麼？
現在pod的版本是0.10.1，這個版本裡面，Objective-C的環境中，IMUIInputView獲取不到delegate，似乎是因為因為缺少 @objc 的標識符，但我見master的branch上這個問題已經解決了，希望可以更新一下cocoapod版本，謝謝！

**Comment by huangminlinux** [comment]
今天会发布一个版本。

**Comment by huangminlinux** [comment]
已更新

**Comment by chy89310** [comment]
@huangminlinux thank you！
