### ISSUE TITLE
ReactChatInputManager 你们这个类不报错么  有import cn.jiguang.imui.chatinput.ChatInputView;这个包路径么

### ISSUE THREAD

**Issue by xiaoniuge** [jpush/aurora-imui#438]

**Comment by JoshLipan** [comment]
[ReactChatInputManager.java#L53](https://github.com/jpush/aurora-imui/blob/master/ReactNative/android/src/main/java/cn/jiguang/imui/messagelist/viewmanager/ReactChatInputManager.java#L53)

**Comment by xiaoniuge** [comment]
\aurora-imui-react-native\ReactNative\android\src\main\java\cn\jiguang\imui\messagelist\viewmanager\ReactChatInputManager.java:53: 错误: 程序包cn.jiguang.imui.chatinput不存在
import cn.jiguang.imui.chatinput.ChatInputView;

报错 找不到程序包

**Comment by JoshLipan** [comment]
用最新的v0.10.12试下
