### ISSUE TITLE
100%之后 启动项目时报这错

### ISSUE THREAD

**Issue by xjnxn1314808** [jpush/aurora-imui#448]

**Comment by xjnxn1314808** [comment]
![image](https://user-images.githubusercontent.com/30460115/45220839-218c5c80-b2e2-11e8-9316-a1a466377c4a.png)

**Comment by JoshLipan** [comment]
这不是IMUI抛的错，参考下RN的[issue](https://github.com/facebook/react-native/issues/20042)
