### ISSUE TITLE
输入框获取焦点时，页面布局乱掉了

### ISSUE THREAD

**Issue by youngjuning** [jpush/aurora-imui#452]
这是我的 AndroidManifest.xml

![image](https://user-images.githubusercontent.com/13204332/45336377-dca04880-b5b5-11e8-9bdd-0f3a859b5564.png)

这是乱掉的布局：

![image](https://user-images.githubusercontent.com/13204332/45336345-b8dd0280-b5b5-11e8-9670-5703696a9854.png)

**Comment by youngjuning** [comment]
下面这个问题导致的，当我设置隐藏 Status 时，就会导致上面的问题
```js
<StatusBar backgroundColor={Theme.Color.primary} hidden animated />
```

**Comment by JoshLipan** [comment]
你有通过[onsizechange](https://github.com/jpush/aurora-imui/blob/master/ReactNative/docs/APIs.md#onsizechange)修改高度吗

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/45582789-b85fa700-b8e8-11e8-8799-3128170f5673.png)

**Comment by JoshLipan** [comment]
更新最新版本v0.11.1试下
