### ISSUE TITLE
Invoke virtual method 'void android.media.MediaPlayer.release()' on a null object reference

### ISSUE THREAD

**Issue by yuensunn** [jpush/aurora-imui#454]
### My environment:
- `react-native` version: 0.55.4
- `aurora-imui-react-native` version: ^0.10.10
- `react-navigation`: ^2.12.1
### 问题
第二次从chat screen 切换取另一个screen 就会出现这一个error （参考附上的gif）
![bug](https://media.giphy.com/media/3t9duqRgQGM0nmA8IL/giphy.gif)

**Comment by yuensunn** [comment]
我更新 aurora-imui-react-native  至 ^0.11.0 却遇到了这些问题 
我尝试了更新 react-native 至 0.57 还是一样
> Task :aurora-imui-react-native:compileDebugJavaWithJavac FAILED
node_modules\aurora-imui-react-native\ReactNative\android\src\main\java\cn\jiguang\imui\messagelist\viewmanager\ReactChatInputManager.java:59: error: package cn.jiguang.imui.chatinput.menu
does not exist
import cn.jiguang.imui.chatinput.menu.Menu;
                                     ^
node_modules\aurora-imui-react-native\ReactNative\android\src\main\java\cn\jiguang\imui\messagelist\viewmanager\ReactChatInputManager.java:776: error: cannot find symbol
                .setMenu(Menu.newBuilder()
                         ^
  symbol:   variable Menu
  location: class ReactChatInputManager
node_modules\aurora-imui-react-native\ReactNative\android\src\main\java\cn\jiguang\imui\messagelist\viewmanager\ReactChatInputManager.java:775: error: cannot find symbol
        mChatInput.getMenuManager()
                  ^
  symbol:   method getMenuManager()
  location: variable mChatInput of type ChatInputView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors

**Comment by JoshLipan** [comment]
更新最新版本v0.11.1
