### ISSUE TITLE
RCTAuroraIMUI.framework 编译了还是不对

### ISSUE THREAD

**Issue by SmileYXHP** [jpush/aurora-imui#457]
### My environment:

`react-native` version:0.57.0
`aurora-imui-react-native` version:^0.11.0
native version:9.4.1

<img width="400" alt="qq20180917-170904 2x" src="https://user-images.githubusercontent.com/20057920/45615083-1b466f00-ba9e-11e8-829d-5fda4639c340.png">

我已经编译过了，RCTAuroraIMUI.framework还是灰色

**Comment by SmileYXHP** [comment]
抱歉，是编译的时候就报错了：
ld: library not found for -lReact
这个怎么解决？是把它删除吗？

**Comment by huangminlinux** [comment]
先编译工程 target，确保 react 相关类库已经编译成功再 编译 RCTAuroraIMUI

**Comment by PokerXu** [comment]
> 抱歉，是编译的时候就报错了：
> ld: library not found for -lReact
> 这个怎么解决？是把它删除吗？

请问你解决这个问题了吗？

**Comment by cnpmge** [comment]
请问如何解决的？
