### ISSUE TITLE
android IMUI  怎么获取列表 =0 的消息  

### ISSUE THREAD

**Issue by HoCham-Lu** [jpush/aurora-imui#458]
### My environment:
android IMUI  怎么获取列表 =0 的消息  
文档没有哦

**Comment by HoCham-Lu** [comment]
也就是 空列表的时候 apater.size() =0 是聊天列表的消息  怎么获取里面的值呢？

**Comment by JoshLipan** [comment]
原生还是RN,要获取哪个值？
