### ISSUE TITLE
照相问题

### ISSUE THREAD

**Issue by chenzhenbo** [jpush/aurora-imui#459]
### My environment:
版本：
`react-native` version: 0.49
`aurora-imui-react-native` version: 0.11.0

问题1
机型：小米6
安卓版本：安卓8
问题描述：拍照在全屏模式下，直接退出

问题2
机型：iphone6s
版本：IOS10.1
问题描述：
a.切换到前置摄像头直接闪退
b.无法视频录像

**Comment by JoshLipan** [comment]
闪退log提供下

**Comment by chenzhenbo** [comment]
> 闪退log提供下

09-19 00:34:48.593 19299-19299/com.testrnimuiexample I/RCTMessageList: Scroll to bottom smoothly
09-19 00:34:48.605 19299-19299/com.testrnimuiexample I/PhotoViewHolder: send image succeed
09-19 00:34:48.613 19299-19299/com.testrnimuiexample I/PhotoViewHolder: send image succeed
09-19 00:34:48.622 19299-19299/com.testrnimuiexample I/PhotoViewHolder: send image succeed
09-19 00:34:48.639 19299-19305/com.testrnimuiexample I/zygote: Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
09-19 00:34:48.653 19299-19305/com.testrnimuiexample I/zygote: Do full code cache collection, code=252KB, data=180KB
    After code cache collection, code=192KB, data=120KB
09-19 00:34:48.686 19299-19299/com.testrnimuiexample I/PhotoViewHolder: send image succeed
09-19 00:34:48.696 19299-19299/com.testrnimuiexample I/PhotoViewHolder: send image succeed
09-19 00:34:48.706 19299-19299/com.testrnimuiexample I/PhotoViewHolder: send image succeed
09-19 00:34:50.825 19299-19299/com.testrnimuiexample E/ChatInputView: TextureView height: 0
09-19 00:34:50.835 19299-19299/com.testrnimuiexample I/RCTMessageList: Scroll to bottom smoothly
09-19 00:34:50.943 19299-19331/com.testrnimuiexample I/ReactNativeJS: onInputViewSizeChange height: 416 width: 360
09-19 00:34:51.001 19299-19299/com.testrnimuiexample D/ChatInputView: Opening camera
09-19 00:34:51.005 19299-19299/com.testrnimuiexample I/CameraManagerGlobal: Connecting to camera service
09-19 00:34:51.013 19299-19299/com.testrnimuiexample W/CameraManagerGlobal: [soar.cts] ignore the status update of camera: 2
    [soar.cts] ignore the status update of camera: 3
09-19 00:34:51.014 19299-19313/com.testrnimuiexample W/CameraManagerGlobal: ignore the torch status update of camera: 2
09-19 00:34:51.015 19299-19313/com.testrnimuiexample W/CameraManagerGlobal: ignore the torch status update of camera: 3
09-19 00:34:51.155 19299-19299/com.testrnimuiexample I/CameraManager: Using legacy camera HAL.
09-19 00:34:51.377 19299-19299/com.testrnimuiexample I/FeatureParser: can't find sagit.xml in assets/device_features/,it may be in /system/etc/device_features
09-19 00:34:51.417 19299-19305/com.testrnimuiexample I/zygote: Do partial code cache collection, code=252KB, data=175KB
09-19 00:34:51.418 19299-19305/com.testrnimuiexample I/zygote: After code cache collection, code=248KB, data=173KB
    Increasing code cache capacity to 1024KB
09-19 00:34:51.429 19299-19352/com.testrnimuiexample I/CameraDeviceState: Legacy camera service transitioning to state CONFIGURING
09-19 00:34:51.430 19299-19394/com.testrnimuiexample I/RequestThread-0: Configure outputs: 2 surfaces configured.
09-19 00:34:51.430 19299-19394/com.testrnimuiexample D/Camera: app passed NULL surface
09-19 00:34:51.434 19299-19394/com.testrnimuiexample I/RequestThread-0: configureOutputs - set take picture size to 4032x3016
09-19 00:34:51.453 19299-19352/com.testrnimuiexample I/CameraDeviceState: Legacy camera service transitioning to state IDLE
09-19 00:34:51.457 19299-19352/com.testrnimuiexample I/RequestQueue: Repeating capture request set.
09-19 00:34:51.464 19299-19299/com.testrnimuiexample I/PhotoViewHolder: send image succeed
09-19 00:34:51.465 19299-19394/com.testrnimuiexample W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
    Only received metering rectangles with weight 0.
    Only received metering rectangles with weight 0.
09-19 00:34:51.739 19299-19396/com.testrnimuiexample I/CameraDeviceState: Legacy camera service transitioning to state CAPTURING
09-19 00:34:53.009 19299-19331/com.testrnimuiexample I/ReactNativeJS: on full screen
09-19 00:34:53.061 19299-19299/com.testrnimuiexample D/ChatInputView: Texture size changed, Opening camera
09-19 00:34:53.118 19299-19299/com.testrnimuiexample I/CameraManager: Using legacy camera HAL.
09-19 00:34:53.131 19299-19353/com.testrnimuiexample E/Camera: Error 2
09-19 00:34:53.131 19299-19353/com.testrnimuiexample I/RequestThread-0: Flushing all pending requests.
09-19 00:34:53.131 19299-19353/com.testrnimuiexample I/RequestQueue: Repeating capture request cancelled.
09-19 00:34:53.132 19299-19353/com.testrnimuiexample W/RequestHolder: Capture failed for request: 0
09-19 00:34:53.132 19299-19353/com.testrnimuiexample I/CameraDeviceState: Legacy camera service transitioning to state ERROR
09-19 00:34:53.136 19299-19352/com.testrnimuiexample E/RequestQueue: cancel failed: no repeating request exists for request id: 0
09-19 00:34:53.203 19299-19426/com.testrnimuiexample E/BufferQueueProducer: [SurfaceTexture-1-19299-1] cancelBuffer: BufferQueue has been abandoned
09-19 00:34:53.205 19299-19426/com.testrnimuiexample I/chatty: uid=10281(u0_a281) Binder:19299_3 identical 5 lines
09-19 00:34:53.206 19299-19426/com.testrnimuiexample E/BufferQueueProducer: [SurfaceTexture-1-19299-1] cancelBuffer: BufferQueue has been abandoned
09-19 00:34:53.467 19299-19427/com.testrnimuiexample I/CameraDeviceState: Legacy camera service transitioning to state CONFIGURING
09-19 00:34:53.468 19299-19473/com.testrnimuiexample I/RequestThread-0: Configure outputs: 2 surfaces configured.
09-19 00:34:53.468 19299-19473/com.testrnimuiexample D/Camera: app passed NULL surface
09-19 00:34:53.471 19299-19473/com.testrnimuiexample I/RequestThread-0: configureOutputs - set take picture size to 4032x3016
09-19 00:34:53.489 19299-19427/com.testrnimuiexample I/CameraDeviceState: Legacy camera service transitioning to state IDLE
09-19 00:34:53.491 19299-19427/com.testrnimuiexample I/RequestQueue: Repeating capture request set.
09-19 00:34:53.495 19299-19473/com.testrnimuiexample W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
    Only received metering rectangles with weight 0.
    Only received metering rectangles with weight 0.
09-19 00:34:53.831 19299-19474/com.testrnimuiexample I/CameraDeviceState: Legacy camera service transitioning to state CAPTURING
09-19 00:34:55.405 19299-19427/com.testrnimuiexample I/RequestQueue: Repeating capture request cancelled.
09-19 00:34:55.412 19299-19473/com.testrnimuiexample W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
09-19 00:34:55.413 19299-19473/com.testrnimuiexample W/LegacyRequestMapper: Only received metering rectangles with weight 0.
    Only received metering rectangles with weight 0.
09-19 00:34:55.465 19299-19428/com.testrnimuiexample D/LegacyFocusStateMapper: onAutoFocusMoving - ignoring move callbacks from old af run1
09-19 00:34:55.466 19299-19473/com.testrnimuiexample W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
    Only received metering rectangles with weight 0.
09-19 00:34:55.467 19299-19473/com.testrnimuiexample W/LegacyRequestMapper: Only received metering rectangles with weight 0.
09-19 00:34:55.614 19299-19428/com.testrnimuiexample I/RequestThread-0: Received jpeg.
09-19 00:34:55.615 19299-19428/com.testrnimuiexample I/RequestThread-0: Producing jpeg buffer...
09-19 00:34:55.655 19299-19473/com.testrnimuiexample I/CameraDeviceState: Legacy camera service transitioning to state IDLE
09-19 00:34:56.508 19299-19427/com.testrnimuiexample I/CameraNew: Saved capture into /data/user/0/com.testrnimuiexample/files/photo/2018-09-19-003455.jpg
09-19 00:34:56.512 19299-19312/com.testrnimuiexample W/MessageQueue: Handler (android.graphics.SurfaceTexture$1) {fb6a78a} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.graphics.SurfaceTexture$1) {fb6a78a} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:551)
        at android.os.Handler.enqueueMessage(Handler.java:661)
        at android.os.Handler.sendMessageAtTime(Handler.java:630)
        at android.os.Handler.sendMessageDelayed(Handler.java:600)
        at android.os.Handler.sendEmptyMessageDelayed(Handler.java:564)
        at android.os.Handler.sendEmptyMessage(Handler.java:549)
        at android.graphics.SurfaceTexture.postEventFromNative(SurfaceTexture.java:382)
09-19 00:34:56.514 19299-19331/com.testrnimuiexample I/ReactNativeJS: media {"size":3154708,"height":4032,"width":3016,"mediaPath":"/data/user/0/com.testrnimuiexample/files/photo/2018-09-19-003455.jpg"}
09-19 00:34:56.515 19299-19312/com.testrnimuiexample E/BufferQueueProducer: [SurfaceTexture-1-19299-2] dequeueBuffer: BufferQueue has been abandoned
09-19 00:34:56.515 19299-19332/com.testrnimuiexample D/AuroraIMUIModule: configure message: { NativeMap: {"mediaPath":"/data/user/0/com.testrnimuiexample/files/photo/2018-09-19-003455.jpg","msgType":"image","fromUser":{"avatarPath":"images","displayName":"replace your nickname","userId":""},"timeString":"0:34","isOutgoing":true,"status":"send_succeed","msgId":"73"} }
    fromUser: {"userId":"","displayName":"replace your nickname","avatarPath":"images"}
09-19 00:34:56.573 19299-19312/com.testrnimuiexample E/BufferQueueProducer: [SurfaceTexture-1-19299-2] cancelBuffer: BufferQueue has been abandoned
09-19 00:34:56.577 19299-19312/com.testrnimuiexample I/chatty: uid=10281(u0_a281) Binder:19299_1 identical 4 lines
09-19 00:34:56.578 19299-19312/com.testrnimuiexample E/BufferQueueProducer: [SurfaceTexture-1-19299-2] cancelBuffer: BufferQueue has been abandoned

**Comment by JoshLipan** [comment]
你是自己集成有的原因，还是demo测试出的问题
从这个log来看最后是正常发出消息了，并没有定位闪退原因
可以用adb抓取原生log：adb logcat -v time ->a.log

**Comment by chenzhenbo** [comment]
[a.log](https://github.com/jpush/aurora-imui/files/2395135/a.log)
自己集成和你的demo都试过，全屏拍照就卡住。

**Comment by JoshLipan** [comment]
更新最新版本v0.11.1

**Comment by laienliang** [comment]
更新到了0.11.1还是出错
sending message to a Handler on a dead thread
