### ISSUE TITLE
安卓表情按钮和发送按钮点击没有反应

### ISSUE THREAD

**Issue by SmileYXHP** [jpush/aurora-imui#461]
### My environment:
if react-native 
- `react-native` version: 0.44.3
- `aurora-imui-react-native` version:^0.11.0

1.如上图，做的分段控制器，安卓一进入页面就自动跳到登录页面，iOS不会；
2.安卓点击输入框，呼出键盘，能正常呼出。但是我一旦点击发送按钮或者表情按钮，再点击输入框，就不能呼出键盘，而且发送按钮或者表情按钮没有出现相应效果；
3.输入框能改变背景色吗？安卓设置底部背景色不起作用？安卓下面有一块白色
4.安卓机型：vivo Y56  系统：6.0.1

**Comment by JoshLipan** [comment]
1.图片没看到，imui就是单独的组件，页面切换逻辑需要自己检查控制下
2.你是自己集成中出现的问题吗，官方demo测试有没有这个问题
3.背景色可以通过[chatInputBackgroupColor](https://github.com/jpush/aurora-imui/blob/master/ReactNative/docs/APIs_zh.md#chatinputbackgroupcolor)设置

**Comment by SmileYXHP** [comment]
1.给的文档说的（status 必须为以下四个值之一: "send_succeed", "send_failed", "send_going", "download_failed"，如果没有定义这个属性， 默认值是 "send_succeed".）
eventMessage = {  // event message
    msgId: "msgid",
    msgType: "event",
    text: "the event text"
}
我传的eventMessage格式就是如上格式，在iOS上面可以，但是在安卓上面报错，报错位置代码在AuroraIMUIModule.java里面的
 private RCTMessage configMessage(ReadableMap message) {
        Log.d("AuroraIMUIModule", "configure message: " + message);
        RCTMessage rctMsg = new RCTMessage(message.getString(RCTMessage.MSG_ID),
                message.getString(RCTMessage.STATUS), message.getString(RCTMessage.MSG_TYPE),
                message.getBoolean(RCTMessage.IS_OUTGOING));
这是否表示安卓不管传任何类型message都必须传全部键值？（目前我测试过，是必须传全部）

2.背景色我用chatInputBackgroupColor设置过了，只在iOS上面有效果，安卓没有效果，而且这个属性是设置整个输入那块（输入框+功能区）View的背景色，并不是我想要的只是单独设置输入框的背景色；

3.我用的你们提供的demo,文档说：
// 如果 left/right/bottom 没有提供则不会显示，直接隐藏。
customLayoutItems={{
            left: ['voice'],
            right: ['send']
		}} 
，但安卓跑起来bottom那块没有隐藏，如下图：
![im-3](https://user-images.githubusercontent.com/20057920/45873088-2feb7580-bdc4-11e8-86cc-1f5e02f1160c.jpg)
![im-4](https://user-images.githubusercontent.com/20057920/45873107-3974dd80-bdc4-11e8-9c7e-22482f17c34e.jpg)
而且我如果把表情和发送功能区放在右边，点击没有效果；
但是放在底部，点击就有相应效果了；


4.如果我用分段选项，安卓一进入界面就自动跳到，聊天界面，安卓如下图：
![im-2](https://user-images.githubusercontent.com/20057920/45873542-5362f000-bdc5-11e8-992b-bc2b8f07b463.jpg)

iOS不会，iOS如下图：
![im-1](https://user-images.githubusercontent.com/20057920/45873673-98872200-bdc5-11e8-9d25-12d00b680586.jpg)

**Comment by JoshLipan** [comment]
确实有这个问题，更新最新版本v0.11.1

**Comment by JoshLipan** [comment]
背景色是之前两个平台不统一导致android设置失败，现在统一用chatInputBackgrounpColor设置
