### ISSUE TITLE
哪位大哥知道AndroidStudio怎么导入，才能正常运行么？

### ISSUE THREAD

**Issue by gaohequan** [jpush/aurora-imui#462]
### My environment:

Mac OS 
Android Studio 3.1.3
jdk1.8

**Comment by JoshLipan** [comment]
原生直接导入[sample](https://github.com/jpush/aurora-imui/tree/master/Android/sample)，RN导入[sample/android](https://github.com/jpush/aurora-imui/tree/master/ReactNative/sample/android)

**Comment by gaohequan** [comment]
@JoshLipan   怎么导都不行 昨天下午折腾到现在 莫名其妙的好的。。。
改了setting.gradle 中include放在了第一行
加了local.properties文件
删除了build.gradle中的productFlavors 
不知道和上面的操作有没有关系。总之解决了 3Q
