### ISSUE TITLE
安卓崩溃和键盘不消失

### ISSUE THREAD

**Issue by SmileYXHP** [jpush/aurora-imui#463]
### My environment:
if react-native 
- `react-native` version: 0.44.3
- `aurora-imui-react-native` version: ^0.11.0

1.安卓经常奔溃，报错位置如下图：
<img width="984" alt="glide" src="https://user-images.githubusercontent.com/20057920/45923905-0564fe00-bf25-11e8-956f-775fd12f3c16.png">

2.安卓怎么让键盘消失，如下设置了，键盘也没有消失：
if (Platform.OS === "android") {
            console.log("==========外部点击空白区域，键盘消失========")
            this.refs["ChatInput"].showMenu(false);//**这里true和false都试了**
            this.setState({
              messageListLayout: { flex: 1, width: window.width, margin: 0 },
              inputViewLayout: { width: theme.screenWidth, height: 60, },
            });
            AuroraIController.hidenFeatureView(true);
            this.forceUpdate();
          }

**Comment by JoshLipan** [comment]
1.看错误信息是你在当前界面销毁了还继续调用UI相关API导致的
2.键盘是否展是底层逻辑，上层暂没有提供接口处理

**Comment by SmileYXHP** [comment]
1.我看了RN的源码，用的 this.refs["ChatInput"].closeSoftInput();消失键盘，但是是tab切换，就有问题，如图：
<img width="429" alt="scroll" src="https://user-images.githubusercontent.com/20057920/46000460-35ee9880-c0db-11e8-8447-ab89638ce58f.png">

布局是ScrollView包裹的课程介绍和讨论区两个子view，
操作步骤是：我进入这个页面，在讨论区未呼出键盘的时候，点击tab切换，一切正常；
但是如果我点到讨论区，把键盘呼出来，在点击tab切换到课程介绍，就变成上图的情况。打印ScrollView里面onScroll方法显示的是：先x滑到0（这是正确的，就应该在这里终止了），但然后自动滑到屏幕宽度了（就是这里莫名其妙，程序都木有调任何滑动了，却自己滑动了，找不到原因）

**Comment by SmileYXHP** [comment]
请看一下#461
