### ISSUE TITLE
图片语音

### ISSUE THREAD

**Issue by Br1125** [jpush/aurora-imui#467]
### My environment:

android
![85iabve 1 34ea_v0mcyy0](https://user-images.githubusercontent.com/23623206/46007197-01370d00-c0ec-11e8-8431-304ca3b73176.png)

  compile 'cn.jiguang.sdk:jmessage:2.7.0'
    // 此处以JMessage 2.7.0 版本为例。极光群组聊天

//    极光IM
    compile 'cn.jiguang.imui:messagelist:0.7.4'
    compile 'cn.jiguang.imui:chatinput:0.9.0'

**Comment by JoshLipan** [comment]
[社区](https://community.jiguang.cn/t/topic/29773)回答你了，关闭
