### ISSUE TITLE
相机全屏时底部状态栏挡住了视图

### ISSUE THREAD

**Issue by 1111mp** [jpush/aurora-imui#469]
我用的调试机是小米的全面屏手机 然后在相机全屏的时候出现了这个问题
![_20180926111613](https://user-images.githubusercontent.com/31227919/46055314-0775c980-c17e-11e8-9186-16484a747ac4.png)
底部视图被挡住了 我尝试了[https://blog.csdn.net/Alice_1_1/article/details/52385830](url)这种方法 但是依然解决不了这个问题  请问能帮忙解答一下吗

**Comment by 1111mp** [comment]
你的意思是去掉底部状态栏？

**Comment by 1111mp** [comment]
![image](https://user-images.githubusercontent.com/31227919/46055933-d8ad2280-c180-11e8-9622-6dd6f3dfbc9b.png)
 这样还是会出现这个问题 我用了git上面的代码跑起来依旧有这个问题

**Comment by 1111mp** [comment]
onFullScreen = () => {
    // console.warn("on full screen")
    this.setState({
      messageListLayout: { flex: 0, width: 0, height: 0 },
      inputViewLayout: { flex: 1, width: window.width, height: window.height },
      navigationBar: { height: 0 }
    })
  }

**Comment by 1111mp** [comment]
希望大牛能教一下 谢谢啊

**Comment by JoshLipan** [comment]
看下#399

**Comment by JoshLipan** [comment]
更新最新版本v0.11.1

**Comment by YanmaY** [comment]
全屏，然后点击物理返回按钮或者手机导航栏上的返回按钮，这个时候导航栏依旧会挡住视图
![1](https://user-images.githubusercontent.com/7043862/53074501-e3989300-3525-11e9-9925-db57cf42db13.png)
![2](https://user-images.githubusercontent.com/7043862/53074503-e72c1a00-3525-11e9-9daa-fca21412922e.png)
![3](https://user-images.githubusercontent.com/7043862/53074506-e98e7400-3525-11e9-8b79-5eef024350c9.png)
![4](https://user-images.githubusercontent.com/7043862/53074508-ebf0ce00-3525-11e9-9ed6-a7b2849e51cf.png)
