### ISSUE TITLE
昵称怎么显示出来?  iOS Object-c

### ISSUE THREAD

**Issue by HHuiHao** [jpush/aurora-imui#472]
displayName有值
![image](https://user-images.githubusercontent.com/8486113/46189555-bd2d4d80-c321-11e8-95e4-72d5eb4f7ea0.png)

**Comment by HuminiOS** [comment]
有一个全局配置项 IMUIMessageCellLayout.isNeedShowOutGoingName 需要设为 true。

**Comment by HHuiHao** [comment]
好的， 谢谢
