### ISSUE TITLE
安卓多行输入，收起键盘，底部留白

### ISSUE THREAD

**Issue by SmileYXHP** [jpush/aurora-imui#473]
### My environment:
- `react-native` version: 0.44.3
- `aurora-imui-react-native` version: ^0.11.0

1.安卓，多行输入，收起键盘，底部留白；
初始图：
![less](https://user-images.githubusercontent.com/20057920/46191959-fff42300-c32b-11e8-9423-5768162c2f54.jpg)

多行输入后，底部l留白：
![more](https://user-images.githubusercontent.com/20057920/46192086-86106980-c32c-11e8-8e55-fbd5543195ca.jpg)

2.iOS升级xcode到10，报错：
error: unexpected duplicate task: CompileXIB /Users/mac/Desktop/chamiSVN/app/trunk/client/ChaMi/node_modules/aurora-imui-react-native/ReactNative/ios/RCTAuroraIMUI/RCTInputView.xib (in target 'RCTAuroraIMUI')
不知道是不是因为我RN版本太低了

**Comment by JoshLipan** [comment]
更新到v0.12.2

**Comment by SmileYXHP** [comment]
更新版本后，iOS报错RCTMessageModel，我全部改成IMUIMessageModel了
