### ISSUE TITLE
react native  接收到消息 怎么设置 在左边 显示

### ISSUE THREAD

**Issue by loss99** [jpush/aurora-imui#474]
react native  接收到消息 怎么设置 在左边 显示 let message = {}
我 拿到 历史 记录怎么 设置 在 左边显示  收到的消息 右边 显示 发送的消息 是 那个属性  我没找到 这个设置

        message.msgId=WebIM.conn.getUniqueId();
        message.isOutgoing = true;
        message.timeString =  TimeUtil.currentTime();

        let user = {
            userId: this.conversationId,
            displayName: '',
            avatarPath: ""
        };

        message.fromUser = user;

        for (let index in messageData) {
            if (messageData[index].to != this.username) {
                message.status = "send_succeed"
            }else {
                message.status = "receive"
            }
            message.timeString=TimeUtil.formatChatTime(parseInt(messageData[index].time));
            message.fromUser.displayName =messageData[index].to;
                message.msgType = messageData[index].msgType;
            message.text=messageData[index].data
            AuroraIController.appendMessages([message])
            console.log('历史消息',message);
        }

        AuroraIController.scrollToBottom(true)

**Comment by JoshLipan** [comment]
message .isOutgoing = false
