### ISSUE TITLE
拍照时启用前置摄像头界面被拉伸并且模糊

### ISSUE THREAD

**Issue by 1111mp** [jpush/aurora-imui#475]
![192660113339189691](https://user-images.githubusercontent.com/31227919/46244454-a1a17000-c411-11e8-91b9-847ddd2be8d2.jpg)
 请问能否把改变气泡的背景颜色的设置暴露出来呢谢谢啊
在安卓中不能通过右滑手势返回上个页面，我不知道是什么原因造成的
如果我需要改气泡的背景颜色我应该怎么做呢
因为我是做前端的 对原生的不是很懂 所以就会有很多问题 希望你见谅 
谢谢

**Comment by JoshLipan** [comment]
参考 #412
