### ISSUE TITLE
RCTMessageList找不到的问题

### ISSUE THREAD

**Issue by spidersq** [jpush/aurora-imui#476]
### My environment:
- OS:  win10 
- `react-native` version:0.57.0
- `aurora-imui-react-native` version:0.12.3

Invariant Violation: Invariant Violation: requireNativeComponent: "RCTMessageList" was not found in the UIManager.

This error is located at:
    in RCTMessageList (at messagelist.android.js:80)
    in MessageList (at Chat.js:505)
    in RCTView (at View.js:44)
    in TestRNIMUI (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:574)
    in RCTView (at View.js:44)
    in AnimatedComponent (at StackViewCard.js:12)
    in Card (at createPointerEventsContainer.js:28)
    in Container (at StackViewLayout.js:612)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:63)
    in RCTView (at View.js:44)
    in Transitioner (at StackView.js:21)
    in StackView (at createNavigator.js:59)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at App.js:8)
    in App (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

**Comment by spidersq** [comment]
@JoshLipan 完全按照安装配置来的，网上查到有些原生组件也出现这个问题，貌似是说新版本就会有这个问题，所以在这里提了个问题。

**Comment by spidersq** [comment]
已找到问题所在，并不是imui本身的问题，是受到其他插件的影响。

**Comment by Lsgsunny** [comment]
@spidersq 我也遇到这样的问题，请问你是怎么解决的？

**Comment by zmGitHub** [comment]
+1

**Comment by Alphia** [comment]
@spidersq 请问怎么解决的？
