### ISSUE TITLE
拍照发图片

### ISSUE THREAD

**Issue by Br1125** [jpush/aurora-imui#479]
### My environment:

Android
    compile 'cn.jiguang.imui:messagelist:0.7.4'
    compile 'cn.jiguang.imui:chatinput:0.9.1'

拍照时没有明显的动画或提示，用户不知道是否完成拍照，可能会连续发几张相同的图片。

**Comment by mylovetop** [comment]
和你一样版本，我这拍一次 出现2张图片

**Comment by JoshLipan** [comment]
@mylovetop 两张照片是同一个资源吗，定位下是拍了两张，还是一张照片被发了两次

**Comment by mylovetop** [comment]
不是同一资源， 拍了2张不同名称的图片

**Comment by peijinliang** [comment]
这个怎么解决的，问一下？

**Comment by Br1125** [comment]
> 这个怎么解决的，问一下？

**Comment by Br1125** [comment]
@peijinliang 我是改了UI,然后调用自带的相机。

**Comment by peijinliang** [comment]
好的，谢谢
