### ISSUE TITLE
获取新的数据时 怎么禁止滚动到底部。。

### ISSUE THREAD

**Issue by gaoxuan-haxibiao** [jpush/aurora-imui#480]
### My environment:

当页面重新获取数据时   就会滚动到底部。

在处理下拉加载历史记录时，获取新的消息时体验很不友好。

AuroraIMUIController.scrollToBottom(false)   不起作用

**Comment by JoshLipan** [comment]
scrollToBottom是个行为，不是配置，不想滚动到底部不调用就行

**Comment by gaoxuan-haxibiao** [comment]
没有调用

因为每次有新的数据时    都会重新 appendMessages([message])

所以就跟第一次进入聊天页面一样 从顶部滚动到底部。

**Comment by JoshLipan** [comment]
appendMessages滚动到底部这是默认设置，没提供配置，不过你可以通过修改插件实现：
找到[插件对应位置](https://github.com/jpush/aurora-imui/blob/master/ReactNative/android/src/main/java/cn/jiguang/imui/messagelist/viewmanager/ReactMsgListManager.java#L348)，修改为
```
mAdapter.addToStart(rctMessage, false);
```

**Comment by gaoxuan-haxibiao** [comment]
谢谢 

我想提个建议 

初始化列表时可以直接定位到底部，而不是先在顶部再滚动到底部
