### ISSUE TITLE
Android端  onPullToRefresh 只能触发一次

### ISSUE THREAD

**Issue by gaoxuan-haxibiao** [jpush/aurora-imui#481]
- `react-native` version:0.56.0
- `aurora-imui-react-native` version:^0.11.0

触发一次后好像就被锁死了。。

小圆圈一直在转，重新下拉没有任何反应。
![image](https://user-images.githubusercontent.com/36940267/46722945-44c37680-cca9-11e8-8907-4e357fc80160.png)

**Comment by JoshLipan** [comment]
可以看下刷新回调触发了没

**Comment by gaoxuan-haxibiao** [comment]
触发一次就不触发了   console只打印一次信息

**Comment by JoshLipan** [comment]
更新[最新版本](https://github.com/jpush/aurora-imui/releases/tag/0.13.0)重试

**Comment by SanChunAndrroid** [comment]
更新版本也一样

**Comment by applewoainiqwe** [comment]
if (Platform.OS === 'android') {
        this.refs["MessageList"].refreshComplete()
      }
看看这句在什么地方
