### ISSUE TITLE
react-native iOS 版在首次push聊天界面时卡顿

### ISSUE THREAD

**Issue by Itangjie** [jpush/aurora-imui#486]
### My environment:

`react-native` version:0.49
 `aurora-imui-react-native` version:

iOS 版在首次push聊天界面时，会因为ChatInput的emoji键盘造成界面卡顿，请问该怎么优化？

**Comment by HuminiOS** [comment]
emoji 的 只有在弹出出的时候才会渲染，直接显示  chatinput view 不会渲染，应该是不是 emoji 造成的。

**Comment by huangminlinux** [comment]
你用的是这个库？

**Comment by Itangjie** [comment]
> 你用的是这个库？

不好意思，我看了下用的那个库是fork的这个项目，它版本有点老了，和这边好多不一样
