### ISSUE TITLE
IOS Only : UITextView Not show init, But the scroll bar list will display.

### ISSUE THREAD

**Issue by Base2526** [jpush/aurora-imui#489]
### My environment:

https://user-images.githubusercontent.com/900211/47206827-d28f1800-d3b3-11e8-969c-8c8ebb6e6b9f.png

i check 
https://github.com/jpush/aurora-imui/blob/4e93d76e32dbdbb9e6bf846bfaca7beb0ced26f5/iOS/IMUIInputView/Controllers/IMUICustomInputView.swift

Call Some times, Not every time
// 该接口提供给 React Native 用于处理 第三库（react-navigation 或 react-native-router-flux ）可能导致的布局问题。
  @objc public func layoutInputView() {
      self.fitTextViewSize(self.inputTextView)
  }

Solutions
Thx.

**Comment by HuminiOS** [comment]
Do you have this problem using [demo](https://github.com/jpush/aurora-imui/tree/4e93d76e32dbdbb9e6bf846bfaca7beb0ced26f5/iOS/sample)?

**Comment by Base2526** [comment]
Thanks for the reply.
yes i using follow https://github.com/jpush/aurora-imui/tree/4e93d76e32dbdbb9e6bf846bfaca7beb0ced26f5/ReactNative/sample/ios

"aurora-imui-react-native": "^0.11.1",

but i set Color separation
Thx

**Comment by huangminlinux** [comment]
You can t update to `aurora-imui-react-native@0.12.4` . It's ok for me.

**Comment by Base2526** [comment]
@huangminlinux  Thanks for the reply.
i test run simulator & device but not work
![44296801_324357658340040_8143739523474391040_n](https://user-images.githubusercontent.com/900211/47224626-2d416780-d3e6-11e8-9f7f-0571dcaa1dba.jpg)

Thx.

**Comment by huangminlinux** [comment]
Could you provide the following information? I have to make a demo for test.
- react-native version
- which route lib do you use?  (and provide route config)
- the chatInputView style.

**Comment by Base2526** [comment]
@huangminlinux Thanks for the reply

Demo for test
http://139.59.228.56/db/ExSNavigator.zip

Thx.

**Comment by Base2526** [comment]
Thanks for the reply

Demo for test
http://139.59.228.56/db/ExSNavigator.zip

Thx.

**Comment by Base2526** [comment]
Video Test : http://139.59.228.56/db/aurora_imui_error.mov

**Comment by huangminlinux** [comment]
If you want to add bottom item in chatInputview.
You should set the [initHeight](https://github.com/jpush/aurora-imui/blob/master/ReactNative/sample/App.js#L139) to 86

**Comment by Base2526** [comment]
@huangminlinux Thanks for the reply 
Work for me thanks very much.
