### ISSUE TITLE
发送图片时崩溃

### ISSUE THREAD

**Issue by istarvip** [jpush/aurora-imui#491]

**Comment by istarvip** [comment]
Android的 最新 sdk：
![image](https://user-images.githubusercontent.com/12675437/47347810-9ecd2e80-d6e2-11e8-8a4e-8dbea9ee148f.png)

录音两次的图标是干嘛的，点击也没有效果，从相册发送图片没效果，自定义菜单时，可以监听该菜单的子view的点击事件吗。

**Comment by JoshLipan** [comment]
录音两次是指？你可以直接设置自定义菜单点击事件，并不冲突

**Comment by istarvip** [comment]
> 录音两次是指？你可以直接设置自定义菜单点击事件，并不冲突

![image](https://user-images.githubusercontent.com/12675437/47400315-3b3d1280-d76f-11e8-99db-f5e857739c70.png)
这两侧的图标（之前打错字了）是干嘛的，点击也没效果，有方法可以去掉吗，自定义菜单的子菜单的点击事件怎么定义，在下面的截图中定义还是自己写一个点击监听事件： 
![image](https://user-images.githubusercontent.com/12675437/47400575-51979e00-d770-11e8-9e5a-103f57a3aafd.png)

**Comment by JoshLipan** [comment]
长按录音后左移试听，右移删除。
菜单项MenuItem点击事件对应onMenuItemClick，菜单功能MenuFeature自行定义

**Comment by istarvip** [comment]
那我发送图片的时候（可能点太快）有时候会崩溃，是什么原因，代码在最上面，OnePlus5T  8.1 的设备

**Comment by JoshLipan** [comment]
是拍照发送奔溃吗，是偶现还是必现？
能否描述复现步骤，然后提供下完整的log，我这边尝试重现下

**Comment by istarvip** [comment]
刚刚频繁下拉获取消息列表时发生了空指针异常。
![image](https://user-images.githubusercontent.com/12675437/47493010-dd98eb00-d880-11e8-96a4-e4d104d1878b.png)

**Comment by JoshLipan** [comment]
更新[最新版本](https://github.com/jpush/aurora-imui/releases/tag/0.13.0)
