### ISSUE TITLE
自定义消息（我按照教程步骤走的）

### ISSUE THREAD

**Issue by Chenshibiao** [jpush/aurora-imui#493]
### My environment:
        MsgListAdapter.HoldersConfig holdersConfig = new MsgListAdapter.HoldersConfig();
        holdersConfig.setSenderTxtMsg(MyCustomHolder.class, R.layout.custom_message);
        holdersConfig.setReceiverTxtMsg( MyCustomHolder.class, R.layout.custom_message);
        holdersConfig.setReceiveCustomMsg( MyCustomHolder.class, R.layout.custom_message);
        holdersConfig.setSendCustomMsg(MyCustomHolder.class, R.layout.custom_message);

这里setSenderTxtMsg（）第一个参数一直都报错，类型不匹配，这是我的自定义Holder。

public class MyCustomHolder<CustomMessage extends IMessage>
        extends BaseMessageViewHolder<CustomMessage>
        implements MsgListAdapter.DefaultMessageViewHolder {

    @Override
    public void onBind(CustomMessage customMessage) {

    }

    public MyCustomHolder(View itemView) {
        super(itemView);
    }

    @Override
    public void applyStyle(MessageListStyle style) {

    }

请问该怎么解决，是我操作出问题了吗，请告知，谢谢大佬分享。

**Comment by china-coder** [comment]
报错内容贴上来
