### ISSUE TITLE
Android 键盘问题

### ISSUE THREAD

**Issue by JoanBoat** [jpush/aurora-imui#496]
魅族pro6 安卓7.1  vivo x7 安卓5.1无法收起  
![06412797269ad3fdfd8d156c22207631](https://user-images.githubusercontent.com/25084399/47700791-a6488680-dc52-11e8-8f55-2a3e72a0eb76.jpg)
![2b59d3b83a5eeda0341a5b4bcacf392e](https://user-images.githubusercontent.com/25084399/47700792-a9437700-dc52-11e8-85dc-f4ac0f92b0cd.jpg)

**Comment by JoshLipan** [comment]
你的操作流程是什么？直接在键盘弹起时finish掉页面？
