### ISSUE TITLE
.DS_Store文件被添加进git里了

### ISSUE THREAD

**Issue by czvn** [jpush/aurora-imui#5]
明明gitIgnore里配置了忽略.DS_Store，但在Android/imui/src/main/java/cn/jiguang/imui/messages/下还是发现了有这个文件的存在

**Comment by KenChoi1992** [comment]
@czvn OK, 现在删掉了。

**Comment by czvn** [comment]
@KenChoi1992 好的

**Comment by czvn** [comment]
@KenChoi1992 不止这一个目录有，我PR过来的那次Commit里显示有14个

**Comment by KenChoi1992** [comment]
@czvn 合了，谢谢
