### ISSUE TITLE
ImageLoader

### ISSUE THREAD

**Issue by kangshaopeng** [jpush/aurora-imui#50]
Android中ImageLoader接口中只有头像的方法能用，图片消息的方法不起作用（PhotoViewHolder中好像只设置了头像的回调方法，没设置图片消息的）

**Comment by KenChoi1992** [comment]
@kangshaopeng 感谢提供反馈，确实没有提供图片回调，下个版本修复。

**Comment by KenChoi1992** [comment]
@kangshaopeng 0.4.0 已经修复了
