### ISSUE TITLE
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.

### ISSUE THREAD

**Issue by youngjuning** [jpush/aurora-imui#500]
是否考虑升级 Gradle 配置？？

![image](https://user-images.githubusercontent.com/13204332/47874581-29cec700-de4f-11e8-8f14-2a81e2630c11.png)

**Comment by JoshLipan** [comment]
直接 compile 替换成 api 就可以

**Comment by youngjuning** [comment]
手动改 node_modules 吗？

**Comment by JoshLipan** [comment]
可以，不过这个对编译没有影响吧，后续我们会升级

**Comment by youngjuning** [comment]
https://github.com/oblador/react-native-vector-icons/tree/master/android 影响就是打包会很慢，包体积会因为 android support 版本不一致变大。0.57.* 提供了根配置，你可以参考这个库和 https://github.com/master-atul/react-native-exception-handler/blob/master/android/build.gradle

**Comment by youngjuning** [comment]
@JoshLipan 请尽快修改吧，哥们，我排查了我用的10几个原生库，绝大部分都升级到适配 0.57.* 了

**Comment by JoshLipan** [comment]
[最新版本](https://github.com/jpush/aurora-imui/releases/tag/0.13.0)已适配新 gradle 语法
