### ISSUE TITLE
不添加混淆有什么影响吗，我去掉之后也没有报任何错

### ISSUE THREAD

**Issue by youngjuning** [jpush/aurora-imui#505]
![image](https://user-images.githubusercontent.com/13204332/47979670-3711dd00-e0ff-11e8-9153-7e9fb5e4c8c6.png)

**Comment by youngjuning** [comment]
且，apk 包减小了 50kb

**Comment by JoshLipan** [comment]
参考 #124

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/47980035-c8358380-e100-11e8-9bdb-ad7c2f2c51df.png)
也就是说只保持这两个就可以，文档里是忽略了所有 imui
