### ISSUE TITLE
Sender的頭像距離氣泡和Receiver不一致 => 如何調整頭像與氣泡間的距離

### ISSUE THREAD

**Issue by JLinKuo** [jpush/aurora-imui#508]
### My environment:

- Android Studio 3.2.1

如題，查詢了一下，似乎沒人提出這類的問題，麻煩了，感恩

**Comment by JoshLipan** [comment]
不一样吗？能否截图看下你那边的效果

**Comment by JLinKuo** [comment]
![for_imui](https://user-images.githubusercontent.com/21345791/48172845-5184ca00-e33c-11e8-8e0c-880c5dbc6a44.jpg

@JoshLipan 麻煩您看一下嚕，感恩 ：）

**Comment by JoshLipan** [comment]
你是替换了气泡背景吗，.9图的左右是不是一致的，这像是右边有多余的留边导致的

**Comment by JLinKuo** [comment]
貼上xml檔
 activity中引用
<cn.jiguang.imui.messages.MessageList
            android:id="@+id/msg_list"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:avatarHeight="60dp"
            app:avatarRadius="33dp"
            app:avatarWidth="60dp"
            app:bubbleMaxWidth="0.70"
            app:dateTextColor="#b5aeae"
            app:dateTextSize="12.3sp"
            app:receiveBubbleDrawable="@drawable/aurora_sender_receiver_bubble_shape"
            app:receiveBubbleColor="@color/white"
            app:receiveBubblePaddingBottom="10.3dp"
            app:receiveBubblePaddingLeft="10dp"
            app:receiveBubblePaddingRight="10dp"
            app:receiveBubblePaddingTop="10.7dp"
            app:receiveTextColor="#6c6565"
            app:receiveTextSize="14.3sp"
            app:sendBubbleDrawable="@drawable/aurora_sender_receiver_bubble_shape"
            app:sendBubbleColor="@color/white"
            app:sendBubblePaddingBottom="10.3dp"
            app:sendBubblePaddingLeft="10dp"
            app:sendBubblePaddingRight="10dp"
            app:sendBubblePaddingTop="10.7dp"
            app:sendTextColor="#6c6565"
            app:sendTextSize="14.3sp"
            app:showReceiverDisplayName="HIDE"
            app:showSenderDisplayName="HIDE" />

aurora_sender_receiver_bubble_shape.xml檔

<shape  xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <solid android:color="@android:color/white"/>
    <corners android:radius="1.7dp" />
</shape >

**Comment by JLinKuo** [comment]
aurora_sender_receiver_bubble_shape.xml檔
<shape  xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">

    <solid android:color="@android:color/white"/>

    <corners android:radius="1.7dp" />

</shape >

**Comment by JLinKuo** [comment]
@JoshLipan 我是有換氣泡的背景圖，但其實沒換之前就如此了，而我以上附上我的xml檔，請您協助看一下是否有設定不當之處，最後感恩您的回覆喔 ：）

**Comment by JoshLipan** [comment]
左右确实存在 3dp 误差，下个版本提供 api 调整，目前只能通过修改源码[去除margin](https://github.com/jpush/aurora-imui/blob/master/Android/messagelist/src/main/res/layout/item_send_text.xml#L58)实现

**Comment by JLinKuo** [comment]
萬般感恩您的回覆

**Comment by JoshLipan** [comment]
cn.jiguang.imui:messagelist:0.8.0 修正了消息气泡距离头像不一致性
