### ISSUE TITLE
语音发送与播放问题

### ISSUE THREAD

**Issue by spidersq** [jpush/aurora-imui#509]
- `react-native` version:0.57.0
- `aurora-imui-react-native` version:0.12.5

语音这块发现的问题
1.在Android模拟器上，录音后划到预览，提示没有找到文件，权限给了。
2.在Android模拟器上，录音后发出，onFinishRecordVoice接收到的duration无论论录多久的音，都是一个固定值，举个例子：5963或者是5832，不同模拟器之间这个返回的duration是不同的。
3.在Android手机上，是可以正常预览和发送的，预览的时候有声音，但是发出的文件是没有声音的，拿到相应的m4a文件试了下，chrome下也是无法播放，edge和safari下是可以播放的。

**Comment by JoshLipan** [comment]
录音和照相功能请用真机测试，第三条真机测试没有声音是什么机型测的，设备声音调大点，或者换个机子测一下看

**Comment by JoshLipan** [comment]
这边用小米5和小米8测试都没有问题的

**Comment by spidersq** [comment]
看了下代码，是不是不能播放网络路径的voice？能否像图片一样支持网络路径及其缓存？

**Comment by spidersq** [comment]
这里是否有计划改进一下？

**Comment by JoshLipan** [comment]
目前还不支持，后续如果有支持会在发版中说明

**Comment by spidersq** [comment]
好的

**Comment by RowgerGo** [comment]
大兄弟你的im最后用什么方案解决的
