### ISSUE TITLE
添加长按手势

### ISSUE THREAD

**Issue by eyvallah** [jpush/aurora-imui#51]
希望添加长按信息的delegate方法，还有keyboardWillShow里面貌似scrollToBottom没有用？是否可以考虑显示feature view时添加个delegate方法（也许可以和keyboardWillShow统一？因为都是屏幕下方显示一个东西），因为显示feature view时会挡住最下面的信息

**Comment by huangminlinux** [comment]
下个版本中会有个调整，到时候可以自行在contentView 上添加 长按手势。

显示Feature View 的事件 可以监听 SwitchTo****mode 这类事件。

**Comment by eyvallah** [comment]
我再来提一个
open func insertMessages(with messages:[IMUIMessageProtocol])
插入信息后没有显示在原来的位置

**Comment by huangminlinux** [comment]
该问题已修复，可以更新到最新版本。
