### ISSUE TITLE
android接收到消息后必须要点一下聊天列表才会刷新出来

### ISSUE THREAD

**Issue by HongLr** [jpush/aurora-imui#510]
- android
`cn.jiguang.imui:messagelist:0.7.4`
`cn.jiguang.imui:chatinput:0.9.1`

> 在提此问题前已经在关闭的问题中看到过类似问题，但并未解决#61
### 问题描述
在进行通信的时候，接收方正常接收到消息，但是界面上不展示，只有主动触摸messagelist或者chatinput区域才会将消息展现出来

1. 接收方如果接收到一条消息去主动触摸屏幕的话就会展示出来，再接收到一条还需要去主动触摸才会展示

2. 接收方如果接收到第一条消息未主动触摸屏幕，再接收到第二条的时候就会自己展示出来，后面就会一切正常

望解决！

**Comment by HongLr** [comment]
是不是因为messagelist和chatinput有冲突所导致的  @JoshLipan

**Comment by JoshLipan** [comment]
#61 是RN的问题，你这个是在原生遇到的吗，你添加信息调用的是哪个API呢

**Comment by HongLr** [comment]
**已解决**

> 由于是在子线程调用的mAdapter.addToStart(message, true) 所引发的问题
切记要在主线程去调用
