### ISSUE TITLE
拍照后闪退

### ISSUE THREAD

**Issue by MrGaodev** [jpush/aurora-imui#514]
### My environment:

![image](https://user-images.githubusercontent.com/31085101/48690787-f2ac3400-ec0a-11e8-90f7-bf0565e90a02.png)
求助，请问有剪裁接口么。或者设置加载宽，高的地方。

**Comment by MrGaodev** [comment]
![image](https://user-images.githubusercontent.com/31085101/48690897-5cc4d900-ec0b-11e8-8fec-94137d6a5131.png)

**Comment by MrGaodev** [comment]
我这里是必现的，手机是小米3，给的demo也是闪退。

**Comment by MrGaodev** [comment]
@JoshLipan 
我这里是必现的，手机是小米3，给的demo也是闪退。

**Comment by istarvip** [comment]
![_20181124115821](https://user-images.githubusercontent.com/12675437/48964354-69b54400-efe0-11e8-8038-219e168cf121.jpg)
我这拍照发送照片经常发送2次同一张照片

**Comment by JoshLipan** [comment]
因为这边无法复现问题，所以在新版本中对触发此问题的地方做了加固，请更新下面版本重试
原生更新 cn.jiguang.imui:chatinput:0.10.0 ，RN 更新 aurora-imui-react-native@0.13.0
