### ISSUE TITLE
message.msgType 'custom'，

### ISSUE THREAD

**Issue by JohnTree** [jpush/aurora-imui#515]

**Comment by JohnTree** [comment]
message.content = '<h5>This is a custom message. </h5>\
                                      <img src="file://'
                    message.content += RNFS.MainBundlePath + '/defoult_header.png' + '\"></img>'
可以解释下吗 这个路径 我想显示网络图片怎么办

**Comment by JohnTree** [comment]
`message.content = '<h5>This is a custom message. </h5>\
                                      <img src="file://'
                    message.content += RNFS.MainBundlePath + '/defoult_header.png' + '\"></img>'`

**Comment by HuminiOS** [comment]
这个沙盒路径，想显示网络图片替 src 换成 url 就行。

**Comment by JohnTree** [comment]
> 这个沙盒路径，想显示网络图片替 src 换成 url 就行。

安卓好像不可以，ios能出来。

**Comment by JoshLipan** [comment]
Android custom 类型不支持网络图片显示，建议统一下载本地再通过本地路径加载

**Comment by JohnTree** [comment]
> Android custom 类型不支持网络图片显示，建议统一下载本地再通过本地路径加载

如果是本地路径用变量表示，该怎么表示呢，谢谢。
`message.content = '<h5>This is a custom message. </h5>\
                                      <img src="'
            this.state.vimg + '\"></img>'`
目前我这样不好用 闪退 我用的fs

**Comment by JohnTree** [comment]
`` message.content = `
                <body bgcolor="#ff3399">
                  <h5>This is a custom message. </h5>
                  <img src="file://${this.state.vimg}"></img>
                </body>`
这样也不行 但是我看demo 我也试了下 ios这样行

**Comment by JohnTree** [comment]
> Android custom 类型不支持网络图片显示，建议统一下载本地再通过本地路径加载
@JoshLipan 原来图片出来了 是太小了 我发现在安卓真机上只能看到图片一点点 差不多只有一条线

**Comment by JohnTree** [comment]
我把其他的标签都去了就显示了。。。原来是文字挤压的
