### ISSUE TITLE
OC版本里面的 .swift文件有33处报错，纯OC的童鞋不知道怎么改

### ISSUE THREAD

**Issue by yjjwxq** [jpush/aurora-imui#525]

**Comment by yjjwxq** [comment]
![3106c946-5349-422c-bf5a-4bdda354ee8d](https://user-images.githubusercontent.com/19277258/49216925-3f5fee00-f407-11e8-8ace-e927bc350ba4.png)

**Comment by yjjwxq** [comment]
谁来回答一下，OC的demo还在维护吗？

**Comment by huangminlinux** [comment]
将 swift language version 改成 4.2 就行，也可以拉一下最新代码
