### ISSUE TITLE
进入之后直接点表情就会，表情输入框会沾满整个屏幕

### ISSUE THREAD

**Issue by china-coder** [jpush/aurora-imui#527]
### My environment:

进入之后直接点表情就会显示成如下样子
![image](https://user-images.githubusercontent.com/13534737/49488948-d1db1400-f883-11e8-82cb-4ed1a878f3ff.png)
点击输入框，然后再点表情符号，显示正常

**Comment by JoshLipan** [comment]
你这是 RN 吗，RN 可以配合 [onSizeChange](https://github.com/jpush/aurora-imui/blob/master/ReactNative/docs/APIs.md#onsizechange) 来设置控件高度，不然你要自己计算控件位置，具体参考 demo

**Comment by china-coder** [comment]
好的 谢谢了
