### ISSUE TITLE
可以类似淘宝那样发送订单吗？我看目前的自定义消息没有可以点击的按钮，比如点击发送，再发送。如果没有可点击的按钮，只能进入聊天界面直接显示了。

### ISSUE THREAD

**Issue by JohnTree** [jpush/aurora-imui#531]

**Comment by JoshLipan** [comment]
消息内部按钮是无法触发的，我们提供了 [onMsgClick](https://github.com/jpush/aurora-imui/blob/master/ReactNative/docs/APIs.md#onmsgclick) 事件，你可以收到消息点击消息后做个弹窗或者其他方式去实现你想要的逻辑

**Comment by JohnTree** [comment]
好的 谢谢。

**Comment by JohnTree** [comment]
还有个问题，里面的布局我怎么设置什么属性都不好用。。。我是用div

**Comment by JohnTree** [comment]
> 自定义消息属性设置这块要等等，需要看下能不能完善

哦哦 坐等！！！
