### ISSUE TITLE
点击菜单栏麦克风会默认调用起录音面板，并且询问是否授权么？可以阻止这个事件吗？

### ISSUE THREAD

**Issue by GLJK24** [jpush/aurora-imui#535]
### My environment:
- `react-native` version: 0.55.2
- `aurora-imui-react-native` version: 0.12.5

有需求想在Android中说明APP为什么需要录音的权限，所以需要加入一个alert提示用户，然后用户再进行权限确认。
现在我碰到的问题是：没办法在弹出权限弹窗之前加入我自己的提示。
所以我想问下有没有方法可以解决这个问题

**Comment by JoshLipan** [comment]
你可以把原生的权限申请去掉，然后在收到 onSwitchToMicrophoneMode 事件后自己去做alert和权限申请逻辑。
找到[相应位置](https://github.com/jpush/aurora-imui/blob/master/ReactNative/android/src/main/java/cn/jiguang/imui/messagelist/viewmanager/ReactChatInputManager.java#L243)，注释以下代码：

![](https://user-images.githubusercontent.com/16323137/50127999-5c713980-02ae-11e9-8439-223767f08f3f.png)

**Comment by GLJK24** [comment]
好的，我试一下，谢谢你了
