### ISSUE TITLE
ios RN TestRNIMUI 编译不通过

### ISSUE THREAD

**Issue by helloddyl** [jpush/aurora-imui#544]
### My environment:
- `react-native` version:0.53.3
- `aurora-imui-react-native` version:0.11.1
直接编译 react-native run-ios
报错：❌  error: unexpected duplicate task: CompileXIB /Users/Desktop/aurora-imui-0.12.7/ReactNative/sample/node_modules/aurora-imui-react-native/ReactNative/ios/RCTAuroraIMUI/RCTMessageListView.xib (in target 'RCTAuroraIMUI')

❌  error: unexpected duplicate task: CompileXIB /Users/Desktop/aurora-imui-0.12.7/ReactNative/sample/node_modules/aurora-imui-react-native/ReactNative/ios/RCTAuroraIMUI/RCTMessageListView.xib (in target 'RCTAuroraIMUI')

❌  error: unexpected duplicate task: CompileXIB /Users/Desktop/aurora-imui-0.12.7/ReactNative/sample/node_modules/aurora-imui-react-native/ReactNative/ios/RCTAuroraIMUI/RCTInputView.xib (in target 'RCTAuroraIMUI')

❌  error: unexpected duplicate task: CompileXIB /Users/Desktop/aurora-imui-0.12.7/ReactNative/sample/node_modules/aurora-imui-react-native/ReactNative/ios/RCTAuroraIMUI/RCTInputView.xib (in target 'RCTAuroraIMUI')

** BUILD FAILED **

Installing build/Build/Products/Debug-iphonesimulator/TestRNIMUI.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/TestRNIMUI.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

安卓是没有问题的

**Comment by huangminlinux** [comment]
可以升级到最新版本 aurora-imui-react-native 0.12.7 , 老版本的在 xcode 10 上会有这个问题。

**Comment by YuJianSirius** [comment]
我也遇到过，删掉重复的引用就可以了

**Comment by zjz2020** [comment]
xcode还是没有编译通过,"aurora-imui-react-native": "^0.13.1",这个挺高了,RCTAuroraIMUI这个库也删除了多余的,编译失败 没有报错
