### ISSUE TITLE
xcode9.2跑objcsample工程swift语法报错问题

### ISSUE THREAD

**Issue by ZhangQiJin** [jpush/aurora-imui#546]
### My environment:
 native iOS 

- [ ] 使用xcode9.2跑demo会有很多swift语法问题，请问swift语法对应的版本是最新的还是多少版本的swift

**Comment by huangminlinux** [comment]
当前是 swift4.2 版本，如果是4.0  可以用 https://github.com/jpush/aurora-imui/tree/swift4.0
