### ISSUE TITLE
6.0权限问题

### ISSUE THREAD

**Issue by a7210232** [jpush/aurora-imui#55]
6.0语音和图片无法获取到本地文件

**Comment by lhw5123** [comment]
是运行的 sample 吗？具体机型是什么？

**Comment by KenChoi1992** [comment]
@a7210232 需要设置一下录音及拍照的路径。用这两个接口：`setVoiceFilePath` 和 `setCameraCaptureFile`。详情可以参考 sample。

**Comment by KenChoi1992** [comment]
@a7210232 没有回复就关闭了。
