### ISSUE TITLE
属性cornerRadius冲突

### ISSUE THREAD

**Issue by tanzhixue** [jpush/aurora-imui#551]
error: duplicate value for resource 'attr/cornerRadius' with config ''.
Message{kind=ERROR, text=error: duplicate value for resource 'attr/cornerRadius' with config ''., sources=[H:\studio\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.0.aar\65222ecbbfb7ceab75a28af8cca72655\res\values\values.xml:251:5-69], original message=, tool name=Optional.of(AAPT)}

**Comment by tanzhixue** [comment]
已找到不是这个库的问题

**Comment by SmartVive** [comment]
请问是怎么解决的？我也出现了这个问题 @tanzhixue

**Comment by Evan-zch** [comment]
> 请问是怎么解决的？我也出现了这个问题@tanzhixue

处理了吗?

**Comment by Evan-zch** [comment]
好吧，我不知道和哪个库冲突了，直接改个名字就好了

**Comment by tanzhixue** [comment]
> 请问是怎么解决的？我也出现了这个问题 @tanzhixue

自己工程里面全局搜索这个属性直接改名字就好了

**Comment by tanzhixue** [comment]
> 好吧，我不知道和哪个库冲突了，直接改个名字就好了

对哦直接该自己工程里面的属性字段就好了
