### ISSUE TITLE
ReactNative 下如何客户化 发送和接受方文字的背景颜色

### ISSUE THREAD

**Issue by kala888** [jpush/aurora-imui#558]
React Native，尝试设置
```
 sendBubble={{imageName: "send_msg", padding: 10}}
```
报错

![image](https://user-images.githubusercontent.com/1215976/51518122-d8cfdd00-1e57-11e9-8eeb-35d908725fd1.png)

**Comment by chenmyGitHub** [comment]
你好，可以直接设置颜色吗？
receiveBubble={{ imageName: "图片名称", padding: { left: 10, right: 10, top:10 , left: 10 } }}
图片会出现如下的情况。
![image](https://user-images.githubusercontent.com/7311356/52947888-f474c780-33b2-11e9-87b2-22b165ea130b.png)

**Comment by gancan110** [comment]
Android的怎修改自定义bubble

**Comment by JoshLipan** [comment]
参考[自定义介绍](https://github.com/jpush/aurora-imui/blob/master/ReactNative/docs/APIs_zh.md#messagelist-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) @gancan110
