### ISSUE TITLE
文字显示区域宽度可以调整吗？iOS 和 RN

### ISSUE THREAD

**Issue by HHuiHao** [jpush/aurora-imui#559]
![image](https://user-images.githubusercontent.com/8486113/51592321-43e9e400-1f2a-11e9-988f-777d50c3892a.png)
调整为：
![image](https://user-images.githubusercontent.com/8486113/51592350-595f0e00-1f2a-11e9-9e43-75f98fa3a3e1.png)

**Comment by huangminlinux** [comment]
可以使用  [maxBubbleWidth](https://github.com/jpush/aurora-imui/blob/master/ReactNative/docs/APIs_zh.md#maxBubbleWidth)

**Comment by HHuiHao** [comment]
bubbleMaxWidth  好的，谢谢！
