### ISSUE TITLE
rn 0.13.0 安卓customLayoutItems属性被误删了

### ISSUE THREAD

**Issue by gmmp** [jpush/aurora-imui#562]
chatinput 的 customLayoutItems属性被删除了，估计是增加新属性误替换了，会导致使用customLayoutItems属性时rn报错。

**Comment by JoshLipan** [comment]
[sample](https://github.com/jpush/aurora-imui/blob/master/ReactNative/sample/App.js#L557) 测试 [customLayoutItems](https://github.com/jpush/aurora-imui/blob/master/ReactNative/android/src/main/java/cn/jiguang/imui/messagelist/viewmanager/ReactChatInputManager.java#L748)  没问题

**Comment by gmmp** [comment]
- 原生的代码没问题的，我是说封装原生方法的js代码。这次commit [chatinput.android.js](https://github.com/jpush/aurora-imui/commit/8ed9e172bd761bd52e6eba2a8caf18c4df2ae08b#diff-650cae007f7eff7c3d8796cbe4729669L270)将customLayoutItems的定义去除了，导致使用会错误。
- 还有sample中package.json定义的[aurora-imui-react-native依赖](https://github.com/jpush/aurora-imui/blob/master/ReactNative/sample/package.json#L11)为 ``^0.11.1``，理论上这样major版本号为0，是取不到最新的0.13.0吧
[npm关于版本号文档](https://docs.npmjs.com/misc/semver.html)
![image](https://user-images.githubusercontent.com/16728548/52624583-043f6800-2eea-11e9-8b06-b2995f99c7c0.png)

**Comment by JoshLipan** [comment]
参数缺失问题已发布 [v0.13.1](https://www.npmjs.com/package/aurora-imui-react-native/v/0.13.1) 修复，sample 也同步更新版本了，感谢建议
