### ISSUE TITLE
异步请求成功后再设置发送状态没有效果

### ISSUE THREAD

**Issue by Jorble** [jpush/aurora-imui#572]
### My environment:

代码如下：
                final ChatMessage sendMessage = new ChatMessage(input.toString(), IMessage.MessageType.SEND_TEXT.ordinal());
                sendMessage.setUserInfo(new DefaultUser("1", "Ironman", "R.drawable.ironman"));
                sendMessage.setTimeString(new SimpleDateFormat("HH:mm", Locale.getDefault()).format(new Date()));
                mAdapter.addToStart(sendMessage, true);
               //发送网络请求(异步)
                call.enqueue(new Callback<ExpertMsgRsp>() {
                    @Override
                    public void onResponse(Call<ExpertMsgRsp> call, Response<ExpertMsgRsp> response) {
                       ....

                        //显示发送成功状态（就是这里设置状态没有反应）
                        sendMessage.setMessageStatus(IMessage.MessageStatus.SEND_SUCCEED);

**Comment by JoshLipan** [comment]
修改消息状态后同时调用更新消息API，注意要在 UI 线程操作
```
sendMessage.setMessageStatus(IMessage.MessageStatus.SEND_SUCCEED);
mAdapter.updateMessage(sendMessage);
```

**Comment by Jorble** [comment]
啊，对喔，谢谢你啊
