### ISSUE TITLE
iOS 前置摄像头拍照崩溃

### ISSUE THREAD

**Issue by Jqiangwf** [jpush/aurora-imui#575]
### My environment:

iOS 11.2 聊天是调用前置摄像头拍照崩溃
错误在IMUICameraView 575行
      self.photoOutput?.capturePhoto(with: photoSettings, delegate: photoCaptureDelegate)
错误日志：libc++abi.dylib: terminate_handler unexpectedly threw an exception

**Comment by huangminlinux** [comment]
原生可以升级到 0.14.0 版本，修复了这个问题。

**Comment by Jqiangwf** [comment]
pod里面我只看到了0.12.0版本呢

**Comment by huangminlinux** [comment]
应该是 pod 本地仓库没有更新， 可以更新一下再看看。

**Comment by Jqiangwf** [comment]
你好，导入了0.14.0后，报了很多swift的语法错误，这个是什么原因导致的呢？ 之前设置的swift version 4.0

**Comment by Jqiangwf** [comment]
不管swift版本设置成4.0 还是4.2都是会报那些语法错误
![image](https://user-images.githubusercontent.com/21197148/53718119-4d555d00-3e95-11e9-9626-75bf1d998dc7.png)

**Comment by huangminlinux** [comment]
新版本适配的是 swift4.2
可能是升级的时候  pod 指定版本没有更新，
两个方法
- 卸载再安装
- 将 Pods -> TARGETS -> Build Settings -> Swift Language Version 设为 swift 4.2
