### ISSUE TITLE
如何修改发送按钮的样式

### ISSUE THREAD

**Issue by CRTZUISHUAI** [jpush/aurora-imui#578]

**Comment by CRTZUISHUAI** [comment]
<InputView style={this.state.inputViewLayout}
                           ref="ChatInput"
                           onSendText={this.onSendText}
                           onTakePicture={this.onTakePicture}
                           onStartRecordVideo={this.onStartRecordVideo}
                           onFinishRecordVideo={this.onFinishRecordVideo}
                           onSendGalleryFiles={this.onSendGalleryFiles}
                           onSwitchToEmojiMode={this.onSwitchToEmojiMode}
                           onSwitchToMicrophoneMode={this.onSwitchToMicrophoneMode}
                           onSwitchToGalleryMode={this.onSwitchToGalleryMode}
                           onSwitchToCameraMode={this.onSwitchToCameraMode}
                           onShowKeyboard={this.onShowKeyboard}
                           onTouchEditText={this.onTouchEditText}
                           onFullScreen={this.onFullScreen}
                           onRecoverScreen={this.onRecoverScreen}
                           onSizeChange={this.onInputViewSizeChange}
                           closeCamera={this.onCloseCamera}
                           switchCameraMode={this.switchCameraMode}
                           showSelectAlbumBtn={false}
                           showRecordVideoBtn={false}
                           onClickSelectAlbum={this.onClickSelectAlbum}
                           chatInputBackgroundcolor={"#000000"}
                           inputPadding={{ left: 10, top: 10, right: 10, bottom: 10 }}
                           galleryScale={0.6}//default = 0.5
                           compressionQuality={0.6}
                           cameraQuality={0.7}//default = 0.5
                           customLayoutItems={{
                               left: ['emoji'],
                               right: ['send'],
                               // bottom: ['voice','gallery','emoji','camera']
                           }}
                />

**Comment by JoshLipan** [comment]
没提供配置，可以通过修改原生实现
