### ISSUE TITLE
求助:刚进页面MessageList自动滑动到底部怎么实现，发送一条消息，MessageList会自动跳到第一条怎么解决

### ISSUE THREAD

**Issue by mazihao66** [jpush/aurora-imui#58]
求助:刚进页面MessageList自动滑动到底部怎么实现，发送一条消息，MessageList会自动跳到第一条怎么解决

**Comment by huangminlinux** [comment]
react-native , 还是 native iOS / Android

**Comment by mazihao66** [comment]
Android

**Comment by mazihao66** [comment]
刚进页面有多条聊天记录的时候，使用mMsgList.scrollToPosition()不启作用，自动滑动到底部不知道怎么实现

**Comment by lhw5123** [comment]
可以参考下 demo 的写法：
![hv28 110 ecihl5a1w ct](https://user-images.githubusercontent.com/6531354/27363452-473ad318-5667-11e7-897c-7f6bc3491936.png)

**Comment by mazihao66** [comment]
感谢，可以了
