### ISSUE TITLE
能不能支持消息长按事件

### ISSUE THREAD

**Issue by 871263000** [jpush/aurora-imui#581]
没有长按事件。  不能定义转发事件

**Comment by JoshLipan** [comment]
原生和 RN 都有长按事件

**Comment by 871263000** [comment]
RN MessageList 事件回调 API  并没有看到那里有长按事件。  请问是那个事件？

**Comment by JoshLipan** [comment]
https://github.com/jpush/aurora-imui/blob/master/ReactNative/messagelist.android.js#L98
