### ISSUE TITLE
项目里面的demo为什么运行报错

### ISSUE THREAD

**Issue by dypbkb1314** [jpush/aurora-imui#582]
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

这是模拟器版本问题么

**Comment by JoshLipan** [comment]
就这个 log 看这是设备连接问题，和项目没关系

**Comment by dypbkb1314** [comment]
换了下启动方式，用android-studio启动不会报这个错了，会提示 Plugin with id 'com.android.library' not found 原生这方面不是很懂，大佬能帮下忙不，去网上找了下解决方法也没有解决，万分感谢

**Comment by dypbkb1314** [comment]
应该是缓存的问题 ，清了两遍重新运行可以了，感谢大佬的demo
