### ISSUE TITLE
library not found for -lReact

### ISSUE THREAD

**Issue by luojf945** [jpush/aurora-imui#59]
### clang: error: linker command  failed with exit code 1 (use -v  to see  invocation)

**Comment by 1107979819** [comment]
你好，请教一下，你这个问题是如何解决的？我也遇到了

**Comment by SmileYXHP** [comment]
同问，编译的时候遇到的，怎么解决

**Comment by cnpmge** [comment]
怎么解决的老哥

**Comment by HeyShinner** [comment]
请问怎么解决的 @luojf945
