### ISSUE TITLE
点击发送消息后，聊天列表不会更新，必须要手动滑一下才会更新，这是为什么呢？

### ISSUE THREAD

**Issue by sarsbug** [jpush/aurora-imui#61]
点击发送消息后，聊天列表不会更新，必须要手动滑一下才会更新，这是为什么呢？

**Comment by terryyhl** [comment]
我是收到消息不会更新 ，得滑一下才会更新

**Comment by terryyhl** [comment]
上面的问题你处理了没有

**Comment by Jorble** [comment]
是不是你布局问题啊

**Comment by KenChoi1992** [comment]
@Jorble 你有没有出现这个问题？

**Comment by Jorble** [comment]
发送第一张图片的时候有时候会，后面基本都会自动显示最后一条的。可能是你布局遮住了吧。

**Comment by KenChoi1992** [comment]
@sarsbug 调试发现，原生的插入数据后，执行了 `onBindViewHolder`，在 RN 中则没有执行，不知道什么原因。

**Comment by KenChoi1992** [comment]
发布了 0.4.13， 修复了这个问题。

**Comment by jianhui1012** [comment]
由于在Android中ReacNative重写了requestLayout方法，接管了绘制，measure，layout两个方法不会自动调用;
在Android中自定义控件需要重写requestLayout，并强制调用measure，layout两个方法;
详情可以查看stackoverflow：[React Native: Resize custom UI component](https://stackoverflow.com/questions/39836356/react-native-resize-custom-ui-component)
