### ISSUE TITLE
git下有两个rn的demo，应该用哪个

### ISSUE THREAD

**Issue by RowgerGo** [jpush/aurora-imui#619]
git 仓库下有两个rn的ui库，并且两个用法是不一样的，应该用哪个？
```
npm install aurora-imui-react-native --save
npm install aurora-imui@beta --save
```

**Comment by cnpmge** [comment]
你也在搞这个吗，我用的是npm install aurora-imui-react-native --save这个，你知道这个ui库有接收消息的函数吗

**Comment by UchihaKutter** [comment]
那两个demo运行不起来

**Comment by zmGitHub** [comment]
都不行 两个都是跑不起来 感觉 在新版 RN 中 就没有跑起来的

**Comment by cnpmge** [comment]
用第二个，但是你得在运行之前把react-native-fs这个组件下载下来
https://blog.csdn.net/sinat_17775997/article/details/80996574
这个网址你可以看一下，很详细。

**Comment by zmGitHub** [comment]
> 用第二个，但是你得在运行之前把react-native-fs这个组件下载下来
> https://blog.csdn.net/sinat_17775997/article/details/80996574
> 这个网址你可以看一下，很详细。

老铁 方便加个微信勾兑勾兑吗? qingfeideyi816302

**Comment by zmGitHub** [comment]
> 用第二个，但是你得在运行之前把react-native-fs这个组件下载下来
> https://blog.csdn.net/sinat_17775997/article/details/80996574
> 这个网址你可以看一下，很详细。

老铁 方便加个微信勾兑勾兑吗? qingfeideyi816302 第二个是 js 版 第一个才是原生的
