### ISSUE TITLE
nullpointerException

### ISSUE THREAD

**Issue by smarthityou** [jpush/aurora-imui#62]
![qq 20170629160212](https://user-images.githubusercontent.com/16317348/27678109-93549b8c-5ce6-11e7-9d6e-3d241ff74c6d.png)

**Comment by KenChoi1992** [comment]
dev 上修复了，这个星期发布新版本。

**Comment by smarthityou** [comment]
蟹蟹

**Comment by KenChoi1992** [comment]
@smarthityou 更新了
