### ISSUE TITLE
aurora-imui-react-native有没有接收消息的函数，跟微信一样，接收的消息靠左！

### ISSUE THREAD

**Issue by cnpmge** [jpush/aurora-imui#622]
![Screenshot_2019-06-13-10-40-15-905_com xiaoliao](https://user-images.githubusercontent.com/48587696/59404255-795b7500-8dd8-11e9-90c6-0c3d1c3dd354.png)
### My environment:

![Screenshot_2019-06-13-10-40-15-905_com xiaoliao](https://user-images.githubusercontent.com/48587696/59405155-0522d080-8ddc-11e9-9928-88fc7506a029.png)

**Comment by solke** [comment]
确实没看到消息是别人发送的类型的参数

**Comment by cnpmge** [comment]
isOutgoing
