### ISSUE TITLE
dev 分支的 RN sample 无法运行

### ISSUE THREAD

**Issue by musicode** [jpush/aurora-imui#63]
![image](https://user-images.githubusercontent.com/2732303/27763623-3fb062e8-5eb9-11e7-99e5-ad1b2bb89021.png)

按文档所述，我先编译 aurora-imui framework，但是报错了，是哪里操作错误么

**Comment by huangminlinux** [comment]
我新拉下来是没有问题的， 用的是 0.4.2 版本。

**Comment by huangminlinux** [comment]
升级 xcode 到最新版本，先关闭这个 issue 如果还有问题可以重新打开。
