### ISSUE TITLE
能否支持一下文件传送呢？

### ISSUE THREAD

**Issue by china-coder** [jpush/aurora-imui#64]
项目中需要传送文件，请问应该怎么扩展呢？

**Comment by huangminlinux** [comment]
ReactNative 还不支持扩展，   原生的可以使用自定义消息

**Comment by china-coder** [comment]
自定义消息相关的文档在那看呢？我没有找到这方面的文档

**Comment by huangminlinux** [comment]
[iOS](https://github.com/jpush/aurora-imui/blob/master/docs/iOS/IMUIMessageCollectionView_usage_iOS_zh.md#自定义消息)

[Android](https://github.com/jpush/aurora-imui/blob/master/docs/Android/custom_layout_zh.md)

**Comment by china-coder** [comment]
在ChatInputView 这个组件里面 怎么扩展出 选择文件还有发送地理位置呢？

**Comment by huangminlinux** [comment]
InputView 不支持扩展

**Comment by china-coder** [comment]
好的  谢谢

**Comment by KenChoi1992** [comment]
将来会做几种常见的自定义消息类型。
