### ISSUE TITLE
我要才能在AS里面怎么编译运行demo啊

### ISSUE THREAD

**Issue by oscartorres9** [jpush/aurora-imui#642]
AS打开的路径是aurora-imui-master\Android\sample
gradle build error:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':chatinput'.
> Failed to notify project evaluation listener.
   > org.gradle.api.tasks.compile.CompileOptions.setBootClasspath(Ljava/lang/String;)V

好吧，然后我去打开project ':chatinput'.
然后又报错
gradle build error:

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\CXFile\CXAndroid\aurora-imui-master\Android\chatinput\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating root project 'chatinput'.
> Plugin with id 'com.android.library' not found.

================================
==    apply plugin: 'com.android.library'              ==
================================

所以我要怎么在AS里面运行DEMO啊啊啊，求各位大佬支招了ORZ

**Comment by mariohide** [comment]
用 git clone 的方式把项目克隆到你本地，而不是直接下载项目的 zip 包。
打开项目如果还有问题，记得改下项目目录下的 build.gradle 文件里的 gradle 插件版本，改到你日常使用的版本即可。
