### ISSUE TITLE
请问当 react-native 版本 >0.59 时要怎样使用 ？

### ISSUE THREAD

**Issue by SteveChina** [jpush/aurora-imui#669]
### My environment:

`react-native` version: 0.60
`aurora-imui-react-native` version: 0.10.1

**Comment by jeromehan** [comment]
> ### My environment:
> `react-native` version: 0.60
> `aurora-imui-react-native` version: 0.10.1

![image](https://user-images.githubusercontent.com/19773879/70586608-87ad1100-1c02-11ea-87de-22f4b1e460fd.png)
![image](https://user-images.githubusercontent.com/19773879/70586629-98f61d80-1c02-11ea-84f7-7ff1c662daff.png)
修改图中2处，把lReact lWebSocket链接库干掉。因为直接引入Pods Headers就不需要配置other Link了
![image](https://user-images.githubusercontent.com/19773879/70586722-db1f5f00-1c02-11ea-876a-28b7605ba4aa.png)
主项目引入相关库就完美了。
![image](https://user-images.githubusercontent.com/19773879/70586806-1faafa80-1c03-11ea-9dc0-f3435c23020c.png)

**Comment by cnpmge** [comment]
> > ### My environment:
> > `react-native` version: 0.60
> > `aurora-imui-react-native` version: 0.10.1
> 
> ![image](https://user-images.githubusercontent.com/19773879/70586608-87ad1100-1c02-11ea-87de-22f4b1e460fd.png)
> ![image](https://user-images.githubusercontent.com/19773879/70586629-98f61d80-1c02-11ea-84f7-7ff1c662daff.png)
> 修改图中2处，把lReact lWebSocket链接库干掉。因为直接引入Pods Headers就不需要配置other Link了
> ![image](https://user-images.githubusercontent.com/19773879/70586722-db1f5f00-1c02-11ea-876a-28b7605ba4aa.png)
> 主项目引入相关库就完美了。
> ![image](https://user-images.githubusercontent.com/19773879/70586806-1faafa80-1c03-11ea-9dc0-f3435c23020c.png)

你的图都看不到了，能单独发我一份吗？

**Comment by SteveChina** [comment]
> > > ### My environment:
> > > `react-native` version: 0.60
> > > `aurora-imui-react-native` version: 0.10.1
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/19773879/70586608-87ad1100-1c02-11ea-87de-22f4b1e460fd.png)
> > ![image](https://user-images.githubusercontent.com/19773879/70586629-98f61d80-1c02-11ea-84f7-7ff1c662daff.png)
> > 修改图中2处，把lReact lWebSocket链接库干掉。因为直接引入Pods Headers就不需要配置other Link了
> > ![image](https://user-images.githubusercontent.com/19773879/70586722-db1f5f00-1c02-11ea-876a-28b7605ba4aa.png)
> > 主项目引入相关库就完美了。
> > ![image](https://user-images.githubusercontent.com/19773879/70586806-1faafa80-1c03-11ea-9dc0-f3435c23020c.png)
> 
> 你的图都看不到了，能单独发我一份吗？

点击查看图片是可以看到的。

**Comment by SteveChina** [comment]
> > ### My environment:
> > `react-native` version: 0.60
> > `aurora-imui-react-native` version: 0.10.1
> 
> ![image](https://user-images.githubusercontent.com/19773879/70586608-87ad1100-1c02-11ea-87de-22f4b1e460fd.png)
> ![image](https://user-images.githubusercontent.com/19773879/70586629-98f61d80-1c02-11ea-84f7-7ff1c662daff.png)
> 修改图中2处，把lReact lWebSocket链接库干掉。因为直接引入Pods Headers就不需要配置other Link了
> ![image](https://user-images.githubusercontent.com/19773879/70586722-db1f5f00-1c02-11ea-876a-28b7605ba4aa.png)
> 主项目引入相关库就完美了。
> ![image](https://user-images.githubusercontent.com/19773879/70586806-1faafa80-1c03-11ea-9dc0-f3435c23020c.png)

非常感谢！最近在做其他项目，还没有验证，验证后再反馈验证结果。

**Comment by SteveChina** [comment]
> > > ### My environment:
> > > `react-native` version: 0.60
> > > `aurora-imui-react-native` version: 0.10.1
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/19773879/70586608-87ad1100-1c02-11ea-87de-22f4b1e460fd.png)
> > ![image](https://user-images.githubusercontent.com/19773879/70586629-98f61d80-1c02-11ea-84f7-7ff1c662daff.png)
> > 修改图中2处，把lReact lWebSocket链接库干掉。因为直接引入Pods Headers就不需要配置other Link了
> > ![image](https://user-images.githubusercontent.com/19773879/70586722-db1f5f00-1c02-11ea-876a-28b7605ba4aa.png)
> > 主项目引入相关库就完美了。
> > ![image](https://user-images.githubusercontent.com/19773879/70586806-1faafa80-1c03-11ea-9dc0-f3435c23020c.png)
> 
> 你的图都看不到了，能单独发我一份吗？

本人还没有验证该方法，验证后请反馈一下验证结果给大家，谢谢！

**Comment by cnpmge** [comment]
> > > ### My environment:
> > > `react-native` version: 0.60
> > > `aurora-imui-react-native` version: 0.10.1
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/19773879/70586608-87ad1100-1c02-11ea-87de-22f4b1e460fd.png)
> > ![image](https://user-images.githubusercontent.com/19773879/70586629-98f61d80-1c02-11ea-84f7-7ff1c662daff.png)
> > 修改图中2处，把lReact lWebSocket链接库干掉。因为直接引入Pods Headers就不需要配置other Link了
> > ![image](https://user-images.githubusercontent.com/19773879/70586722-db1f5f00-1c02-11ea-876a-28b7605ba4aa.png)
> > 主项目引入相关库就完美了。
> > ![image](https://user-images.githubusercontent.com/19773879/70586806-1faafa80-1c03-11ea-9dc0-f3435c23020c.png)
> 
> 非常感谢！最近在做其他项目，还没有验证，验证后再反馈验证结果。

谢谢你，我已经运行成功了，非常感谢

**Comment by liumin007** [comment]
主项目引入相关库就完美了。 卡在这一步，这两个frameWork保存在哪里的，项目里没有啊

**Comment by jeromehan** [comment]
> 主项目引入相关库就完美了。 卡在这一步，这两个frameWork保存在哪里的，项目里没有啊

手动引入的aurora-imui

**Comment by jeromehan** [comment]
> 主项目引入相关库就完美了。 卡在这一步，这两个frameWork保存在哪里的，项目里没有啊

![image](https://user-images.githubusercontent.com/19773879/72033646-e0d59680-32cd-11ea-8560-aa66463e4e3c.png)
引入之后，点击加号

**Comment by cnpmge** [comment]
项目下的Libraries引入添加RCTAuroraIMUI.xcodeproj，然后再添加就有了

**Comment by liumin007** [comment]
cocoapods导入的咋弄呢

**Comment by cnpmge** [comment]
删了，然后手动不就行了，而且cocopods应该警告你没有这个库吧

**Comment by liumin007** [comment]
对啊，这个东西只能手动是吧

**Comment by jeromehan** [comment]
> cocoapods导入的咋弄呢


cocoapods 导入的只能用在iOS开发的，不能是RN开发的，RN开发的需要手动导入工程

**Comment by jeromehan** [comment]
> 删了，然后手动不就行了，而且cocopods应该警告你没有这个库吧

README写的很清楚了

**Comment by SteveChina** [comment]
Great!

**Comment by whytimber** [comment]
> > > > ### My environment:
> > > > `react-native` version: 0.60
> > > > `aurora-imui-react-native` version: 0.10.1
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/19773879/70586608-87ad1100-1c02-11ea-87de-22f4b1e460fd.png)
> > > ![image](https://user-images.githubusercontent.com/19773879/70586629-98f61d80-1c02-11ea-84f7-7ff1c662daff.png)
> > > 修改图中2处，把lReact lWebSocket链接库干掉。因为直接引入Pods Headers就不需要配置other Link了
> > > ![image](https://user-images.githubusercontent.com/19773879/70586722-db1f5f00-1c02-11ea-876a-28b7605ba4aa.png)
> > > 主项目引入相关库就完美了。
> > > ![image](https://user-images.githubusercontent.com/19773879/70586806-1faafa80-1c03-11ea-9dc0-f3435c23020c.png)
> > 
> > 
> > 非常感谢！最近在做其他项目，还没有验证，验证后再反馈验证结果。
> 
> 谢谢你，我已经运行成功了，非常感谢

能上传一下demo吗

**Comment by yz1311** [comment]
@jeromehan  谢谢，差点放弃了，这个库真是坑死人了，0.62及以上的版本还要注意，移除掉Flipper相关代码，不然会报错

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ghbairmf1yj30oq069wfk.jpg)

**Comment by search110** [comment]
react-native version: 0.62.0
aurora-imui-react-native version: 0.14.0
手动添加后run-ios 失败、项目跑不起来
当unlink后、Invariant Violation: requireNativeComponent: "RCTMessageListView" was not found in the UIManager.
不知有如何解决

**Comment by HHuiHao** [comment]
0.62以上，除了修改上述配置外，移除掉Flipper相关代码，就能run成功啦！
1、注释掉Podfile里的：
```
#  add_flipper_pods!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
```
2、注释掉AppDelegate.m里的相关'Flipper'代码

**Comment by magiclove** [comment]
我按照上面的操作会报如下错误
react-native version: 0.63.2
aurora-imui-react-native version: 0.10.5

In file included from /Users/ihk.xtb/reactNativeCode/apptest/node_modules/aurora-imui-react-native/ReactNative/ios/RCTAuroraIMUI/RCTInputView.m:9:
/Users/ihk.xtb/reactNativeCode/apptest/node_modules/aurora-imui-react-native/ReactNative/ios/RCTAuroraIMUI/RCTInputView.h:12:9: fatal error: 'React/RCTComponent.h' file not found
#import <React/RCTComponent.h>
        ^~~~~~~~~~~~~~~~~~~~~~

**Comment by zjz1993** [comment]
没成功的同学可以看我这边
react-native:0.61.2
aurora-imui-react-native 0.14.0
配置如下图所示
![image](https://user-images.githubusercontent.com/17746534/91806717-a2c32380-ec5e-11ea-9382-6d33fd4145ab.png)
![image](https://user-images.githubusercontent.com/17746534/91807018-b8384d80-ec5e-11ea-9e27-a6fc16fc3fe4.png)
亲测可build成功

**Comment by qq1052504303** [comment]
图片的软件是什么呀，找不到该图片

**Comment by SteveChina** [comment]
> 图片的软件是什么呀，找不到该图片

xcode

**Comment by BeMxself** [comment]
xcode13下按照这个方法编译不过

> > ### My environment:
> > `react-native` version: 0.60
> > `aurora-imui-react-native` version: 0.10.1
> 
> ![image](https://user-images.githubusercontent.com/19773879/70586608-87ad1100-1c02-11ea-87de-22f4b1e460fd.png) ![image](https://user-images.githubusercontent.com/19773879/70586629-98f61d80-1c02-11ea-84f7-7ff1c662daff.png) 修改图中2处，把lReact lWebSocket链接库干掉。因为直接引入Pods Headers就不需要配置other Link了 ![image](https://user-images.githubusercontent.com/19773879/70586722-db1f5f00-1c02-11ea-876a-28b7605ba4aa.png) 主项目引入相关库就完美了。 ![image](https://user-images.githubusercontent.com/19773879/70586806-1faafa80-1c03-11ea-9dc0-f3435c23020c.png)
