### ISSUE TITLE
ios 录制的 aac 文件 在 Android 上不能播放

### ISSUE THREAD

**Issue by zmGitHub** [jpush/aurora-imui#67]
我发现 iOS 录制的 aac 文件 可以在 iOS 播放 但是在 Android 中就不能, 但是 Android 录制的 aac 文件在 Android 和 iOS中都可以, 我分析了下这俩个文件的信息发现 format 格式不对, 请问这个是怎么解决的:

![Uploading image.png…]()

**Comment by huangminlinux** [comment]
iOS 读取数据，传输数据即可
