### ISSUE TITLE
ios运行之后没有展示，就是红屏

### ISSUE THREAD

**Issue by powerformer** [jpush/aurora-imui#68]
![image](https://user-images.githubusercontent.com/26423749/27822120-229dc3c4-60d7-11e7-9faa-32da9b008af0.png)

**Comment by powerformer** [comment]
怎么在项目编译之前先编译aurora-imui.framework，求帮忙

**Comment by huangminlinux** [comment]
![2017-07-04 5 47 47](https://user-images.githubusercontent.com/5852088/27826417-81f0b7a0-6078-11e7-8e9d-de90cc5b1f25.png)
点这个编译。

另外在 PROJECT -> TARGETS -> General -> Embedded Binaries 中添加 RCTAuroraIMUI.framework 这个库

**Comment by powerformer** [comment]
你好，成功运行了，我已经编译了RCTAuroralMUI了，但是在应用里显示AuroraIMUIModule这个模块不存在

**Comment by powerformer** [comment]
@huangminlinux

**Comment by huangminlinux** [comment]
这就奇怪了，用的是最新版本吗？ 
 检查一下 RCTAuroraIMUI -》 TARGETS-》AuroraIMUI 没有没

**Comment by powerformer** [comment]
![image](https://user-images.githubusercontent.com/26423749/27829657-33484b2c-60f5-11e7-971d-ea3bc7b2c9e8.png)
要这样引用才对，RCTAuroraIMUI不存在，直接引用AuroraIMUI，但是发送消息会报default_header错，默认头像的问题把？
![image](https://user-images.githubusercontent.com/26423749/27829704-7fbede12-60f5-11e7-8607-20ba8dc27a9c.png)

**Comment by huangminlinux** [comment]
https://github.com/jpush/aurora-imui/blob/master/ReactNative/README_zh.md#messagelist-自定义样式

看一下这个文档， 里面有要求把你的默认头像导入到工程之中

**Comment by powerformer** [comment]
我如何区分这条消息是对方的呢，就是我从后台取了数据做展现，如何展现自己和别人呢。
![image](https://user-images.githubusercontent.com/26423749/27832078-ed44986e-60ff-11e7-97ab-ae02730b5a30.png)

**Comment by huangminlinux** [comment]
除了event message 其他的消息都有一个 isOutgoing : bool 字段，用于区分是接收还是发送

https://github.com/jpush/aurora-imui/blob/master/ReactNative/README.md#data-format

**Comment by powerformer** [comment]
👍👍问题基本解决了，多谢啦。
就是还有个建议，建议把每种消息类型的源文件直接暴露出来，不要只提供路径，这样便于sdk直接存储

**Comment by musicode** [comment]
在 PROJECT -> TARGETS -> General -> Embedded Binaries 中添加 RCTAuroraIMUI.framework 这个库

发现两个，选哪个呢？

![image](https://user-images.githubusercontent.com/2732303/28514098-63538692-708b-11e7-8285-8f458d646894.png)

**Comment by huangminlinux** [comment]
下面这个 RCTAuroraIMUI 是你自己拖进去的？

**Comment by musicode** [comment]
不是，自己出来的

**Comment by musicode** [comment]
我的操作步骤：

1. 切换到 dev 分支
2. cd 到 sample 目录
3. npm install
4. react-native link
5. 编译 auroal，编译方式借用你的图

![](https://user-images.githubusercontent.com/5852088/27826417-81f0b7a0-6078-11e7-8e9d-de90cc5b1f25.png)

6. 这时候貌似已经导入 framework 了是么

![image](https://user-images.githubusercontent.com/2732303/28515795-7f26255e-7091-11e7-81fa-10bf83c4c4e1.png)

7. Clean 之后，Run
8. 毫无反应

**Comment by huangminlinux** [comment]
不清楚下面这个怎么来的， 一般使用 Libraries 里面的。

毫无反应是什么意思？

**Comment by musicode** [comment]
第6步，Embeded Binaries 已经有 framework 还需要导入么？

毫无反应就是 xcode 提示编译成功，但是什么都没有发生，界面没有自动弹出来，我点击模拟器里的图标，启动不了

**Comment by huangminlinux** [comment]
第六步，建议删掉之前的重新添加。

编译选项选的是 app 还是 framework？ 如果是 framework 就不会编译 app

**Comment by musicode** [comment]
framework 删掉重新导入，如图所示

![image](https://user-images.githubusercontent.com/2732303/28516295-4c316206-7093-11e7-8767-9aa45316e339.png)

确实是没选 app 导致的，这次成功了，多谢~
