### ISSUE TITLE
覆盖了我APP的名字

### ISSUE THREAD

**Issue by EpicWang** [jpush/aurora-imui#7]
添加依赖之后，IMUNKit覆盖了我APP原来的名字，请问在哪修改

**Comment by KenChoi1992** [comment]
@EpicWang 在 strings 中修改一下，这个是我们疏忽了，没有去掉其中默认生成的字符串。

**Comment by KenChoi1992** [comment]
@EpicWang 最近的提交修复了这个问题，你拉一下代码。

**Comment by KenChoi1992** [comment]
@EpicWang 发布了新版本，请更新一下代码。
