### ISSUE TITLE
自定义消息是否支持分享类消息？

### ISSUE THREAD

**Issue by musicode** [jpush/aurora-imui#70]
![image](https://user-images.githubusercontent.com/2732303/27862529-2d0a5ea8-61b8-11e7-9e7d-87ec8694f150.png)

是否支持类似这样的 title + content + image，并且支持点击呢？

**Comment by huangminlinux** [comment]
ReactNative 暂时不会支持, 如果是原生应用可以使用自定义消息实现。

**Comment by KenChoi1992** [comment]
@musicode 后续会支持常见的自定义消息。

**Comment by musicode** [comment]
目前我的需求有两种：

1. 分享类：title + content + image
2. 灰字类：消息时间、群通知（如谁进群了、谁被踢了、群公告被修改了等简短的文本通知）

可有可无的：

1. 正在输入....

再次感谢，希望能给一个大概的时间表可以么？

**Comment by Zhiw** [comment]
@KenChoi1992 请问可以开放位置消息类型吗，和自定义消息类型一样，界面和具体实现由开发者自己实现

**Comment by KenChoi1992** [comment]
@musicode 第二种已经支持了，只要将 `MessageType` 改为 `EVENT` 就行了。第一种还没实现，估计要等几个星期。

**Comment by KenChoi1992** [comment]
@Zhiw 已经有了，`MessageType` 为 `SEND_LOCATION` 和 `RECEIVE_LOCATION`

**Comment by Zhiw** [comment]
@KenChoi1992 我看到了消息类型，可是 `Adapter` 里面没有对位置类型进行处理，同时 `HolderConfig` 里也没有提供位置相关的 holder 和 layout，不知是我理解错误还是写漏了。

**Comment by KenChoi1992** [comment]
@Zhiw 这样啊，我下个版本加上吧

**Comment by weavey** [comment]
一个消息列表能支持多种自定义消息吗  看到源码里面 自定义消息是调用setSendCustomMsg 赋值的方式  而不是用add存储

**Comment by KenChoi1992** [comment]
@weavey 下个版本支持。

**Comment by huangminlinux** [comment]
可以升级到 [0.5.10](https://github.com/jpush/aurora-imui/releases/tag/0.5.10-rn) 用自定义消息实现   ，具体用法可以参考 demo。

**Comment by KenChoi1992** [comment]
@weavey 发布了。https://github.com/jpush/aurora-imui/releases/tag/0.5.9
