### ISSUE TITLE
要是可以下载dome的apk就更好了

### ISSUE THREAD

**Issue by z-chu** [jpush/aurora-imui#71]

**Comment by KenChoi1992** [comment]
可以，下次把 apk 打包到 Release 下。

**Comment by KenChoi1992** [comment]
@z-chu 已更新。

**Comment by z-chu** [comment]
@KenChoi1992  大兄弟，你打的这个包貌似手机装不了啊
错误信息：
Failure [INSTALL_FAILED_TEST_ONLY]
