### ISSUE TITLE
点击输入框,软键盘出来以后会挡住屏幕底部的消息.这个能优化吗？

### ISSUE THREAD

**Issue by MariShunxiang** [jpush/aurora-imui#72]
点击输入框,软键盘出来以后会挡住屏幕底部的消息.这个能优化吗？

**Comment by KenChoi1992** [comment]
新版本还有这个问题吗？添加了 EditText 的点击事件，在这里将列表滚动到底部：
```
 mChatView.setOnTouchEditTextListener(new OnClickEditTextListener() {
            @Override
            public void onTouchEditText() {
                mAdapter.getLayoutManager().scrollToPosition(0);
            }
        });
```

**Comment by Zhiw** [comment]
请问这是新版本吗？0.2.0 没有看到这个方法

**Comment by KenChoi1992** [comment]
新版本

**Comment by Zhiw** [comment]
原来在 `releases` 里面更新了，我参考的文档上还写着 `0.2.0`

**Comment by Zhiw** [comment]
请问新版本正式发布了吗？为什么 chatinput 我同步不到 `0.4.0` 的代码，messagelist 可以 `0.4.0`

**Comment by KenChoi1992** [comment]
@Zhiw  messagelist 最新版本是 0.4.2，chatinput 最新版本是 0.3.4-beta

**Comment by Zhiw** [comment]
@KenChoi1992 感谢回复，希望在 release 或者 README 里面说明最新版本的情况，也就减少我这样的疑问了

**Comment by KenChoi1992** [comment]
@Zhiw 更新了，看看 Release
