### ISSUE TITLE
React Native 布局错误，奔溃没有提示

### ISSUE THREAD

**Issue by Gd362660870** [jpush/aurora-imui#76]
最新版本与0.3.2版本编译不过，
0.3.0编译成功
inputView 点击图片
![img_0813](https://user-images.githubusercontent.com/18651571/28015953-eafb9270-65a4-11e7-87d9-9b0878633abc.PNG)
inputView 点击语音
![img_0814](https://user-images.githubusercontent.com/18651571/28015942-de4f07c8-65a4-11e7-932a-b5592607f217.PNG)
inputView 点击相册
![image](https://user-images.githubusercontent.com/18651571/28015980-0c28e970-65a5-11e7-988d-5fb3593b2bcf.png)
然后......点击发送任何消息..无任何提示闪退

**Comment by Gd362660870** [comment]
RN0.44.3 run 0.30.0

**Comment by huangminlinux** [comment]
当前最新版本是，建议更新到 0.4.3

**Comment by Gd362660870** [comment]
@huangminlinux 首次集成是0.4.3，ios 与android都出现bug，我再次尝试0.4.3版本希望编译顺利

**Comment by Gd362660870** [comment]
@huangminlinux 
再次集成0.4.3版本，RN版本0.44.3 ，希望能帮助我解决这个方案
![1](https://user-images.githubusercontent.com/18651571/28101406-e3f165e8-66fa-11e7-8ef1-1dcc48c741d5.png)
![2](https://user-images.githubusercontent.com/18651571/28101408-e4019044-66fa-11e7-8a4f-046e9c6507f5.png)
![3](https://user-images.githubusercontent.com/18651571/28101407-e3fb3820-66fa-11e7-89e1-9acb4ca6476d.png)
![4](https://user-images.githubusercontent.com/18651571/28101409-e4086e14-66fa-11e7-9694-5db9ba05325f.png)
![5](https://user-images.githubusercontent.com/18651571/28101410-e40c8c92-66fa-11e7-8a7f-3726e1f1441d.png)
![6](https://user-images.githubusercontent.com/18651571/28101411-e41fcf00-66fa-11e7-8cb5-a8e05a68250d.png)

**Comment by huangminlinux** [comment]
我这边测一下。

**Comment by huangminlinux** [comment]
这边测试没问题， 新建项目也没发现问题

环境
```
react-native-cli: 0.2.0
react-native: 0.44.0

xcode8.3.3
```

插件版本
```
"aurora-imui-react-native": "^0.4.3"
```

**Comment by huangminlinux** [comment]
布局问题，在 0.4.10 以上版本应该不会再出现了。
编译错误，可以升级 xcode 到最新版本。 先关闭这个 issue 如果还有问题可以重新打开。
