### ISSUE TITLE
关于avatar和音频的问题😀

### ISSUE THREAD

**Issue by pftom** [jpush/aurora-imui#77]
1.请问这个`avatar path`，是指在文件夹下的路径，还是ios工程或者android工程下的路径
![image](https://user-images.githubusercontent.com/26423749/28248283-df93063c-6a74-11e7-993e-4214c3928ba4.png)

2.请问这个语音消息能录制了能直接返回音频数据嘛？或者怎么样取到音频数据？还有从SDK读取到的音频数据如何加入到消息队列播放呢？
![image](https://user-images.githubusercontent.com/26423749/28248316-6dbfb5d6-6a75-11e7-987c-5867397a21e7.png)

**Comment by huangminlinux** [comment]
1. 工程下的路径
2. 音频录制完成后，会返回音频文件的路径，如果需要音频数据可以读取这个文件内容， 另外你指的 SDK 是指 JMessage 吗？

**Comment by KenChoi1992** [comment]
@powerformer Android 的话，可以是工程下的路径，也可以是本地的路径。

**Comment by powerformer** [comment]
对JMessage,就是我现在使用JMessage，如果把存在云端的语音消息获取下来，那么如何加入要消息队列播放呢？

**Comment by KenChoi1992** [comment]
@powerformer 构造一条语音消息。然后使用接口 appendMessage
