### ISSUE TITLE
可以增加图文布局吗，因为项目要求展示新闻类的消息，而且可以点击时进入网页链接。

### ISSUE THREAD

**Issue by Jorble** [jpush/aurora-imui#78]

**Comment by KenChoi1992** [comment]
@Jorble 有计划要支持常见的自定义消息。

**Comment by huangminlinux** [comment]
react-native 的话可以升级到 [0.5.10](https://github.com/jpush/aurora-imui/releases/tag/0.5.10-rn) 用自定义消息实现   ，具体用法可以参考 demo。
