### ISSUE TITLE
RN安装完这个库出错

### ISSUE THREAD

**Issue by xiaochong44** [jpush/aurora-imui#82]
有集成了官方的JPUSH插件，没安装imui时正常不出错。安装完imui一直报这个错误，
难道和jcore有冲突？
Execution failed for task ':app:prepareYuanjingJcoreReactNativeUnspecifiedLibrary'.
> Could not expand ZIP 'E:\yuanjing\node_modules\jcore-react-native\android\build\outputs\aar\jcore-react-native-release.aar'.

**Comment by KenChoi1992** [comment]
@xiaochong44 imui 没有用到 jcore
