### ISSUE TITLE
编译 RCTAuroralMUI 错误

### ISSUE THREAD

**Issue by powerformer** [jpush/aurora-imui#85]
![image](https://user-images.githubusercontent.com/26423749/28650618-adfad328-72af-11e7-9d1a-96b7e265d604.png)
![image](https://user-images.githubusercontent.com/26423749/28650629-b8c0f53a-72af-11e7-9c96-5b3bdad367ff.png)
![image](https://user-images.githubusercontent.com/26423749/28650634-be1c0f06-72af-11e7-8f5a-224b82c87ec8.png)

**Comment by huangminlinux** [comment]
通过什么方式安装的？

**Comment by powerformer** [comment]
通过 
```
npm install aurora-imui-react-native@^0.4.3 --save
react-native link
```
安装，之后按照步骤，编译到这一步就报错，
```
"react": "16.0.0-alpha.6",
"react-native": "0.44.2",
```

**Comment by huangminlinux** [comment]
提示的是 React Native 的类库没有找到，
看看 React Native 相关的类库是否出现问题了。
重新编译 React Native 类库试试。

**Comment by powerformer** [comment]
@huangminlinux 
这次编译遇到了一下问题
![image](https://user-images.githubusercontent.com/26423749/28994115-d583d296-79f8-11e7-9f9c-13802dff2df6.png)

**Comment by huangminlinux** [comment]
@powerformer  xcode 用什么什么版本？

**Comment by huangminlinux** [comment]
这个问题应该是 xcode 版本问题，建议升级到最新版本的 xcode ，先关闭这个 issue 如果还有问题，可以重新打开。
