### ISSUE TITLE
是否支持表情？

### ISSUE THREAD

**Issue by musicode** [jpush/aurora-imui#9]
是否有默认表情，以及是否提供自定义表情的扩展方式？

**Comment by KenChoi1992** [comment]
@musicode 暂不支持表情，以后会支持。

**Comment by musicode** [comment]
@KenChoi1992 群聊会支持吗

**Comment by xiaosongfu** [comment]
有开发计划吗？大概多久可以呢？

**Comment by musicode** [comment]
表情，复制、删除消息，这些都应该尽快支持吧，一对一聊天的场景，这些都是必须的，群聊才会增加一堆功能

**Comment by musicode** [comment]
在支持 RN 后，表情可否提上计划呢？

**Comment by huangminlinux** [comment]
开发计划可以在这里查看 👉 [开发计划](https://github.com/jpush/aurora-imui/projects)

**Comment by musicode** [comment]
@huangminlinux  请问表情最近有啥进度么？

**Comment by huangminlinux** [comment]
近期有其他的开发任务，表情功能可能要缓一缓。

**Comment by musicode** [comment]
@huangminlinux 大概的时间可否说一下呢

**Comment by huangminlinux** [comment]
预计 9 月份开始开发

**Comment by liujiyao** [comment]
表情大概什么时候可以添加上呀？

**Comment by huangminlinux** [comment]
@liujiyao 这月底会出一个版本，添加表情功能

**Comment by huangminlinux** [comment]
最新版本已经支持，我先关闭这个 issue
