### ISSUE TITLE
从云端传来的 url，png格式，加入message队列就会报性能错误

### ISSUE THREAD

**Issue by powerformer** [jpush/aurora-imui#90]
![image](https://user-images.githubusercontent.com/26423749/29003015-92b7fe30-7ae1-11e7-837f-75edb956dc2c.png)
![image](https://user-images.githubusercontent.com/26423749/29003025-ae23b81c-7ae1-11e7-9cb0-be3408bc802b.png)

**Comment by huangminlinux** [comment]
append 图片消息，iOS 占不支持 url， 需要传本地图片路径。
